# PPO VM Allocation Experiments

This notebook trains and evaluates PPO agents for VM allocation using the existing DRL pipeline:

- `rl/environment.py`: `VMAllocationEnv` (Gymnasium environment)
- `rl/config.py`: PPO and reward configuration  
- `train_ppo.py`: training script
- `eval_ppo.py`: evaluation script

## Current Config (Updated 2024-12-16) - Balanced Training

| Parameter | Training | Evaluation | Reason |
|-----------|----------|------------|--------|
| `episode_length` | **1440 (12h)** | 17150 (full test) | Half daily cycle |
| `total_timesteps` | **2,000,000** | - | ~1,388 episodes |
| `horizon` | 120 (60min) | 120 | Forecast look-ahead |
| `n_envs` | 8 | - | Parallel training |

**Expected training time**: ~4-5 hours (at 118 it/s)

**Note**: LP vs PPO comparison is done in `lp_vs_ppo_comparison.ipynb`.

In [1]:
# Imports and configuration

from pathlib import Path

# Module imports
import importlib
import train_ppo as train_ppo_module
import eval_ppo as eval_ppo_module
import rl.config as rl_config_module

from rl.config import PPOConfig, SCENARIO_OVERLOAD, SCENARIO_COST
from train_ppo import train_ppo
from eval_ppo import evaluate_scenario, print_comparison

# Reload modules to pick up latest code when notebook stays open
importlib.reload(train_ppo_module)
importlib.reload(eval_ppo_module)
importlib.reload(rl_config_module)

# Refresh config after reload
from rl.config import PPOConfig, SCENARIO_OVERLOAD, SCENARIO_COST

PROJECT_ROOT = Path.cwd()
print("Project root:", PROJECT_ROOT)

# Show current default PPO configuration
config = PPOConfig()
config

Project root: e:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure

PPOConfig(learning_rate=0.0003, n_steps=2048, batch_size=64, n_epochs=10, gamma=0.99, gae_lambda=0.95, clip_range=0.2, clip_range_vf=None, ent_coef=0.01, vf_coef=0.5, max_grad_norm=0.5, episode_length=1440, horizon=120, total_timesteps=2000000, tensorboard_log='./tensorboard_logs/', log_interval=10, save_freq=10000)

In [2]:
# Configuration (for training or evaluation)
from copy import deepcopy

# Number of parallel envs
N_ENVS = 8

# Create experiment config
exp_config = deepcopy(config)

# ============================================================
# TRAINING CONFIG (Balanced - 12 hours episode)
# ============================================================
# episode_length for TRAINING: 1440 = 12 hours (half daily cycle)
# Balance between learning patterns and training speed
TRAIN_EPISODE_LENGTH = 1440  # 12 hours

# total_timesteps: 2M = ~1,388 episodes with episode_length=1440
exp_config.total_timesteps = 2_000_000

# ============================================================
# EVALUATION CONFIG
# ============================================================
# episode_length for EVALUATION: 17150 = full test set (~6 days)
EVAL_EPISODE_LENGTH = 17150

# Calculate expected metrics
n_episodes = exp_config.total_timesteps // TRAIN_EPISODE_LENGTH
train_hours = TRAIN_EPISODE_LENGTH * 30 / 3600
eval_hours = EVAL_EPISODE_LENGTH * 30 / 3600

print("=" * 60)
print("📋 CONFIGURATION")
print("=" * 60)
print(f"\n🏋️ TRAINING:")
print(f"   • episode_length:   {TRAIN_EPISODE_LENGTH} steps ({train_hours:.0f} hours)")
print(f"   • total_timesteps:  {exp_config.total_timesteps:,}")
print(f"   • expected episodes: ~{n_episodes:,}")
print(f"   • horizon:          {exp_config.horizon} steps")
print(f"   • n_envs:           {N_ENVS}")
print(f"\n📊 EVALUATION:")
print(f"   • episode_length:   {EVAL_EPISODE_LENGTH} steps ({eval_hours:.1f} hours = full test)")
print("=" * 60)

============================================================
📋 CONFIGURATION
============================================================

🏋️ TRAINING:
   • episode_length:   1440 steps (12 hours)
   • total_timesteps:  2,000,000
   • expected episodes: ~1,388
   • horizon:          120 steps
   • n_envs:           8

📊 EVALUATION:
   • episode_length:   17150 steps (142.9 hours = full test)
============================================================

In [3]:
# ============================================================
# TRAINING
# ============================================================
# Set episode_length for training (daily pattern = 2880)
exp_config.episode_length = TRAIN_EPISODE_LENGTH

print("=" * 60)
print("🚀 STARTING TRAINING")
print("=" * 60)
print(f"   • total_timesteps:  {exp_config.total_timesteps:,}")
print(f"   • episode_length:   {exp_config.episode_length} steps (12 hours)")
print(f"   • horizon:          {exp_config.horizon} steps")
print(f"   • n_envs:           {N_ENVS}")
print(f"   • expected time:    ~4-5 hours (with 118 it/s)")
print("=" * 60)

# Train OVERLOAD scenario (Minimize Resource Overload)
print("\n[1/2] Training OVERLOAD scenario...")
model_overload = train_ppo(
    scenario=SCENARIO_OVERLOAD,
    config=exp_config,
    total_timesteps=exp_config.total_timesteps,
    n_envs=N_ENVS,
    continue_training=False,
)

# Train COST scenario (Minimize Operational Cost)
print("\n[2/2] Training COST scenario...")
model_cost = train_ppo(
    scenario=SCENARIO_COST,
    config=exp_config,
    total_timesteps=exp_config.total_timesteps,
    n_envs=N_ENVS,
    continue_training=False,
)

print("\n✅ Training complete for both scenarios!")

============================================================
🚀 STARTING TRAINING
============================================================
   • total_timesteps:  2,000,000
   • episode_length:   1440 steps (12 hours)
   • horizon:          120 steps
   • n_envs:           8
   • expected time:    ~4-5 hours (with 118 it/s)
============================================================

[1/2] Training OVERLOAD scenario...

============================================================
Training PPO for scenario: OVERLOAD
============================================================
Latest model: models\random_forest_cpu_total_usage_20251111_221930.pkl
✓ Model loaded: models\random_forest_cpu_total_usage_20251111_221930.pkl
  Model: random_forest
  Target: cpu_total_usage
  Saved at: 2025-11-11 22:19:30
Latest model: models\svr_memory_usage_pct_20251111_184735.pkl
✓ Model loaded: models\svr_memory_usage_pct_20251111_184735.pkl
  Model: svr
  Target: memory_usage_pct
  Saved at: 2025-11-11 18:47:35
Latest model: models\random_forest_system_load_20251111_221944.pkl
✓ Model loaded: models\random_forest_system_load_20251111_221944.pkl
  Model: random_forest
  Target: system_load
  Saved at: 2025-11-11 22:19:44
Creating new PPO model
Using cpu device

Starting training for 2,000,000 timesteps...
Logging to ./tensorboard_logs/PPO_14

Output()

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -4.47e+05 |
| time/              |           |
|    fps             | 127       |
|    iterations      | 1         |
|    time_elapsed    | 128       |
|    total_timesteps | 16384     |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -4.46e+05   |
| time/                   |             |
|    fps                  | 121         |
|    iterations           | 2           |
|    time_elapsed         | 269         |
|    total_timesteps      | 32768       |
| train/                  |             |
|    approx_kl            | 0.030058647 |
|    clip_fraction        | 0.274       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.58       |
|    explained_variance   | -1.45       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0954     |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0524     |
|    value_loss           | 0.152       |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -4.42e+05  |
| time/                   |            |
|    fps                  | 119        |
|    iterations           | 3          |
|    time_elapsed         | 411        |
|    total_timesteps      | 49152      |
| train/                  |            |
|    approx_kl            | 0.03019439 |
|    clip_fraction        | 0.311      |
|    clip_range           | 0.2        |
|    entropy_loss         | -9.54      |
|    explained_variance   | -0.269     |
|    learning_rate        | 0.0003     |
|    loss                 | -0.159     |
|    n_updates            | 20         |
|    policy_gradient_loss | -0.0654    |
|    value_loss           | 0.0257     |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -4.37e+05   |
| time/                   |             |
|    fps                  | 114         |
|    iterations           | 4           |
|    time_elapsed         | 574         |
|    total_timesteps      | 65536       |
| train/                  |             |
|    approx_kl            | 0.033367336 |
|    clip_fraction        | 0.345       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.5        |
|    explained_variance   | 0.039       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.176      |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.069      |
|    value_loss           | 0.0148      |
-----------------------------------------

Eval num_timesteps=80000, episode_reward=-164634.55 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -1.65e+05  |
| time/                   |            |
|    total_timesteps      | 80000      |
| train/                  |            |
|    approx_kl            | 0.03530638 |
|    clip_fraction        | 0.378      |
|    clip_range           | 0.2        |
|    entropy_loss         | -9.46      |
|    explained_variance   | -0.0677    |
|    learning_rate        | 0.0003     |
|    loss                 | -0.2       |
|    n_updates            | 40         |
|    policy_gradient_loss | -0.0717    |
|    value_loss           | 0.00973    |
----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -4.28e+05 |
| time/              |           |
|    fps             | 112       |
|    iterations      | 5         |
|    time_elapsed    | 730       |
|    total_timesteps | 81920     |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -4.23e+05  |
| time/                   |            |
|    fps                  | 113        |
|    iterations           | 6          |
|    time_elapsed         | 869        |
|    total_timesteps      | 98304      |
| train/                  |            |
|    approx_kl            | 0.03926206 |
|    clip_fraction        | 0.4        |
|    clip_range           | 0.2        |
|    entropy_loss         | -9.4       |
|    explained_variance   | 0.0246     |
|    learning_rate        | 0.0003     |
|    loss                 | -0.219     |
|    n_updates            | 50         |
|    policy_gradient_loss | -0.0748    |
|    value_loss           | 0.00874    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -4.17e+05   |
| time/                   |             |
|    fps                  | 112         |
|    iterations           | 7           |
|    time_elapsed         | 1018        |
|    total_timesteps      | 114688      |
| train/                  |             |
|    approx_kl            | 0.042456444 |
|    clip_fraction        | 0.429       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.33       |
|    explained_variance   | 0.0951      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.219      |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.0792     |
|    value_loss           | 0.00668     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -4.04e+05  |
| time/                   |            |
|    fps                  | 112        |
|    iterations           | 8          |
|    time_elapsed         | 1167       |
|    total_timesteps      | 131072     |
| train/                  |            |
|    approx_kl            | 0.04300238 |
|    clip_fraction        | 0.435      |
|    clip_range           | 0.2        |
|    entropy_loss         | -9.25      |
|    explained_variance   | -0.0762    |
|    learning_rate        | 0.0003     |
|    loss                 | -0.223     |
|    n_updates            | 70         |
|    policy_gradient_loss | -0.0797    |
|    value_loss           | 0.00582    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -3.98e+05   |
| time/                   |             |
|    fps                  | 111         |
|    iterations           | 9           |
|    time_elapsed         | 1323        |
|    total_timesteps      | 147456      |
| train/                  |             |
|    approx_kl            | 0.044842556 |
|    clip_fraction        | 0.443       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.15       |
|    explained_variance   | 0.37        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.183      |
|    n_updates            | 80          |
|    policy_gradient_loss | -0.0785     |
|    value_loss           | 0.00529     |
-----------------------------------------

Eval num_timesteps=160000, episode_reward=-137157.46 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -1.37e+05   |
| time/                   |             |
|    total_timesteps      | 160000      |
| train/                  |             |
|    approx_kl            | 0.045356676 |
|    clip_fraction        | 0.446       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.06       |
|    explained_variance   | 0.404       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.192      |
|    n_updates            | 90          |
|    policy_gradient_loss | -0.0781     |
|    value_loss           | 0.00505     |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -3.77e+05 |
| time/              |           |
|    fps             | 110       |
|    iterations      | 10        |
|    time_elapsed    | 1477      |
|    total_timesteps | 163840    |
----------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 1.44e+03  |
|    ep_rew_mean          | -3.65e+05 |
| time/                   |           |
|    fps                  | 110       |
|    iterations           | 11        |
|    time_elapsed         | 1624      |
|    total_timesteps      | 180224    |
| train/                  |           |
|    approx_kl            | 0.0461371 |
|    clip_fraction        | 0.447     |
|    clip_range           | 0.2       |
|    entropy_loss         | -8.93     |
|    explained_variance   | 0.659     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.155    |
|    n_updates            | 100       |
|    policy_gradient_loss | -0.0759   |
|    value_loss           | 0.00431   |
---------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -3.38e+05   |
| time/                   |             |
|    fps                  | 110         |
|    iterations           | 12          |
|    time_elapsed         | 1774        |
|    total_timesteps      | 196608      |
| train/                  |             |
|    approx_kl            | 0.049382046 |
|    clip_fraction        | 0.451       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.84       |
|    explained_variance   | 0.74        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.146      |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.0783     |
|    value_loss           | 0.00404     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -3.24e+05   |
| time/                   |             |
|    fps                  | 111         |
|    iterations           | 13          |
|    time_elapsed         | 1914        |
|    total_timesteps      | 212992      |
| train/                  |             |
|    approx_kl            | 0.048989262 |
|    clip_fraction        | 0.454       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.71       |
|    explained_variance   | 0.787       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.176      |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.0758     |
|    value_loss           | 0.00391     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -3.11e+05   |
| time/                   |             |
|    fps                  | 111         |
|    iterations           | 14          |
|    time_elapsed         | 2054        |
|    total_timesteps      | 229376      |
| train/                  |             |
|    approx_kl            | 0.050896436 |
|    clip_fraction        | 0.457       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.62       |
|    explained_variance   | 0.847       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.194      |
|    n_updates            | 130         |
|    policy_gradient_loss | -0.0777     |
|    value_loss           | 0.00329     |
-----------------------------------------

Eval num_timesteps=240000, episode_reward=-158943.25 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -1.59e+05   |
| time/                   |             |
|    total_timesteps      | 240000      |
| train/                  |             |
|    approx_kl            | 0.049361445 |
|    clip_fraction        | 0.451       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.49       |
|    explained_variance   | 0.791       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.172      |
|    n_updates            | 140         |
|    policy_gradient_loss | -0.074      |
|    value_loss           | 0.00317     |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -2.86e+05 |
| time/              |           |
|    fps             | 111       |
|    iterations      | 15        |
|    time_elapsed    | 2203      |
|    total_timesteps | 245760    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -2.74e+05   |
| time/                   |             |
|    fps                  | 111         |
|    iterations           | 16          |
|    time_elapsed         | 2343        |
|    total_timesteps      | 262144      |
| train/                  |             |
|    approx_kl            | 0.051366188 |
|    clip_fraction        | 0.453       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.39       |
|    explained_variance   | 0.773       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.195      |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.0787     |
|    value_loss           | 0.00314     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -2.51e+05   |
| time/                   |             |
|    fps                  | 112         |
|    iterations           | 17          |
|    time_elapsed         | 2483        |
|    total_timesteps      | 278528      |
| train/                  |             |
|    approx_kl            | 0.048974514 |
|    clip_fraction        | 0.445       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.28       |
|    explained_variance   | 0.832       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.197      |
|    n_updates            | 160         |
|    policy_gradient_loss | -0.0733     |
|    value_loss           | 0.00294     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -2.41e+05   |
| time/                   |             |
|    fps                  | 112         |
|    iterations           | 18          |
|    time_elapsed         | 2622        |
|    total_timesteps      | 294912      |
| train/                  |             |
|    approx_kl            | 0.051181912 |
|    clip_fraction        | 0.453       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.17       |
|    explained_variance   | 0.829       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.157      |
|    n_updates            | 170         |
|    policy_gradient_loss | -0.0756     |
|    value_loss           | 0.00256     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -2.21e+05   |
| time/                   |             |
|    fps                  | 112         |
|    iterations           | 19          |
|    time_elapsed         | 2762        |
|    total_timesteps      | 311296      |
| train/                  |             |
|    approx_kl            | 0.053938057 |
|    clip_fraction        | 0.462       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.08       |
|    explained_variance   | 0.827       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.188      |
|    n_updates            | 180         |
|    policy_gradient_loss | -0.0775     |
|    value_loss           | 0.00259     |
-----------------------------------------

Eval num_timesteps=320000, episode_reward=-84148.36 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -8.41e+04   |
| time/                   |             |
|    total_timesteps      | 320000      |
| train/                  |             |
|    approx_kl            | 0.049029864 |
|    clip_fraction        | 0.436       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.89       |
|    explained_variance   | 0.892       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.166      |
|    n_updates            | 190         |
|    policy_gradient_loss | -0.0687     |
|    value_loss           | 0.00209     |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -2.12e+05 |
| time/              |           |
|    fps             | 112       |
|    iterations      | 20        |
|    time_elapsed    | 2911      |
|    total_timesteps | 327680    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.05e+05  |
| time/                   |            |
|    fps                  | 112        |
|    iterations           | 21         |
|    time_elapsed         | 3049       |
|    total_timesteps      | 344064     |
| train/                  |            |
|    approx_kl            | 0.05608241 |
|    clip_fraction        | 0.461      |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.9       |
|    explained_variance   | 0.889      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.175     |
|    n_updates            | 200        |
|    policy_gradient_loss | -0.0759    |
|    value_loss           | 0.00213    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.91e+05   |
| time/                   |             |
|    fps                  | 113         |
|    iterations           | 22          |
|    time_elapsed         | 3187        |
|    total_timesteps      | 360448      |
| train/                  |             |
|    approx_kl            | 0.057352863 |
|    clip_fraction        | 0.46        |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.82       |
|    explained_variance   | 0.905       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.166      |
|    n_updates            | 210         |
|    policy_gradient_loss | -0.0774     |
|    value_loss           | 0.00218     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.84e+05  |
| time/                   |            |
|    fps                  | 113        |
|    iterations           | 23         |
|    time_elapsed         | 3326       |
|    total_timesteps      | 376832     |
| train/                  |            |
|    approx_kl            | 0.05664657 |
|    clip_fraction        | 0.467      |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.69      |
|    explained_variance   | 0.912      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.17      |
|    n_updates            | 220        |
|    policy_gradient_loss | -0.0786    |
|    value_loss           | 0.0017     |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.71e+05   |
| time/                   |             |
|    fps                  | 113         |
|    iterations           | 24          |
|    time_elapsed         | 3464        |
|    total_timesteps      | 393216      |
| train/                  |             |
|    approx_kl            | 0.055307794 |
|    clip_fraction        | 0.45        |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.54       |
|    explained_variance   | 0.916       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.173      |
|    n_updates            | 230         |
|    policy_gradient_loss | -0.0734     |
|    value_loss           | 0.00167     |
-----------------------------------------

Eval num_timesteps=400000, episode_reward=-63261.11 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -6.33e+04  |
| time/                   |            |
|    total_timesteps      | 400000     |
| train/                  |            |
|    approx_kl            | 0.05537544 |
|    clip_fraction        | 0.458      |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.45      |
|    explained_variance   | 0.925      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.183     |
|    n_updates            | 240        |
|    policy_gradient_loss | -0.0749    |
|    value_loss           | 0.00137    |
----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -1.65e+05 |
| time/              |           |
|    fps             | 113       |
|    iterations      | 25        |
|    time_elapsed    | 3610      |
|    total_timesteps | 409600    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.61e+05  |
| time/                   |            |
|    fps                  | 113        |
|    iterations           | 26         |
|    time_elapsed         | 3748       |
|    total_timesteps      | 425984     |
| train/                  |            |
|    approx_kl            | 0.05630645 |
|    clip_fraction        | 0.454      |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.42      |
|    explained_variance   | 0.912      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.164     |
|    n_updates            | 250        |
|    policy_gradient_loss | -0.0754    |
|    value_loss           | 0.00131    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.5e+05    |
| time/                   |             |
|    fps                  | 113         |
|    iterations           | 27          |
|    time_elapsed         | 3899        |
|    total_timesteps      | 442368      |
| train/                  |             |
|    approx_kl            | 0.057390697 |
|    clip_fraction        | 0.456       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.24       |
|    explained_variance   | 0.945       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.185      |
|    n_updates            | 260         |
|    policy_gradient_loss | -0.0762     |
|    value_loss           | 0.0013      |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.45e+05   |
| time/                   |             |
|    fps                  | 113         |
|    iterations           | 28          |
|    time_elapsed         | 4038        |
|    total_timesteps      | 458752      |
| train/                  |             |
|    approx_kl            | 0.056111388 |
|    clip_fraction        | 0.45        |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.12       |
|    explained_variance   | 0.934       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.164      |
|    n_updates            | 270         |
|    policy_gradient_loss | -0.0727     |
|    value_loss           | 0.00106     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.34e+05   |
| time/                   |             |
|    fps                  | 113         |
|    iterations           | 29          |
|    time_elapsed         | 4177        |
|    total_timesteps      | 475136      |
| train/                  |             |
|    approx_kl            | 0.056080446 |
|    clip_fraction        | 0.447       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.98       |
|    explained_variance   | 0.961       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.135      |
|    n_updates            | 280         |
|    policy_gradient_loss | -0.0708     |
|    value_loss           | 0.000983    |
-----------------------------------------

Eval num_timesteps=480000, episode_reward=-107978.18 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -1.08e+05  |
| time/                   |            |
|    total_timesteps      | 480000     |
| train/                  |            |
|    approx_kl            | 0.05456038 |
|    clip_fraction        | 0.447      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.89      |
|    explained_variance   | 0.943      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.169     |
|    n_updates            | 290        |
|    policy_gradient_loss | -0.0703    |
|    value_loss           | 0.00109    |
----------------------------------------

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 1.44e+03 |
|    ep_rew_mean     | -1.3e+05 |
| time/              |          |
|    fps             | 113      |
|    iterations      | 30       |
|    time_elapsed    | 4323     |
|    total_timesteps | 491520   |
---------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.21e+05   |
| time/                   |             |
|    fps                  | 113         |
|    iterations           | 31          |
|    time_elapsed         | 4461        |
|    total_timesteps      | 507904      |
| train/                  |             |
|    approx_kl            | 0.060523286 |
|    clip_fraction        | 0.463       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.9        |
|    explained_variance   | 0.949       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.165      |
|    n_updates            | 300         |
|    policy_gradient_loss | -0.0752     |
|    value_loss           | 0.00106     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.17e+05   |
| time/                   |             |
|    fps                  | 113         |
|    iterations           | 32          |
|    time_elapsed         | 4600        |
|    total_timesteps      | 524288      |
| train/                  |             |
|    approx_kl            | 0.054827176 |
|    clip_fraction        | 0.443       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.7        |
|    explained_variance   | 0.942       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.151      |
|    n_updates            | 310         |
|    policy_gradient_loss | -0.0697     |
|    value_loss           | 0.00101     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.13e+05   |
| time/                   |             |
|    fps                  | 114         |
|    iterations           | 33          |
|    time_elapsed         | 4739        |
|    total_timesteps      | 540672      |
| train/                  |             |
|    approx_kl            | 0.056981243 |
|    clip_fraction        | 0.453       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.67       |
|    explained_variance   | 0.939       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.183      |
|    n_updates            | 320         |
|    policy_gradient_loss | -0.0731     |
|    value_loss           | 0.000924    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.05e+05   |
| time/                   |             |
|    fps                  | 114         |
|    iterations           | 34          |
|    time_elapsed         | 4877        |
|    total_timesteps      | 557056      |
| train/                  |             |
|    approx_kl            | 0.059164353 |
|    clip_fraction        | 0.453       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.62       |
|    explained_variance   | 0.901       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.164      |
|    n_updates            | 330         |
|    policy_gradient_loss | -0.0761     |
|    value_loss           | 0.000989    |
-----------------------------------------

Eval num_timesteps=560000, episode_reward=-76870.83 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -7.69e+04   |
| time/                   |             |
|    total_timesteps      | 560000      |
| train/                  |             |
|    approx_kl            | 0.055967957 |
|    clip_fraction        | 0.441       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.47       |
|    explained_variance   | 0.935       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.163      |
|    n_updates            | 340         |
|    policy_gradient_loss | -0.0696     |
|    value_loss           | 0.000776    |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -1.01e+05 |
| time/              |           |
|    fps             | 114       |
|    iterations      | 35        |
|    time_elapsed    | 5024      |
|    total_timesteps | 573440    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -9.54e+04   |
| time/                   |             |
|    fps                  | 114         |
|    iterations           | 36          |
|    time_elapsed         | 5162        |
|    total_timesteps      | 589824      |
| train/                  |             |
|    approx_kl            | 0.054068826 |
|    clip_fraction        | 0.44        |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.32       |
|    explained_variance   | 0.95        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.137      |
|    n_updates            | 350         |
|    policy_gradient_loss | -0.0712     |
|    value_loss           | 0.000696    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -9.32e+04   |
| time/                   |             |
|    fps                  | 114         |
|    iterations           | 37          |
|    time_elapsed         | 5301        |
|    total_timesteps      | 606208      |
| train/                  |             |
|    approx_kl            | 0.058859266 |
|    clip_fraction        | 0.445       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.38       |
|    explained_variance   | 0.942       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.17       |
|    n_updates            | 360         |
|    policy_gradient_loss | -0.0732     |
|    value_loss           | 0.00083     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -9.06e+04  |
| time/                   |            |
|    fps                  | 114        |
|    iterations           | 38         |
|    time_elapsed         | 5440       |
|    total_timesteps      | 622592     |
| train/                  |            |
|    approx_kl            | 0.06330888 |
|    clip_fraction        | 0.465      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.38      |
|    explained_variance   | 0.93       |
|    learning_rate        | 0.0003     |
|    loss                 | -0.174     |
|    n_updates            | 370        |
|    policy_gradient_loss | -0.0753    |
|    value_loss           | 0.000771   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -8.74e+04  |
| time/                   |            |
|    fps                  | 114        |
|    iterations           | 39         |
|    time_elapsed         | 5578       |
|    total_timesteps      | 638976     |
| train/                  |            |
|    approx_kl            | 0.06485717 |
|    clip_fraction        | 0.47       |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.36      |
|    explained_variance   | 0.942      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.181     |
|    n_updates            | 380        |
|    policy_gradient_loss | -0.0769    |
|    value_loss           | 0.00081    |
----------------------------------------

Eval num_timesteps=640000, episode_reward=-77183.49 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -7.72e+04   |
| time/                   |             |
|    total_timesteps      | 640000      |
| train/                  |             |
|    approx_kl            | 0.055356525 |
|    clip_fraction        | 0.438       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.04       |
|    explained_variance   | 0.937       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.146      |
|    n_updates            | 390         |
|    policy_gradient_loss | -0.0645     |
|    value_loss           | 0.000599    |
-----------------------------------------

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 1.44e+03 |
|    ep_rew_mean     | -8.5e+04 |
| time/              |          |
|    fps             | 114      |
|    iterations      | 40       |
|    time_elapsed    | 5725     |
|    total_timesteps | 655360   |
---------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -8.22e+04  |
| time/                   |            |
|    fps                  | 114        |
|    iterations           | 41         |
|    time_elapsed         | 5863       |
|    total_timesteps      | 671744     |
| train/                  |            |
|    approx_kl            | 0.06667893 |
|    clip_fraction        | 0.469      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.2       |
|    explained_variance   | 0.915      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.18      |
|    n_updates            | 400        |
|    policy_gradient_loss | -0.0759    |
|    value_loss           | 0.000842   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -8.02e+04   |
| time/                   |             |
|    fps                  | 114         |
|    iterations           | 42          |
|    time_elapsed         | 6002        |
|    total_timesteps      | 688128      |
| train/                  |             |
|    approx_kl            | 0.056978628 |
|    clip_fraction        | 0.442       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.96       |
|    explained_variance   | 0.936       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.112      |
|    n_updates            | 410         |
|    policy_gradient_loss | -0.0665     |
|    value_loss           | 0.000694    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -7.85e+04  |
| time/                   |            |
|    fps                  | 114        |
|    iterations           | 43         |
|    time_elapsed         | 6140       |
|    total_timesteps      | 704512     |
| train/                  |            |
|    approx_kl            | 0.06468602 |
|    clip_fraction        | 0.462      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.05      |
|    explained_variance   | 0.929      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.148     |
|    n_updates            | 420        |
|    policy_gradient_loss | -0.075     |
|    value_loss           | 0.000677   |
----------------------------------------

Eval num_timesteps=720000, episode_reward=-100680.31 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -1.01e+05  |
| time/                   |            |
|    total_timesteps      | 720000     |
| train/                  |            |
|    approx_kl            | 0.06379026 |
|    clip_fraction        | 0.452      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.96      |
|    explained_variance   | 0.951      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.151     |
|    n_updates            | 430        |
|    policy_gradient_loss | -0.074     |
|    value_loss           | 0.000683   |
----------------------------------------

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 1.44e+03 |
|    ep_rew_mean     | -7.8e+04 |
| time/              |          |
|    fps             | 114      |
|    iterations      | 44       |
|    time_elapsed    | 6287     |
|    total_timesteps | 720896   |
---------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -7.6e+04   |
| time/                   |            |
|    fps                  | 114        |
|    iterations           | 45         |
|    time_elapsed         | 6424       |
|    total_timesteps      | 737280     |
| train/                  |            |
|    approx_kl            | 0.06374611 |
|    clip_fraction        | 0.454      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.84      |
|    explained_variance   | 0.958      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.162     |
|    n_updates            | 440        |
|    policy_gradient_loss | -0.0723    |
|    value_loss           | 0.000523   |
----------------------------------------

--------------------------------------
| rollout/                |          |
|    ep_len_mean          | 1.44e+03 |
|    ep_rew_mean          | -7.4e+04 |
| time/                   |          |
|    fps                  | 114      |
|    iterations           | 46       |
|    time_elapsed         | 6562     |
|    total_timesteps      | 753664   |
| train/                  |          |
|    approx_kl            | 0.069104 |
|    clip_fraction        | 0.474    |
|    clip_range           | 0.2      |
|    entropy_loss         | -5.97    |
|    explained_variance   | 0.953    |
|    learning_rate        | 0.0003   |
|    loss                 | -0.168   |
|    n_updates            | 450      |
|    policy_gradient_loss | -0.0758  |
|    value_loss           | 0.000764 |
--------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -7.18e+04  |
| time/                   |            |
|    fps                  | 114        |
|    iterations           | 47         |
|    time_elapsed         | 6700       |
|    total_timesteps      | 770048     |
| train/                  |            |
|    approx_kl            | 0.06013306 |
|    clip_fraction        | 0.441      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.63      |
|    explained_variance   | 0.941      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.125     |
|    n_updates            | 460        |
|    policy_gradient_loss | -0.0658    |
|    value_loss           | 0.000624   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -6.83e+04  |
| time/                   |            |
|    fps                  | 114        |
|    iterations           | 48         |
|    time_elapsed         | 6839       |
|    total_timesteps      | 786432     |
| train/                  |            |
|    approx_kl            | 0.05960593 |
|    clip_fraction        | 0.441      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.56      |
|    explained_variance   | 0.954      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.159     |
|    n_updates            | 470        |
|    policy_gradient_loss | -0.07      |
|    value_loss           | 0.000495   |
----------------------------------------

Eval num_timesteps=800000, episode_reward=-119598.52 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -1.2e+05    |
| time/                   |             |
|    total_timesteps      | 800000      |
| train/                  |             |
|    approx_kl            | 0.061841775 |
|    clip_fraction        | 0.457       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.58       |
|    explained_variance   | 0.91        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.134      |
|    n_updates            | 480         |
|    policy_gradient_loss | -0.0692     |
|    value_loss           | 0.000626    |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -6.77e+04 |
| time/              |           |
|    fps             | 114       |
|    iterations      | 49        |
|    time_elapsed    | 6985      |
|    total_timesteps | 802816    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -6.43e+04  |
| time/                   |            |
|    fps                  | 114        |
|    iterations           | 50         |
|    time_elapsed         | 7123       |
|    total_timesteps      | 819200     |
| train/                  |            |
|    approx_kl            | 0.06564094 |
|    clip_fraction        | 0.459      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.49      |
|    explained_variance   | 0.92       |
|    learning_rate        | 0.0003     |
|    loss                 | -0.15      |
|    n_updates            | 490        |
|    policy_gradient_loss | -0.0711    |
|    value_loss           | 0.000487   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -6.34e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 51         |
|    time_elapsed         | 7261       |
|    total_timesteps      | 835584     |
| train/                  |            |
|    approx_kl            | 0.06418154 |
|    clip_fraction        | 0.46       |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.5       |
|    explained_variance   | 0.937      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.162     |
|    n_updates            | 500        |
|    policy_gradient_loss | -0.0724    |
|    value_loss           | 0.000515   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -6.2e+04   |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 52         |
|    time_elapsed         | 7400       |
|    total_timesteps      | 851968     |
| train/                  |            |
|    approx_kl            | 0.06437769 |
|    clip_fraction        | 0.456      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.48      |
|    explained_variance   | 0.943      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.148     |
|    n_updates            | 510        |
|    policy_gradient_loss | -0.0703    |
|    value_loss           | 0.000601   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -5.95e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 53         |
|    time_elapsed         | 7539       |
|    total_timesteps      | 868352     |
| train/                  |            |
|    approx_kl            | 0.06619655 |
|    clip_fraction        | 0.463      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.47      |
|    explained_variance   | 0.924      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.132     |
|    n_updates            | 520        |
|    policy_gradient_loss | -0.0714    |
|    value_loss           | 0.000604   |
----------------------------------------

Eval num_timesteps=880000, episode_reward=-93162.09 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -9.32e+04   |
| time/                   |             |
|    total_timesteps      | 880000      |
| train/                  |             |
|    approx_kl            | 0.063000545 |
|    clip_fraction        | 0.453       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.32       |
|    explained_variance   | 0.89        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.146      |
|    n_updates            | 530         |
|    policy_gradient_loss | -0.0694     |
|    value_loss           | 0.000489    |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -5.79e+04 |
| time/              |           |
|    fps             | 115       |
|    iterations      | 54        |
|    time_elapsed    | 7685      |
|    total_timesteps | 884736    |
----------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 1.44e+03  |
|    ep_rew_mean          | -5.57e+04 |
| time/                   |           |
|    fps                  | 115       |
|    iterations           | 55        |
|    time_elapsed         | 7823      |
|    total_timesteps      | 901120    |
| train/                  |           |
|    approx_kl            | 0.064609  |
|    clip_fraction        | 0.445     |
|    clip_range           | 0.2       |
|    entropy_loss         | -5.23     |
|    explained_variance   | 0.919     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.15     |
|    n_updates            | 540       |
|    policy_gradient_loss | -0.0688   |
|    value_loss           | 0.000344  |
---------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -5.5e+04    |
| time/                   |             |
|    fps                  | 115         |
|    iterations           | 56          |
|    time_elapsed         | 7961        |
|    total_timesteps      | 917504      |
| train/                  |             |
|    approx_kl            | 0.060703278 |
|    clip_fraction        | 0.441       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.22       |
|    explained_variance   | 0.949       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.146      |
|    n_updates            | 550         |
|    policy_gradient_loss | -0.0674     |
|    value_loss           | 0.000347    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -5.38e+04   |
| time/                   |             |
|    fps                  | 115         |
|    iterations           | 57          |
|    time_elapsed         | 8100        |
|    total_timesteps      | 933888      |
| train/                  |             |
|    approx_kl            | 0.065018326 |
|    clip_fraction        | 0.457       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.25       |
|    explained_variance   | 0.938       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.137      |
|    n_updates            | 560         |
|    policy_gradient_loss | -0.0643     |
|    value_loss           | 0.000473    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -5.32e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 58         |
|    time_elapsed         | 8238       |
|    total_timesteps      | 950272     |
| train/                  |            |
|    approx_kl            | 0.07010321 |
|    clip_fraction        | 0.461      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.14      |
|    explained_variance   | 0.933      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.143     |
|    n_updates            | 570        |
|    policy_gradient_loss | -0.0713    |
|    value_loss           | 0.000426   |
----------------------------------------

Eval num_timesteps=960000, episode_reward=-68594.77 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -6.86e+04  |
| time/                   |            |
|    total_timesteps      | 960000     |
| train/                  |            |
|    approx_kl            | 0.06321891 |
|    clip_fraction        | 0.447      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.09      |
|    explained_variance   | 0.923      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.136     |
|    n_updates            | 580        |
|    policy_gradient_loss | -0.0641    |
|    value_loss           | 0.000454   |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -5.24e+04 |
| time/              |           |
|    fps             | 115       |
|    iterations      | 59        |
|    time_elapsed    | 8384      |
|    total_timesteps | 966656    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -5.03e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 60         |
|    time_elapsed         | 8523       |
|    total_timesteps      | 983040     |
| train/                  |            |
|    approx_kl            | 0.06035756 |
|    clip_fraction        | 0.439      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.92      |
|    explained_variance   | 0.912      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.109     |
|    n_updates            | 590        |
|    policy_gradient_loss | -0.0687    |
|    value_loss           | 0.000272   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -4.89e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 61         |
|    time_elapsed         | 8661       |
|    total_timesteps      | 999424     |
| train/                  |            |
|    approx_kl            | 0.06569643 |
|    clip_fraction        | 0.448      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.01      |
|    explained_variance   | 0.953      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.168     |
|    n_updates            | 600        |
|    policy_gradient_loss | -0.0665    |
|    value_loss           | 0.000362   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -4.71e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 62         |
|    time_elapsed         | 8800       |
|    total_timesteps      | 1015808    |
| train/                  |            |
|    approx_kl            | 0.06620875 |
|    clip_fraction        | 0.45       |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.85      |
|    explained_variance   | 0.917      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.154     |
|    n_updates            | 610        |
|    policy_gradient_loss | -0.0687    |
|    value_loss           | 0.000343   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -4.61e+04   |
| time/                   |             |
|    fps                  | 115         |
|    iterations           | 63          |
|    time_elapsed         | 8939        |
|    total_timesteps      | 1032192     |
| train/                  |             |
|    approx_kl            | 0.059030037 |
|    clip_fraction        | 0.429       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.78       |
|    explained_variance   | 0.942       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.124      |
|    n_updates            | 620         |
|    policy_gradient_loss | -0.0643     |
|    value_loss           | 0.000251    |
-----------------------------------------

Eval num_timesteps=1040000, episode_reward=-47111.65 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -4.71e+04   |
| time/                   |             |
|    total_timesteps      | 1040000     |
| train/                  |             |
|    approx_kl            | 0.061286993 |
|    clip_fraction        | 0.432       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.7        |
|    explained_variance   | 0.939       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.131      |
|    n_updates            | 630         |
|    policy_gradient_loss | -0.0666     |
|    value_loss           | 0.000236    |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -4.47e+04 |
| time/              |           |
|    fps             | 115       |
|    iterations      | 64        |
|    time_elapsed    | 9084      |
|    total_timesteps | 1048576   |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -4.34e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 65         |
|    time_elapsed         | 9223       |
|    total_timesteps      | 1064960    |
| train/                  |            |
|    approx_kl            | 0.06783797 |
|    clip_fraction        | 0.453      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.81      |
|    explained_variance   | 0.923      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.13      |
|    n_updates            | 640        |
|    policy_gradient_loss | -0.0704    |
|    value_loss           | 0.000371   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -4.26e+04   |
| time/                   |             |
|    fps                  | 115         |
|    iterations           | 66          |
|    time_elapsed         | 9361        |
|    total_timesteps      | 1081344     |
| train/                  |             |
|    approx_kl            | 0.068470255 |
|    clip_fraction        | 0.444       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.74       |
|    explained_variance   | 0.964       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.144      |
|    n_updates            | 650         |
|    policy_gradient_loss | -0.0701     |
|    value_loss           | 0.000259    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -4.1e+04   |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 67         |
|    time_elapsed         | 9499       |
|    total_timesteps      | 1097728    |
| train/                  |            |
|    approx_kl            | 0.06592892 |
|    clip_fraction        | 0.442      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.66      |
|    explained_variance   | 0.954      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.142     |
|    n_updates            | 660        |
|    policy_gradient_loss | -0.0676    |
|    value_loss           | 0.00031    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -4.02e+04   |
| time/                   |             |
|    fps                  | 115         |
|    iterations           | 68          |
|    time_elapsed         | 9638        |
|    total_timesteps      | 1114112     |
| train/                  |             |
|    approx_kl            | 0.064762816 |
|    clip_fraction        | 0.453       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.55       |
|    explained_variance   | 0.884       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.15       |
|    n_updates            | 670         |
|    policy_gradient_loss | -0.0723     |
|    value_loss           | 0.000211    |
-----------------------------------------

Eval num_timesteps=1120000, episode_reward=-80047.09 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -8e+04      |
| time/                   |             |
|    total_timesteps      | 1120000     |
| train/                  |             |
|    approx_kl            | 0.064845294 |
|    clip_fraction        | 0.438       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.53       |
|    explained_variance   | 0.94        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.127      |
|    n_updates            | 680         |
|    policy_gradient_loss | -0.0653     |
|    value_loss           | 0.000277    |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -3.83e+04 |
| time/              |           |
|    fps             | 115       |
|    iterations      | 69        |
|    time_elapsed    | 9784      |
|    total_timesteps | 1130496   |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -3.86e+04   |
| time/                   |             |
|    fps                  | 115         |
|    iterations           | 70          |
|    time_elapsed         | 9923        |
|    total_timesteps      | 1146880     |
| train/                  |             |
|    approx_kl            | 0.065167546 |
|    clip_fraction        | 0.447       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.49       |
|    explained_variance   | 0.945       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.146      |
|    n_updates            | 690         |
|    policy_gradient_loss | -0.07       |
|    value_loss           | 0.000207    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -3.78e+04   |
| time/                   |             |
|    fps                  | 115         |
|    iterations           | 71          |
|    time_elapsed         | 10061       |
|    total_timesteps      | 1163264     |
| train/                  |             |
|    approx_kl            | 0.068341225 |
|    clip_fraction        | 0.449       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.49       |
|    explained_variance   | 0.956       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.138      |
|    n_updates            | 700         |
|    policy_gradient_loss | -0.0682     |
|    value_loss           | 0.00025     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -3.74e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 72         |
|    time_elapsed         | 10200      |
|    total_timesteps      | 1179648    |
| train/                  |            |
|    approx_kl            | 0.06533955 |
|    clip_fraction        | 0.442      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.27      |
|    explained_variance   | 0.904      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.135     |
|    n_updates            | 710        |
|    policy_gradient_loss | -0.069     |
|    value_loss           | 0.000183   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -3.66e+04   |
| time/                   |             |
|    fps                  | 115         |
|    iterations           | 73          |
|    time_elapsed         | 10338       |
|    total_timesteps      | 1196032     |
| train/                  |             |
|    approx_kl            | 0.069328874 |
|    clip_fraction        | 0.444       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.44       |
|    explained_variance   | 0.955       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.154      |
|    n_updates            | 720         |
|    policy_gradient_loss | -0.0708     |
|    value_loss           | 0.000252    |
-----------------------------------------

Eval num_timesteps=1200000, episode_reward=-74236.01 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -7.42e+04  |
| time/                   |            |
|    total_timesteps      | 1200000    |
| train/                  |            |
|    approx_kl            | 0.06587359 |
|    clip_fraction        | 0.441      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.28      |
|    explained_variance   | 0.952      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.128     |
|    n_updates            | 730        |
|    policy_gradient_loss | -0.0677    |
|    value_loss           | 0.000204   |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -3.51e+04 |
| time/              |           |
|    fps             | 115       |
|    iterations      | 74        |
|    time_elapsed    | 10484     |
|    total_timesteps | 1212416   |
----------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 1.44e+03  |
|    ep_rew_mean          | -3.49e+04 |
| time/                   |           |
|    fps                  | 115       |
|    iterations           | 75        |
|    time_elapsed         | 10622     |
|    total_timesteps      | 1228800   |
| train/                  |           |
|    approx_kl            | 0.0667262 |
|    clip_fraction        | 0.435     |
|    clip_range           | 0.2       |
|    entropy_loss         | -4.29     |
|    explained_variance   | 0.923     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.128    |
|    n_updates            | 740       |
|    policy_gradient_loss | -0.0688   |
|    value_loss           | 0.000232  |
---------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -3.42e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 76         |
|    time_elapsed         | 10760      |
|    total_timesteps      | 1245184    |
| train/                  |            |
|    approx_kl            | 0.06993161 |
|    clip_fraction        | 0.444      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.3       |
|    explained_variance   | 0.96       |
|    learning_rate        | 0.0003     |
|    loss                 | -0.118     |
|    n_updates            | 750        |
|    policy_gradient_loss | -0.0708    |
|    value_loss           | 0.000215   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -3.39e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 77         |
|    time_elapsed         | 10899      |
|    total_timesteps      | 1261568    |
| train/                  |            |
|    approx_kl            | 0.06676137 |
|    clip_fraction        | 0.442      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.2       |
|    explained_variance   | 0.938      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.13      |
|    n_updates            | 760        |
|    policy_gradient_loss | -0.0681    |
|    value_loss           | 0.000241   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -3.32e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 78         |
|    time_elapsed         | 11038      |
|    total_timesteps      | 1277952    |
| train/                  |            |
|    approx_kl            | 0.06228541 |
|    clip_fraction        | 0.425      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.99      |
|    explained_variance   | 0.92       |
|    learning_rate        | 0.0003     |
|    loss                 | -0.139     |
|    n_updates            | 770        |
|    policy_gradient_loss | -0.0654    |
|    value_loss           | 0.000166   |
----------------------------------------

Eval num_timesteps=1280000, episode_reward=-57679.39 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -5.77e+04  |
| time/                   |            |
|    total_timesteps      | 1280000    |
| train/                  |            |
|    approx_kl            | 0.06640309 |
|    clip_fraction        | 0.445      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.07      |
|    explained_variance   | 0.913      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.139     |
|    n_updates            | 780        |
|    policy_gradient_loss | -0.0689    |
|    value_loss           | 0.000217   |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -3.13e+04 |
| time/              |           |
|    fps             | 115       |
|    iterations      | 79        |
|    time_elapsed    | 11184     |
|    total_timesteps | 1294336   |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -3.11e+04   |
| time/                   |             |
|    fps                  | 115         |
|    iterations           | 80          |
|    time_elapsed         | 11323       |
|    total_timesteps      | 1310720     |
| train/                  |             |
|    approx_kl            | 0.066331014 |
|    clip_fraction        | 0.443       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.95       |
|    explained_variance   | 0.887       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.127      |
|    n_updates            | 790         |
|    policy_gradient_loss | -0.0693     |
|    value_loss           | 0.000162    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -3.07e+04   |
| time/                   |             |
|    fps                  | 115         |
|    iterations           | 81          |
|    time_elapsed         | 11461       |
|    total_timesteps      | 1327104     |
| train/                  |             |
|    approx_kl            | 0.067923956 |
|    clip_fraction        | 0.451       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.03       |
|    explained_variance   | 0.93        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.143      |
|    n_updates            | 800         |
|    policy_gradient_loss | -0.0669     |
|    value_loss           | 0.000192    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -2.99e+04   |
| time/                   |             |
|    fps                  | 115         |
|    iterations           | 82          |
|    time_elapsed         | 11599       |
|    total_timesteps      | 1343488     |
| train/                  |             |
|    approx_kl            | 0.071494795 |
|    clip_fraction        | 0.448       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.04       |
|    explained_variance   | 0.937       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.143      |
|    n_updates            | 810         |
|    policy_gradient_loss | -0.069      |
|    value_loss           | 0.000202    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.9e+04   |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 83         |
|    time_elapsed         | 11738      |
|    total_timesteps      | 1359872    |
| train/                  |            |
|    approx_kl            | 0.06743101 |
|    clip_fraction        | 0.434      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.89      |
|    explained_variance   | 0.952      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.143     |
|    n_updates            | 820        |
|    policy_gradient_loss | -0.0663    |
|    value_loss           | 0.000144   |
----------------------------------------

Eval num_timesteps=1360000, episode_reward=-49923.13 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -4.99e+04   |
| time/                   |             |
|    total_timesteps      | 1360000     |
| train/                  |             |
|    approx_kl            | 0.068782374 |
|    clip_fraction        | 0.452       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.92       |
|    explained_variance   | 0.923       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.129      |
|    n_updates            | 830         |
|    policy_gradient_loss | -0.0671     |
|    value_loss           | 0.000146    |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -2.81e+04 |
| time/              |           |
|    fps             | 115       |
|    iterations      | 84        |
|    time_elapsed    | 11884     |
|    total_timesteps | 1376256   |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.77e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 85         |
|    time_elapsed         | 12022      |
|    total_timesteps      | 1392640    |
| train/                  |            |
|    approx_kl            | 0.07163137 |
|    clip_fraction        | 0.44       |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.83      |
|    explained_variance   | 0.939      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.136     |
|    n_updates            | 840        |
|    policy_gradient_loss | -0.0682    |
|    value_loss           | 0.000179   |
----------------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 1.44e+03  |
|    ep_rew_mean          | -2.76e+04 |
| time/                   |           |
|    fps                  | 115       |
|    iterations           | 86        |
|    time_elapsed         | 12161     |
|    total_timesteps      | 1409024   |
| train/                  |           |
|    approx_kl            | 0.0671845 |
|    clip_fraction        | 0.439     |
|    clip_range           | 0.2       |
|    entropy_loss         | -3.77     |
|    explained_variance   | 0.927     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.133    |
|    n_updates            | 850       |
|    policy_gradient_loss | -0.0668   |
|    value_loss           | 0.000163  |
---------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.75e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 87         |
|    time_elapsed         | 12300      |
|    total_timesteps      | 1425408    |
| train/                  |            |
|    approx_kl            | 0.07305716 |
|    clip_fraction        | 0.451      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.78      |
|    explained_variance   | 0.956      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.139     |
|    n_updates            | 860        |
|    policy_gradient_loss | -0.0714    |
|    value_loss           | 0.000164   |
----------------------------------------

Eval num_timesteps=1440000, episode_reward=-60413.46 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -6.04e+04   |
| time/                   |             |
|    total_timesteps      | 1440000     |
| train/                  |             |
|    approx_kl            | 0.071211815 |
|    clip_fraction        | 0.43        |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.69       |
|    explained_variance   | 0.953       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.141      |
|    n_updates            | 870         |
|    policy_gradient_loss | -0.0662     |
|    value_loss           | 0.000192    |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -2.82e+04 |
| time/              |           |
|    fps             | 115       |
|    iterations      | 88        |
|    time_elapsed    | 12446     |
|    total_timesteps | 1441792   |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.77e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 89         |
|    time_elapsed         | 12585      |
|    total_timesteps      | 1458176    |
| train/                  |            |
|    approx_kl            | 0.07664283 |
|    clip_fraction        | 0.45       |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.89      |
|    explained_variance   | 0.959      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.124     |
|    n_updates            | 880        |
|    policy_gradient_loss | -0.0707    |
|    value_loss           | 0.000229   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.7e+04   |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 90         |
|    time_elapsed         | 12723      |
|    total_timesteps      | 1474560    |
| train/                  |            |
|    approx_kl            | 0.06840441 |
|    clip_fraction        | 0.435      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.58      |
|    explained_variance   | 0.964      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.139     |
|    n_updates            | 890        |
|    policy_gradient_loss | -0.0688    |
|    value_loss           | 0.000146   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -2.67e+04   |
| time/                   |             |
|    fps                  | 115         |
|    iterations           | 91          |
|    time_elapsed         | 12862       |
|    total_timesteps      | 1490944     |
| train/                  |             |
|    approx_kl            | 0.072239414 |
|    clip_fraction        | 0.448       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.67       |
|    explained_variance   | 0.952       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.143      |
|    n_updates            | 900         |
|    policy_gradient_loss | -0.0715     |
|    value_loss           | 0.00017     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.64e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 92         |
|    time_elapsed         | 13001      |
|    total_timesteps      | 1507328    |
| train/                  |            |
|    approx_kl            | 0.07054658 |
|    clip_fraction        | 0.439      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.59      |
|    explained_variance   | 0.939      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.149     |
|    n_updates            | 910        |
|    policy_gradient_loss | -0.0676    |
|    value_loss           | 0.000175   |
----------------------------------------

Eval num_timesteps=1520000, episode_reward=-40395.38 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -4.04e+04  |
| time/                   |            |
|    total_timesteps      | 1520000    |
| train/                  |            |
|    approx_kl            | 0.07527876 |
|    clip_fraction        | 0.456      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.55      |
|    explained_variance   | 0.925      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.146     |
|    n_updates            | 920        |
|    policy_gradient_loss | -0.0716    |
|    value_loss           | 0.00016    |
----------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 1.44e+03 |
|    ep_rew_mean     | -2.6e+04 |
| time/              |          |
|    fps             | 115      |
|    iterations      | 93       |
|    time_elapsed    | 13147    |
|    total_timesteps | 1523712  |
---------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.54e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 94         |
|    time_elapsed         | 13286      |
|    total_timesteps      | 1540096    |
| train/                  |            |
|    approx_kl            | 0.06806599 |
|    clip_fraction        | 0.428      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.44      |
|    explained_variance   | 0.936      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.1       |
|    n_updates            | 930        |
|    policy_gradient_loss | -0.0676    |
|    value_loss           | 0.000143   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.42e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 95         |
|    time_elapsed         | 13425      |
|    total_timesteps      | 1556480    |
| train/                  |            |
|    approx_kl            | 0.06859917 |
|    clip_fraction        | 0.428      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.31      |
|    explained_variance   | 0.972      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.101     |
|    n_updates            | 940        |
|    policy_gradient_loss | -0.0654    |
|    value_loss           | 0.000107   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.37e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 96         |
|    time_elapsed         | 13564      |
|    total_timesteps      | 1572864    |
| train/                  |            |
|    approx_kl            | 0.06862507 |
|    clip_fraction        | 0.433      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.34      |
|    explained_variance   | 0.931      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.135     |
|    n_updates            | 950        |
|    policy_gradient_loss | -0.0669    |
|    value_loss           | 0.00014    |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.31e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 97         |
|    time_elapsed         | 13702      |
|    total_timesteps      | 1589248    |
| train/                  |            |
|    approx_kl            | 0.07424472 |
|    clip_fraction        | 0.448      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.38      |
|    explained_variance   | 0.947      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.133     |
|    n_updates            | 960        |
|    policy_gradient_loss | -0.0715    |
|    value_loss           | 0.000136   |
----------------------------------------

Eval num_timesteps=1600000, episode_reward=-27974.32 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -2.8e+04   |
| time/                   |            |
|    total_timesteps      | 1600000    |
| train/                  |            |
|    approx_kl            | 0.06877969 |
|    clip_fraction        | 0.43       |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.24      |
|    explained_variance   | 0.947      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.117     |
|    n_updates            | 970        |
|    policy_gradient_loss | -0.0678    |
|    value_loss           | 9.66e-05   |
----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -2.18e+04 |
| time/              |           |
|    fps             | 115       |
|    iterations      | 98        |
|    time_elapsed    | 13849     |
|    total_timesteps | 1605632   |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -2.1e+04    |
| time/                   |             |
|    fps                  | 115         |
|    iterations           | 99          |
|    time_elapsed         | 13987       |
|    total_timesteps      | 1622016     |
| train/                  |             |
|    approx_kl            | 0.071015075 |
|    clip_fraction        | 0.439       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.29       |
|    explained_variance   | 0.952       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.115      |
|    n_updates            | 980         |
|    policy_gradient_loss | -0.0701     |
|    value_loss           | 9.92e-05    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -2e+04      |
| time/                   |             |
|    fps                  | 115         |
|    iterations           | 100         |
|    time_elapsed         | 14126       |
|    total_timesteps      | 1638400     |
| train/                  |             |
|    approx_kl            | 0.064661436 |
|    clip_fraction        | 0.427       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.22       |
|    explained_variance   | 0.961       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.115      |
|    n_updates            | 990         |
|    policy_gradient_loss | -0.06       |
|    value_loss           | 9.22e-05    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.01e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 101        |
|    time_elapsed         | 14265      |
|    total_timesteps      | 1654784    |
| train/                  |            |
|    approx_kl            | 0.06568078 |
|    clip_fraction        | 0.428      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.14      |
|    explained_variance   | 0.954      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.113     |
|    n_updates            | 1000       |
|    policy_gradient_loss | -0.0629    |
|    value_loss           | 9.23e-05   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.93e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 102        |
|    time_elapsed         | 14403      |
|    total_timesteps      | 1671168    |
| train/                  |            |
|    approx_kl            | 0.08059262 |
|    clip_fraction        | 0.444      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.24      |
|    explained_variance   | 0.962      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.134     |
|    n_updates            | 1010       |
|    policy_gradient_loss | -0.0687    |
|    value_loss           | 0.000118   |
----------------------------------------

Eval num_timesteps=1680000, episode_reward=-24221.72 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -2.42e+04   |
| time/                   |             |
|    total_timesteps      | 1680000     |
| train/                  |             |
|    approx_kl            | 0.067748606 |
|    clip_fraction        | 0.43        |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.15       |
|    explained_variance   | 0.944       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.148      |
|    n_updates            | 1020        |
|    policy_gradient_loss | -0.064      |
|    value_loss           | 0.000107    |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -1.91e+04 |
| time/              |           |
|    fps             | 115       |
|    iterations      | 103       |
|    time_elapsed    | 14549     |
|    total_timesteps | 1687552   |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.9e+04   |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 104        |
|    time_elapsed         | 14688      |
|    total_timesteps      | 1703936    |
| train/                  |            |
|    approx_kl            | 0.07080723 |
|    clip_fraction        | 0.432      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.04      |
|    explained_variance   | 0.932      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0966    |
|    n_updates            | 1030       |
|    policy_gradient_loss | -0.0677    |
|    value_loss           | 0.000104   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.86e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 105         |
|    time_elapsed         | 14826       |
|    total_timesteps      | 1720320     |
| train/                  |             |
|    approx_kl            | 0.072050765 |
|    clip_fraction        | 0.433       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.97       |
|    explained_variance   | 0.972       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.113      |
|    n_updates            | 1040        |
|    policy_gradient_loss | -0.0673     |
|    value_loss           | 7.57e-05    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.81e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 106        |
|    time_elapsed         | 14965      |
|    total_timesteps      | 1736704    |
| train/                  |            |
|    approx_kl            | 0.07058026 |
|    clip_fraction        | 0.435      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.08      |
|    explained_variance   | 0.969      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.111     |
|    n_updates            | 1050       |
|    policy_gradient_loss | -0.0665    |
|    value_loss           | 0.0001     |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.75e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 107         |
|    time_elapsed         | 15103       |
|    total_timesteps      | 1753088     |
| train/                  |             |
|    approx_kl            | 0.069332644 |
|    clip_fraction        | 0.421       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.87       |
|    explained_variance   | 0.953       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.104      |
|    n_updates            | 1060        |
|    policy_gradient_loss | -0.064      |
|    value_loss           | 8.46e-05    |
-----------------------------------------

Eval num_timesteps=1760000, episode_reward=-18437.74 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -1.84e+04   |
| time/                   |             |
|    total_timesteps      | 1760000     |
| train/                  |             |
|    approx_kl            | 0.067604214 |
|    clip_fraction        | 0.417       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.8        |
|    explained_variance   | 0.951       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.12       |
|    n_updates            | 1070        |
|    policy_gradient_loss | -0.0647     |
|    value_loss           | 7.22e-05    |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -1.74e+04 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 108       |
|    time_elapsed    | 15250     |
|    total_timesteps | 1769472   |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.67e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 109        |
|    time_elapsed         | 15388      |
|    total_timesteps      | 1785856    |
| train/                  |            |
|    approx_kl            | 0.07236511 |
|    clip_fraction        | 0.426      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.85      |
|    explained_variance   | 0.953      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.121     |
|    n_updates            | 1080       |
|    policy_gradient_loss | -0.0681    |
|    value_loss           | 8.03e-05   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.64e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 110        |
|    time_elapsed         | 15528      |
|    total_timesteps      | 1802240    |
| train/                  |            |
|    approx_kl            | 0.07626037 |
|    clip_fraction        | 0.433      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.9       |
|    explained_variance   | 0.967      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.111     |
|    n_updates            | 1090       |
|    policy_gradient_loss | -0.0676    |
|    value_loss           | 9.09e-05   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.61e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 111        |
|    time_elapsed         | 15666      |
|    total_timesteps      | 1818624    |
| train/                  |            |
|    approx_kl            | 0.06666656 |
|    clip_fraction        | 0.413      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.69      |
|    explained_variance   | 0.963      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.121     |
|    n_updates            | 1100       |
|    policy_gradient_loss | -0.0644    |
|    value_loss           | 6.56e-05   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.57e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 112        |
|    time_elapsed         | 15805      |
|    total_timesteps      | 1835008    |
| train/                  |            |
|    approx_kl            | 0.06840282 |
|    clip_fraction        | 0.417      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.68      |
|    explained_variance   | 0.958      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.132     |
|    n_updates            | 1110       |
|    policy_gradient_loss | -0.0645    |
|    value_loss           | 6.31e-05   |
----------------------------------------

Eval num_timesteps=1840000, episode_reward=-15824.50 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -1.58e+04   |
| time/                   |             |
|    total_timesteps      | 1840000     |
| train/                  |             |
|    approx_kl            | 0.072552316 |
|    clip_fraction        | 0.42        |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.69       |
|    explained_variance   | 0.964       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.121      |
|    n_updates            | 1120        |
|    policy_gradient_loss | -0.068      |
|    value_loss           | 7.18e-05    |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -1.53e+04 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 113       |
|    time_elapsed    | 15951     |
|    total_timesteps | 1851392   |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.45e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 114        |
|    time_elapsed         | 16090      |
|    total_timesteps      | 1867776    |
| train/                  |            |
|    approx_kl            | 0.07176614 |
|    clip_fraction        | 0.428      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.62      |
|    explained_variance   | 0.943      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.122     |
|    n_updates            | 1130       |
|    policy_gradient_loss | -0.067     |
|    value_loss           | 5.15e-05   |
----------------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 1.44e+03  |
|    ep_rew_mean          | -1.45e+04 |
| time/                   |           |
|    fps                  | 116       |
|    iterations           | 115       |
|    time_elapsed         | 16229     |
|    total_timesteps      | 1884160   |
| train/                  |           |
|    approx_kl            | 0.0698858 |
|    clip_fraction        | 0.416     |
|    clip_range           | 0.2       |
|    entropy_loss         | -2.56     |
|    explained_variance   | 0.955     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.134    |
|    n_updates            | 1140      |
|    policy_gradient_loss | -0.066    |
|    value_loss           | 5.61e-05  |
---------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.43e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 116        |
|    time_elapsed         | 16367      |
|    total_timesteps      | 1900544    |
| train/                  |            |
|    approx_kl            | 0.06759288 |
|    clip_fraction        | 0.412      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.49      |
|    explained_variance   | 0.948      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.12      |
|    n_updates            | 1150       |
|    policy_gradient_loss | -0.0652    |
|    value_loss           | 4.57e-05   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.4e+04   |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 117        |
|    time_elapsed         | 16506      |
|    total_timesteps      | 1916928    |
| train/                  |            |
|    approx_kl            | 0.08033061 |
|    clip_fraction        | 0.44       |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.58      |
|    explained_variance   | 0.943      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.118     |
|    n_updates            | 1160       |
|    policy_gradient_loss | -0.0689    |
|    value_loss           | 6.39e-05   |
----------------------------------------

Eval num_timesteps=1920000, episode_reward=-13989.63 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -1.4e+04    |
| time/                   |             |
|    total_timesteps      | 1920000     |
| train/                  |             |
|    approx_kl            | 0.071405366 |
|    clip_fraction        | 0.406       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.32       |
|    explained_variance   | 0.962       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.137      |
|    n_updates            | 1170        |
|    policy_gradient_loss | -0.0658     |
|    value_loss           | 4.27e-05    |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -1.35e+04 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 118       |
|    time_elapsed    | 16652     |
|    total_timesteps | 1933312   |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.31e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 119         |
|    time_elapsed         | 16791       |
|    total_timesteps      | 1949696     |
| train/                  |             |
|    approx_kl            | 0.075020425 |
|    clip_fraction        | 0.426       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.36       |
|    explained_variance   | 0.965       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.102      |
|    n_updates            | 1180        |
|    policy_gradient_loss | -0.0702     |
|    value_loss           | 4.72e-05    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.31e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 120         |
|    time_elapsed         | 16929       |
|    total_timesteps      | 1966080     |
| train/                  |             |
|    approx_kl            | 0.078597724 |
|    clip_fraction        | 0.419       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.32       |
|    explained_variance   | 0.955       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.118      |
|    n_updates            | 1190        |
|    policy_gradient_loss | -0.0687     |
|    value_loss           | 6.08e-05    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.26e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 121        |
|    time_elapsed         | 17068      |
|    total_timesteps      | 1982464    |
| train/                  |            |
|    approx_kl            | 0.07742781 |
|    clip_fraction        | 0.422      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.4       |
|    explained_variance   | 0.956      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.111     |
|    n_updates            | 1200       |
|    policy_gradient_loss | -0.0683    |
|    value_loss           | 6e-05      |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.24e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 122        |
|    time_elapsed         | 17206      |
|    total_timesteps      | 1998848    |
| train/                  |            |
|    approx_kl            | 0.07287638 |
|    clip_fraction        | 0.408      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.26      |
|    explained_variance   | 0.955      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.126     |
|    n_updates            | 1210       |
|    policy_gradient_loss | -0.0629    |
|    value_loss           | 5.23e-05   |
----------------------------------------

Eval num_timesteps=2000000, episode_reward=-18828.25 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -1.88e+04   |
| time/                   |             |
|    total_timesteps      | 2000000     |
| train/                  |             |
|    approx_kl            | 0.076609254 |
|    clip_fraction        | 0.412       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.18       |
|    explained_variance   | 0.97        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.116      |
|    n_updates            | 1220        |
|    policy_gradient_loss | -0.0673     |
|    value_loss           | 3.97e-05    |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -1.22e+04 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 123       |
|    time_elapsed    | 17353     |
|    total_timesteps | 2015232   |
----------------------------------

Training completed in 4:49:25.085301
Model saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\rl_models\ppo_overload.zip
VecNormalize saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\rl_models\ppo_overload_vecnormalize.pkl

[2/2] Training COST scenario...

============================================================
Training PPO for scenario: COST
============================================================
Latest model: models\random_forest_cpu_total_usage_20251111_221930.pkl
✓ Model loaded: models\random_forest_cpu_total_usage_20251111_221930.pkl
  Model: random_forest
  Target: cpu_total_usage
  Saved at: 2025-11-11 22:19:30
Latest model: models\svr_memory_usage_pct_20251111_184735.pkl
✓ Model loaded: models\svr_memory_usage_pct_20251111_184735.pkl
  Model: svr
  Target: memory_usage_pct
  Saved at: 2025-11-11 18:47:35
Latest model: models\random_forest_system_load_20251111_221944.pkl
✓ Model loaded: models\random_forest_system_load_20251111_221944.pkl
  Model: random_forest
  Target: system_load
  Saved at: 2025-11-11 22:19:44
Creating new PPO model
Using cpu device

Starting training for 2,000,000 timesteps...
Logging to ./tensorboard_logs/PPO_15

Output()

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -4.67e+05 |
| time/              |           |
|    fps             | 129       |
|    iterations      | 1         |
|    time_elapsed    | 126       |
|    total_timesteps | 16384     |
----------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 1.44e+03  |
|    ep_rew_mean          | -4.67e+05 |
| time/                   |           |
|    fps                  | 123       |
|    iterations           | 2         |
|    time_elapsed         | 264       |
|    total_timesteps      | 32768     |
| train/                  |           |
|    approx_kl            | 0.0309111 |
|    clip_fraction        | 0.28      |
|    clip_range           | 0.2       |
|    entropy_loss         | -9.58     |
|    explained_variance   | -0.94     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.169    |
|    n_updates            | 10        |
|    policy_gradient_loss | -0.0529   |
|    value_loss           | 0.17      |
---------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -4.63e+05  |
| time/                   |            |
|    fps                  | 122        |
|    iterations           | 3          |
|    time_elapsed         | 401        |
|    total_timesteps      | 49152      |
| train/                  |            |
|    approx_kl            | 0.03147088 |
|    clip_fraction        | 0.327      |
|    clip_range           | 0.2        |
|    entropy_loss         | -9.54      |
|    explained_variance   | -0.271     |
|    learning_rate        | 0.0003     |
|    loss                 | -0.167     |
|    n_updates            | 20         |
|    policy_gradient_loss | -0.0676    |
|    value_loss           | 0.0264     |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -4.59e+05   |
| time/                   |             |
|    fps                  | 121         |
|    iterations           | 4           |
|    time_elapsed         | 539         |
|    total_timesteps      | 65536       |
| train/                  |             |
|    approx_kl            | 0.033083744 |
|    clip_fraction        | 0.354       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.5        |
|    explained_variance   | 0.417       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.185      |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.0668     |
|    value_loss           | 0.015       |
-----------------------------------------

Eval num_timesteps=80000, episode_reward=-271104.02 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -2.71e+05   |
| time/                   |             |
|    total_timesteps      | 80000       |
| train/                  |             |
|    approx_kl            | 0.036526162 |
|    clip_fraction        | 0.38        |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.45       |
|    explained_variance   | 0.409       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.195      |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0728     |
|    value_loss           | 0.0108      |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -4.48e+05 |
| time/              |           |
|    fps             | 119       |
|    iterations      | 5         |
|    time_elapsed    | 686       |
|    total_timesteps | 81920     |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -4.42e+05  |
| time/                   |            |
|    fps                  | 119        |
|    iterations           | 6          |
|    time_elapsed         | 825        |
|    total_timesteps      | 98304      |
| train/                  |            |
|    approx_kl            | 0.03784334 |
|    clip_fraction        | 0.407      |
|    clip_range           | 0.2        |
|    entropy_loss         | -9.39      |
|    explained_variance   | 0.528      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.202     |
|    n_updates            | 50         |
|    policy_gradient_loss | -0.0732    |
|    value_loss           | 0.00879    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -4.36e+05   |
| time/                   |             |
|    fps                  | 118         |
|    iterations           | 7           |
|    time_elapsed         | 965         |
|    total_timesteps      | 114688      |
| train/                  |             |
|    approx_kl            | 0.040673465 |
|    clip_fraction        | 0.421       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.32       |
|    explained_variance   | 0.373       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.187      |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.075      |
|    value_loss           | 0.00793     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -4.22e+05   |
| time/                   |             |
|    fps                  | 118         |
|    iterations           | 8           |
|    time_elapsed         | 1104        |
|    total_timesteps      | 131072      |
| train/                  |             |
|    approx_kl            | 0.041862555 |
|    clip_fraction        | 0.425       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.23       |
|    explained_variance   | 0.639       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.194      |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.075      |
|    value_loss           | 0.00627     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -4.15e+05   |
| time/                   |             |
|    fps                  | 118         |
|    iterations           | 9           |
|    time_elapsed         | 1243        |
|    total_timesteps      | 147456      |
| train/                  |             |
|    approx_kl            | 0.043811843 |
|    clip_fraction        | 0.437       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.15       |
|    explained_variance   | 0.723       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.198      |
|    n_updates            | 80          |
|    policy_gradient_loss | -0.0766     |
|    value_loss           | 0.00515     |
-----------------------------------------

Eval num_timesteps=160000, episode_reward=-161282.34 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -1.61e+05  |
| time/                   |            |
|    total_timesteps      | 160000     |
| train/                  |            |
|    approx_kl            | 0.04447648 |
|    clip_fraction        | 0.431      |
|    clip_range           | 0.2        |
|    entropy_loss         | -9.05      |
|    explained_variance   | 0.69       |
|    learning_rate        | 0.0003     |
|    loss                 | -0.189     |
|    n_updates            | 90         |
|    policy_gradient_loss | -0.0762    |
|    value_loss           | 0.00495    |
----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -3.95e+05 |
| time/              |           |
|    fps             | 117       |
|    iterations      | 10        |
|    time_elapsed    | 1391      |
|    total_timesteps | 163840    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -3.81e+05  |
| time/                   |            |
|    fps                  | 117        |
|    iterations           | 11         |
|    time_elapsed         | 1530       |
|    total_timesteps      | 180224     |
| train/                  |            |
|    approx_kl            | 0.04774133 |
|    clip_fraction        | 0.442      |
|    clip_range           | 0.2        |
|    entropy_loss         | -8.98      |
|    explained_variance   | 0.723      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.189     |
|    n_updates            | 100        |
|    policy_gradient_loss | -0.0774    |
|    value_loss           | 0.00491    |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -3.56e+05  |
| time/                   |            |
|    fps                  | 117        |
|    iterations           | 12         |
|    time_elapsed         | 1670       |
|    total_timesteps      | 196608     |
| train/                  |            |
|    approx_kl            | 0.04715481 |
|    clip_fraction        | 0.442      |
|    clip_range           | 0.2        |
|    entropy_loss         | -8.87      |
|    explained_variance   | 0.829      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.177     |
|    n_updates            | 110        |
|    policy_gradient_loss | -0.0773    |
|    value_loss           | 0.00447    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -3.42e+05   |
| time/                   |             |
|    fps                  | 117         |
|    iterations           | 13          |
|    time_elapsed         | 1809        |
|    total_timesteps      | 212992      |
| train/                  |             |
|    approx_kl            | 0.049094994 |
|    clip_fraction        | 0.451       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.76       |
|    explained_variance   | 0.752       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.206      |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.0761     |
|    value_loss           | 0.00453     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -3.3e+05   |
| time/                   |            |
|    fps                  | 117        |
|    iterations           | 14         |
|    time_elapsed         | 1948       |
|    total_timesteps      | 229376     |
| train/                  |            |
|    approx_kl            | 0.04773835 |
|    clip_fraction        | 0.443      |
|    clip_range           | 0.2        |
|    entropy_loss         | -8.64      |
|    explained_variance   | 0.851      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.195     |
|    n_updates            | 130        |
|    policy_gradient_loss | -0.0751    |
|    value_loss           | 0.00474    |
----------------------------------------

Eval num_timesteps=240000, episode_reward=-94105.13 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -9.41e+04   |
| time/                   |             |
|    total_timesteps      | 240000      |
| train/                  |             |
|    approx_kl            | 0.051597096 |
|    clip_fraction        | 0.453       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.53       |
|    explained_variance   | 0.81        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.199      |
|    n_updates            | 140         |
|    policy_gradient_loss | -0.0784     |
|    value_loss           | 0.00425     |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -3.06e+05 |
| time/              |           |
|    fps             | 117       |
|    iterations      | 15        |
|    time_elapsed    | 2096      |
|    total_timesteps | 245760    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -2.95e+05   |
| time/                   |             |
|    fps                  | 117         |
|    iterations           | 16          |
|    time_elapsed         | 2234        |
|    total_timesteps      | 262144      |
| train/                  |             |
|    approx_kl            | 0.051502794 |
|    clip_fraction        | 0.453       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.49       |
|    explained_variance   | 0.833       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.209      |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.0756     |
|    value_loss           | 0.00435     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -2.72e+05   |
| time/                   |             |
|    fps                  | 117         |
|    iterations           | 17          |
|    time_elapsed         | 2374        |
|    total_timesteps      | 278528      |
| train/                  |             |
|    approx_kl            | 0.049036503 |
|    clip_fraction        | 0.445       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.3        |
|    explained_variance   | 0.919       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.189      |
|    n_updates            | 160         |
|    policy_gradient_loss | -0.0719     |
|    value_loss           | 0.00316     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.61e+05  |
| time/                   |            |
|    fps                  | 117        |
|    iterations           | 18         |
|    time_elapsed         | 2513       |
|    total_timesteps      | 294912     |
| train/                  |            |
|    approx_kl            | 0.04959774 |
|    clip_fraction        | 0.444      |
|    clip_range           | 0.2        |
|    entropy_loss         | -8.18      |
|    explained_variance   | 0.908      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.183     |
|    n_updates            | 170        |
|    policy_gradient_loss | -0.0743    |
|    value_loss           | 0.00301    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -2.4e+05    |
| time/                   |             |
|    fps                  | 117         |
|    iterations           | 19          |
|    time_elapsed         | 2653        |
|    total_timesteps      | 311296      |
| train/                  |             |
|    approx_kl            | 0.052309316 |
|    clip_fraction        | 0.452       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.08       |
|    explained_variance   | 0.904       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.166      |
|    n_updates            | 180         |
|    policy_gradient_loss | -0.0756     |
|    value_loss           | 0.00258     |
-----------------------------------------

Eval num_timesteps=320000, episode_reward=-180295.91 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -1.8e+05    |
| time/                   |             |
|    total_timesteps      | 320000      |
| train/                  |             |
|    approx_kl            | 0.050823852 |
|    clip_fraction        | 0.443       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.93       |
|    explained_variance   | 0.932       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.174      |
|    n_updates            | 190         |
|    policy_gradient_loss | -0.072      |
|    value_loss           | 0.00211     |
-----------------------------------------

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 1.44e+03 |
|    ep_rew_mean     | -2.3e+05 |
| time/              |          |
|    fps             | 116      |
|    iterations      | 20       |
|    time_elapsed    | 2802     |
|    total_timesteps | 327680   |
---------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -2.2e+05    |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 21          |
|    time_elapsed         | 2941        |
|    total_timesteps      | 344064      |
| train/                  |             |
|    approx_kl            | 0.053684436 |
|    clip_fraction        | 0.454       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.91       |
|    explained_variance   | 0.911       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.189      |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.0774     |
|    value_loss           | 0.00252     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -2.05e+05   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 22          |
|    time_elapsed         | 3080        |
|    total_timesteps      | 360448      |
| train/                  |             |
|    approx_kl            | 0.049874082 |
|    clip_fraction        | 0.441       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.72       |
|    explained_variance   | 0.925       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.163      |
|    n_updates            | 210         |
|    policy_gradient_loss | -0.0641     |
|    value_loss           | 0.00234     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.97e+05  |
| time/                   |            |
|    fps                  | 117        |
|    iterations           | 23         |
|    time_elapsed         | 3220       |
|    total_timesteps      | 376832     |
| train/                  |            |
|    approx_kl            | 0.05704703 |
|    clip_fraction        | 0.46       |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.74      |
|    explained_variance   | 0.939      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.191     |
|    n_updates            | 220        |
|    policy_gradient_loss | -0.0748    |
|    value_loss           | 0.00213    |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.84e+05  |
| time/                   |            |
|    fps                  | 117        |
|    iterations           | 24         |
|    time_elapsed         | 3359       |
|    total_timesteps      | 393216     |
| train/                  |            |
|    approx_kl            | 0.05481894 |
|    clip_fraction        | 0.451      |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.63      |
|    explained_variance   | 0.925      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.176     |
|    n_updates            | 230        |
|    policy_gradient_loss | -0.0748    |
|    value_loss           | 0.00212    |
----------------------------------------

Eval num_timesteps=400000, episode_reward=-195454.98 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -1.95e+05   |
| time/                   |             |
|    total_timesteps      | 400000      |
| train/                  |             |
|    approx_kl            | 0.057927817 |
|    clip_fraction        | 0.461       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.57       |
|    explained_variance   | 0.924       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.199      |
|    n_updates            | 240         |
|    policy_gradient_loss | -0.0772     |
|    value_loss           | 0.00233     |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -1.77e+05 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 25        |
|    time_elapsed    | 3507      |
|    total_timesteps | 409600    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.73e+05   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 26          |
|    time_elapsed         | 3645        |
|    total_timesteps      | 425984      |
| train/                  |             |
|    approx_kl            | 0.059195705 |
|    clip_fraction        | 0.467       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.44       |
|    explained_variance   | 0.931       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.153      |
|    n_updates            | 250         |
|    policy_gradient_loss | -0.0747     |
|    value_loss           | 0.0018      |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.62e+05  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 27         |
|    time_elapsed         | 3785       |
|    total_timesteps      | 442368     |
| train/                  |            |
|    approx_kl            | 0.05574067 |
|    clip_fraction        | 0.455      |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.33      |
|    explained_variance   | 0.945      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.179     |
|    n_updates            | 260        |
|    policy_gradient_loss | -0.0708    |
|    value_loss           | 0.00155    |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.58e+05  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 28         |
|    time_elapsed         | 3925       |
|    total_timesteps      | 458752     |
| train/                  |            |
|    approx_kl            | 0.05619093 |
|    clip_fraction        | 0.451      |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.19      |
|    explained_variance   | 0.922      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.144     |
|    n_updates            | 270        |
|    policy_gradient_loss | -0.0687    |
|    value_loss           | 0.00169    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.5e+05    |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 29          |
|    time_elapsed         | 4065        |
|    total_timesteps      | 475136      |
| train/                  |             |
|    approx_kl            | 0.055129483 |
|    clip_fraction        | 0.449       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.13       |
|    explained_variance   | 0.936       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.18       |
|    n_updates            | 280         |
|    policy_gradient_loss | -0.0703     |
|    value_loss           | 0.00158     |
-----------------------------------------

Eval num_timesteps=480000, episode_reward=-186071.98 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -1.86e+05  |
| time/                   |            |
|    total_timesteps      | 480000     |
| train/                  |            |
|    approx_kl            | 0.05730942 |
|    clip_fraction        | 0.448      |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.09      |
|    explained_variance   | 0.941      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.18      |
|    n_updates            | 290        |
|    policy_gradient_loss | -0.0695    |
|    value_loss           | 0.00153    |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -1.46e+05 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 30        |
|    time_elapsed    | 4212      |
|    total_timesteps | 491520    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.38e+05   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 31          |
|    time_elapsed         | 4352        |
|    total_timesteps      | 507904      |
| train/                  |             |
|    approx_kl            | 0.059267227 |
|    clip_fraction        | 0.461       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.03       |
|    explained_variance   | 0.956       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.167      |
|    n_updates            | 300         |
|    policy_gradient_loss | -0.0741     |
|    value_loss           | 0.00134     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.34e+05   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 32          |
|    time_elapsed         | 4491        |
|    total_timesteps      | 524288      |
| train/                  |             |
|    approx_kl            | 0.060532983 |
|    clip_fraction        | 0.461       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.92       |
|    explained_variance   | 0.948       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.146      |
|    n_updates            | 310         |
|    policy_gradient_loss | -0.0745     |
|    value_loss           | 0.00136     |
-----------------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 1.44e+03  |
|    ep_rew_mean          | -1.31e+05 |
| time/                   |           |
|    fps                  | 116       |
|    iterations           | 33        |
|    time_elapsed         | 4631      |
|    total_timesteps      | 540672    |
| train/                  |           |
|    approx_kl            | 0.057826  |
|    clip_fraction        | 0.453     |
|    clip_range           | 0.2       |
|    entropy_loss         | -6.85     |
|    explained_variance   | 0.945     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.151    |
|    n_updates            | 320       |
|    policy_gradient_loss | -0.0679   |
|    value_loss           | 0.00146   |
---------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.23e+05   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 34          |
|    time_elapsed         | 4771        |
|    total_timesteps      | 557056      |
| train/                  |             |
|    approx_kl            | 0.056467805 |
|    clip_fraction        | 0.436       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.76       |
|    explained_variance   | 0.966       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.148      |
|    n_updates            | 330         |
|    policy_gradient_loss | -0.0699     |
|    value_loss           | 0.00118     |
-----------------------------------------

Eval num_timesteps=560000, episode_reward=-206661.37 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -2.07e+05  |
| time/                   |            |
|    total_timesteps      | 560000     |
| train/                  |            |
|    approx_kl            | 0.05596806 |
|    clip_fraction        | 0.444      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.66      |
|    explained_variance   | 0.941      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.153     |
|    n_updates            | 340        |
|    policy_gradient_loss | -0.0645    |
|    value_loss           | 0.00126    |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -1.19e+05 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 35        |
|    time_elapsed    | 4918      |
|    total_timesteps | 573440    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.15e+05  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 36         |
|    time_elapsed         | 5058       |
|    total_timesteps      | 589824     |
| train/                  |            |
|    approx_kl            | 0.05913619 |
|    clip_fraction        | 0.446      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.64      |
|    explained_variance   | 0.949      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.165     |
|    n_updates            | 350        |
|    policy_gradient_loss | -0.068     |
|    value_loss           | 0.00106    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.11e+05   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 37          |
|    time_elapsed         | 5197        |
|    total_timesteps      | 606208      |
| train/                  |             |
|    approx_kl            | 0.056657813 |
|    clip_fraction        | 0.437       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.58       |
|    explained_variance   | 0.967       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.161      |
|    n_updates            | 360         |
|    policy_gradient_loss | -0.0657     |
|    value_loss           | 0.00126     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.05e+05   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 38          |
|    time_elapsed         | 5337        |
|    total_timesteps      | 622592      |
| train/                  |             |
|    approx_kl            | 0.057017982 |
|    clip_fraction        | 0.447       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.41       |
|    explained_variance   | 0.945       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.159      |
|    n_updates            | 370         |
|    policy_gradient_loss | -0.071      |
|    value_loss           | 0.000839    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.02e+05   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 39          |
|    time_elapsed         | 5476        |
|    total_timesteps      | 638976      |
| train/                  |             |
|    approx_kl            | 0.055842165 |
|    clip_fraction        | 0.438       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.42       |
|    explained_variance   | 0.938       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.171      |
|    n_updates            | 380         |
|    policy_gradient_loss | -0.0662     |
|    value_loss           | 0.00127     |
-----------------------------------------

Eval num_timesteps=640000, episode_reward=-178139.13 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -1.78e+05   |
| time/                   |             |
|    total_timesteps      | 640000      |
| train/                  |             |
|    approx_kl            | 0.057486814 |
|    clip_fraction        | 0.443       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.33       |
|    explained_variance   | 0.933       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.163      |
|    n_updates            | 390         |
|    policy_gradient_loss | -0.071      |
|    value_loss           | 0.000917    |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -9.86e+04 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 40        |
|    time_elapsed    | 5624      |
|    total_timesteps | 655360    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -9.48e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 41         |
|    time_elapsed         | 5763       |
|    total_timesteps      | 671744     |
| train/                  |            |
|    approx_kl            | 0.06289968 |
|    clip_fraction        | 0.448      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.31      |
|    explained_variance   | 0.96       |
|    learning_rate        | 0.0003     |
|    loss                 | -0.152     |
|    n_updates            | 400        |
|    policy_gradient_loss | -0.0721    |
|    value_loss           | 0.0009     |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -9.49e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 42         |
|    time_elapsed         | 5903       |
|    total_timesteps      | 688128     |
| train/                  |            |
|    approx_kl            | 0.06317358 |
|    clip_fraction        | 0.458      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.3       |
|    explained_variance   | 0.969      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.142     |
|    n_updates            | 410        |
|    policy_gradient_loss | -0.0723    |
|    value_loss           | 0.000819   |
----------------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 1.44e+03  |
|    ep_rew_mean          | -9.01e+04 |
| time/                   |           |
|    fps                  | 116       |
|    iterations           | 43        |
|    time_elapsed         | 6042      |
|    total_timesteps      | 704512    |
| train/                  |           |
|    approx_kl            | 0.0592239 |
|    clip_fraction        | 0.442     |
|    clip_range           | 0.2       |
|    entropy_loss         | -6.2      |
|    explained_variance   | 0.975     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.149    |
|    n_updates            | 420       |
|    policy_gradient_loss | -0.0693   |
|    value_loss           | 0.000704  |
---------------------------------------

Eval num_timesteps=720000, episode_reward=-175594.18 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -1.76e+05  |
| time/                   |            |
|    total_timesteps      | 720000     |
| train/                  |            |
|    approx_kl            | 0.05552402 |
|    clip_fraction        | 0.426      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.93      |
|    explained_variance   | 0.949      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.134     |
|    n_updates            | 430        |
|    policy_gradient_loss | -0.0659    |
|    value_loss           | 0.000544   |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -8.77e+04 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 44        |
|    time_elapsed    | 6190      |
|    total_timesteps | 720896    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -8.2e+04    |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 45          |
|    time_elapsed         | 6330        |
|    total_timesteps      | 737280      |
| train/                  |             |
|    approx_kl            | 0.059796296 |
|    clip_fraction        | 0.434       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.92       |
|    explained_variance   | 0.955       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.146      |
|    n_updates            | 440         |
|    policy_gradient_loss | -0.0648     |
|    value_loss           | 0.000508    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -8.03e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 46          |
|    time_elapsed         | 6469        |
|    total_timesteps      | 753664      |
| train/                  |             |
|    approx_kl            | 0.055868275 |
|    clip_fraction        | 0.428       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.74       |
|    explained_variance   | 0.94        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.119      |
|    n_updates            | 450         |
|    policy_gradient_loss | -0.0634     |
|    value_loss           | 0.000497    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -7.97e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 47         |
|    time_elapsed         | 6609       |
|    total_timesteps      | 770048     |
| train/                  |            |
|    approx_kl            | 0.06444135 |
|    clip_fraction        | 0.455      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.88      |
|    explained_variance   | 0.956      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.14      |
|    n_updates            | 460        |
|    policy_gradient_loss | -0.068     |
|    value_loss           | 0.000759   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -7.63e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 48          |
|    time_elapsed         | 6748        |
|    total_timesteps      | 786432      |
| train/                  |             |
|    approx_kl            | 0.070058264 |
|    clip_fraction        | 0.461       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.88       |
|    explained_variance   | 0.905       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.159      |
|    n_updates            | 470         |
|    policy_gradient_loss | -0.072      |
|    value_loss           | 0.000764    |
-----------------------------------------

Eval num_timesteps=800000, episode_reward=-104398.49 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -1.04e+05  |
| time/                   |            |
|    total_timesteps      | 800000     |
| train/                  |            |
|    approx_kl            | 0.06397545 |
|    clip_fraction        | 0.455      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.79      |
|    explained_variance   | 0.957      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.158     |
|    n_updates            | 480        |
|    policy_gradient_loss | -0.0719    |
|    value_loss           | 0.000666   |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -7.55e+04 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 49        |
|    time_elapsed    | 6896      |
|    total_timesteps | 802816    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -7.11e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 50          |
|    time_elapsed         | 7035        |
|    total_timesteps      | 819200      |
| train/                  |             |
|    approx_kl            | 0.066137284 |
|    clip_fraction        | 0.455       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.67       |
|    explained_variance   | 0.927       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.158      |
|    n_updates            | 490         |
|    policy_gradient_loss | -0.0709     |
|    value_loss           | 0.000666    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -6.7e+04   |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 51         |
|    time_elapsed         | 7175       |
|    total_timesteps      | 835584     |
| train/                  |            |
|    approx_kl            | 0.06157336 |
|    clip_fraction        | 0.447      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.64      |
|    explained_variance   | 0.947      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.164     |
|    n_updates            | 500        |
|    policy_gradient_loss | -0.0673    |
|    value_loss           | 0.000617   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -6.59e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 52          |
|    time_elapsed         | 7315        |
|    total_timesteps      | 851968      |
| train/                  |             |
|    approx_kl            | 0.060634635 |
|    clip_fraction        | 0.434       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.43       |
|    explained_variance   | 0.948       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.115      |
|    n_updates            | 510         |
|    policy_gradient_loss | -0.0674     |
|    value_loss           | 0.000423    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -6.49e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 53         |
|    time_elapsed         | 7454       |
|    total_timesteps      | 868352     |
| train/                  |            |
|    approx_kl            | 0.06695861 |
|    clip_fraction        | 0.464      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.52      |
|    explained_variance   | 0.948      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.146     |
|    n_updates            | 520        |
|    policy_gradient_loss | -0.0707    |
|    value_loss           | 0.000507   |
----------------------------------------

Eval num_timesteps=880000, episode_reward=-91843.97 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -9.18e+04   |
| time/                   |             |
|    total_timesteps      | 880000      |
| train/                  |             |
|    approx_kl            | 0.062156357 |
|    clip_fraction        | 0.45        |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.49       |
|    explained_variance   | 0.954       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.142      |
|    n_updates            | 530         |
|    policy_gradient_loss | -0.0691     |
|    value_loss           | 0.000553    |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -6.45e+04 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 54        |
|    time_elapsed    | 7601      |
|    total_timesteps | 884736    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -6.21e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 55         |
|    time_elapsed         | 7741       |
|    total_timesteps      | 901120     |
| train/                  |            |
|    approx_kl            | 0.06864387 |
|    clip_fraction        | 0.461      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.48      |
|    explained_variance   | 0.951      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.153     |
|    n_updates            | 540        |
|    policy_gradient_loss | -0.0732    |
|    value_loss           | 0.000586   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -6.21e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 56         |
|    time_elapsed         | 7881       |
|    total_timesteps      | 917504     |
| train/                  |            |
|    approx_kl            | 0.06281404 |
|    clip_fraction        | 0.445      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.23      |
|    explained_variance   | 0.953      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.154     |
|    n_updates            | 550        |
|    policy_gradient_loss | -0.0692    |
|    value_loss           | 0.000363   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -5.95e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 57          |
|    time_elapsed         | 8021        |
|    total_timesteps      | 933888      |
| train/                  |             |
|    approx_kl            | 0.068340175 |
|    clip_fraction        | 0.459       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.38       |
|    explained_variance   | 0.966       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.151      |
|    n_updates            | 560         |
|    policy_gradient_loss | -0.0697     |
|    value_loss           | 0.000427    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -5.84e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 58          |
|    time_elapsed         | 8161        |
|    total_timesteps      | 950272      |
| train/                  |             |
|    approx_kl            | 0.062300228 |
|    clip_fraction        | 0.444       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.26       |
|    explained_variance   | 0.913       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.153      |
|    n_updates            | 570         |
|    policy_gradient_loss | -0.0702     |
|    value_loss           | 0.00051     |
-----------------------------------------

Eval num_timesteps=960000, episode_reward=-103515.39 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -1.04e+05  |
| time/                   |            |
|    total_timesteps      | 960000     |
| train/                  |            |
|    approx_kl            | 0.06598286 |
|    clip_fraction        | 0.451      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.21      |
|    explained_variance   | 0.947      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.142     |
|    n_updates            | 580        |
|    policy_gradient_loss | -0.0686    |
|    value_loss           | 0.000411   |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -5.77e+04 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 59        |
|    time_elapsed    | 8308      |
|    total_timesteps | 966656    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -5.63e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 60         |
|    time_elapsed         | 8447       |
|    total_timesteps      | 983040     |
| train/                  |            |
|    approx_kl            | 0.06808746 |
|    clip_fraction        | 0.462      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.18      |
|    explained_variance   | 0.942      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.137     |
|    n_updates            | 590        |
|    policy_gradient_loss | -0.0706    |
|    value_loss           | 0.000428   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -5.51e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 61         |
|    time_elapsed         | 8587       |
|    total_timesteps      | 999424     |
| train/                  |            |
|    approx_kl            | 0.06251978 |
|    clip_fraction        | 0.434      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.95      |
|    explained_variance   | 0.964      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.141     |
|    n_updates            | 600        |
|    policy_gradient_loss | -0.0681    |
|    value_loss           | 0.000298   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -5.22e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 62         |
|    time_elapsed         | 8726       |
|    total_timesteps      | 1015808    |
| train/                  |            |
|    approx_kl            | 0.06272164 |
|    clip_fraction        | 0.44       |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.96      |
|    explained_variance   | 0.941      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.147     |
|    n_updates            | 610        |
|    policy_gradient_loss | -0.0691    |
|    value_loss           | 0.000356   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -5.07e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 63          |
|    time_elapsed         | 8866        |
|    total_timesteps      | 1032192     |
| train/                  |             |
|    approx_kl            | 0.067469016 |
|    clip_fraction        | 0.458       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.94       |
|    explained_variance   | 0.93        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.149      |
|    n_updates            | 620         |
|    policy_gradient_loss | -0.0718     |
|    value_loss           | 0.000372    |
-----------------------------------------

Eval num_timesteps=1040000, episode_reward=-70751.67 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -7.08e+04  |
| time/                   |            |
|    total_timesteps      | 1040000    |
| train/                  |            |
|    approx_kl            | 0.06154688 |
|    clip_fraction        | 0.428      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.8       |
|    explained_variance   | 0.958      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.13      |
|    n_updates            | 630        |
|    policy_gradient_loss | -0.0703    |
|    value_loss           | 0.000278   |
----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -4.83e+04 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 64        |
|    time_elapsed    | 9013      |
|    total_timesteps | 1048576   |
----------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 1.44e+03  |
|    ep_rew_mean          | -4.65e+04 |
| time/                   |           |
|    fps                  | 116       |
|    iterations           | 65        |
|    time_elapsed         | 9152      |
|    total_timesteps      | 1064960   |
| train/                  |           |
|    approx_kl            | 0.0642607 |
|    clip_fraction        | 0.437     |
|    clip_range           | 0.2       |
|    entropy_loss         | -4.74     |
|    explained_variance   | 0.943     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.139    |
|    n_updates            | 640       |
|    policy_gradient_loss | -0.0711   |
|    value_loss           | 0.00024   |
---------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -4.54e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 66          |
|    time_elapsed         | 9292        |
|    total_timesteps      | 1081344     |
| train/                  |             |
|    approx_kl            | 0.063814335 |
|    clip_fraction        | 0.439       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.7        |
|    explained_variance   | 0.964       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.116      |
|    n_updates            | 650         |
|    policy_gradient_loss | -0.0682     |
|    value_loss           | 0.000192    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -4.36e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 67         |
|    time_elapsed         | 9432       |
|    total_timesteps      | 1097728    |
| train/                  |            |
|    approx_kl            | 0.06696312 |
|    clip_fraction        | 0.449      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.67      |
|    explained_variance   | 0.925      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.124     |
|    n_updates            | 660        |
|    policy_gradient_loss | -0.071     |
|    value_loss           | 0.00031    |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -4.18e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 68         |
|    time_elapsed         | 9572       |
|    total_timesteps      | 1114112    |
| train/                  |            |
|    approx_kl            | 0.06467039 |
|    clip_fraction        | 0.447      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.67      |
|    explained_variance   | 0.944      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.146     |
|    n_updates            | 670        |
|    policy_gradient_loss | -0.0704    |
|    value_loss           | 0.000261   |
----------------------------------------

Eval num_timesteps=1120000, episode_reward=-56121.93 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -5.61e+04   |
| time/                   |             |
|    total_timesteps      | 1120000     |
| train/                  |             |
|    approx_kl            | 0.060814947 |
|    clip_fraction        | 0.429       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.5        |
|    explained_variance   | 0.951       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.151      |
|    n_updates            | 680         |
|    policy_gradient_loss | -0.0671     |
|    value_loss           | 0.000199    |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -4.06e+04 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 69        |
|    time_elapsed    | 9719      |
|    total_timesteps | 1130496   |
----------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 1.44e+03  |
|    ep_rew_mean          | -4e+04    |
| time/                   |           |
|    fps                  | 116       |
|    iterations           | 70        |
|    time_elapsed         | 9859      |
|    total_timesteps      | 1146880   |
| train/                  |           |
|    approx_kl            | 0.0674922 |
|    clip_fraction        | 0.442     |
|    clip_range           | 0.2       |
|    entropy_loss         | -4.55     |
|    explained_variance   | 0.943     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.139    |
|    n_updates            | 690       |
|    policy_gradient_loss | -0.0694   |
|    value_loss           | 0.000247  |
---------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -3.9e+04   |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 71         |
|    time_elapsed         | 9999       |
|    total_timesteps      | 1163264    |
| train/                  |            |
|    approx_kl            | 0.06757197 |
|    clip_fraction        | 0.439      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.53      |
|    explained_variance   | 0.948      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.142     |
|    n_updates            | 700        |
|    policy_gradient_loss | -0.07      |
|    value_loss           | 0.000223   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -3.8e+04   |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 72         |
|    time_elapsed         | 10139      |
|    total_timesteps      | 1179648    |
| train/                  |            |
|    approx_kl            | 0.06275918 |
|    clip_fraction        | 0.439      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.28      |
|    explained_variance   | 0.956      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.161     |
|    n_updates            | 710        |
|    policy_gradient_loss | -0.0677    |
|    value_loss           | 0.000177   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -3.74e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 73         |
|    time_elapsed         | 10278      |
|    total_timesteps      | 1196032    |
| train/                  |            |
|    approx_kl            | 0.06856445 |
|    clip_fraction        | 0.454      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.47      |
|    explained_variance   | 0.959      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.141     |
|    n_updates            | 720        |
|    policy_gradient_loss | -0.0738    |
|    value_loss           | 0.00023    |
----------------------------------------

Eval num_timesteps=1200000, episode_reward=-38995.01 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -3.9e+04   |
| time/                   |            |
|    total_timesteps      | 1200000    |
| train/                  |            |
|    approx_kl            | 0.06525032 |
|    clip_fraction        | 0.444      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.36      |
|    explained_variance   | 0.957      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.145     |
|    n_updates            | 730        |
|    policy_gradient_loss | -0.0705    |
|    value_loss           | 0.000195   |
----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -3.61e+04 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 74        |
|    time_elapsed    | 10426     |
|    total_timesteps | 1212416   |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -3.55e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 75         |
|    time_elapsed         | 10565      |
|    total_timesteps      | 1228800    |
| train/                  |            |
|    approx_kl            | 0.06475712 |
|    clip_fraction        | 0.434      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.23      |
|    explained_variance   | 0.953      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.148     |
|    n_updates            | 740        |
|    policy_gradient_loss | -0.0672    |
|    value_loss           | 0.000191   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -3.42e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 76          |
|    time_elapsed         | 10705       |
|    total_timesteps      | 1245184     |
| train/                  |             |
|    approx_kl            | 0.062294483 |
|    clip_fraction        | 0.434       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.17       |
|    explained_variance   | 0.947       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.127      |
|    n_updates            | 750         |
|    policy_gradient_loss | -0.0631     |
|    value_loss           | 0.000147    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -3.36e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 77         |
|    time_elapsed         | 10845      |
|    total_timesteps      | 1261568    |
| train/                  |            |
|    approx_kl            | 0.06359811 |
|    clip_fraction        | 0.436      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.16      |
|    explained_variance   | 0.953      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.11      |
|    n_updates            | 760        |
|    policy_gradient_loss | -0.0669    |
|    value_loss           | 0.000167   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -3.28e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 78         |
|    time_elapsed         | 10985      |
|    total_timesteps      | 1277952    |
| train/                  |            |
|    approx_kl            | 0.06530676 |
|    clip_fraction        | 0.445      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.1       |
|    explained_variance   | 0.892      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.13      |
|    n_updates            | 770        |
|    policy_gradient_loss | -0.0714    |
|    value_loss           | 0.000162   |
----------------------------------------

Eval num_timesteps=1280000, episode_reward=-24423.42 +/- 0.00

Episode length: 1440.00 +/- 0.00

---------------------------------------
| eval/                   |           |
|    mean_ep_length       | 1.44e+03  |
|    mean_reward          | -2.44e+04 |
| time/                   |           |
|    total_timesteps      | 1280000   |
| train/                  |           |
|    approx_kl            | 0.0653644 |
|    clip_fraction        | 0.442     |
|    clip_range           | 0.2       |
|    entropy_loss         | -4.12     |
|    explained_variance   | 0.94      |
|    learning_rate        | 0.0003    |
|    loss                 | -0.122    |
|    n_updates            | 780       |
|    policy_gradient_loss | -0.0677   |
|    value_loss           | 0.00017   |
---------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -3.17e+04 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 79        |
|    time_elapsed    | 11133     |
|    total_timesteps | 1294336   |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -3.12e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 80          |
|    time_elapsed         | 11272       |
|    total_timesteps      | 1310720     |
| train/                  |             |
|    approx_kl            | 0.066812575 |
|    clip_fraction        | 0.437       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4          |
|    explained_variance   | 0.965       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.153      |
|    n_updates            | 790         |
|    policy_gradient_loss | -0.07       |
|    value_loss           | 0.000146    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.97e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 81         |
|    time_elapsed         | 11412      |
|    total_timesteps      | 1327104    |
| train/                  |            |
|    approx_kl            | 0.06258772 |
|    clip_fraction        | 0.432      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.87      |
|    explained_variance   | 0.924      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.15      |
|    n_updates            | 800        |
|    policy_gradient_loss | -0.0676    |
|    value_loss           | 0.000123   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.85e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 82         |
|    time_elapsed         | 11551      |
|    total_timesteps      | 1343488    |
| train/                  |            |
|    approx_kl            | 0.06756975 |
|    clip_fraction        | 0.44       |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.89      |
|    explained_variance   | 0.973      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.121     |
|    n_updates            | 810        |
|    policy_gradient_loss | -0.0716    |
|    value_loss           | 0.000126   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -2.76e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 83          |
|    time_elapsed         | 11691       |
|    total_timesteps      | 1359872     |
| train/                  |             |
|    approx_kl            | 0.061786972 |
|    clip_fraction        | 0.422       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.77       |
|    explained_variance   | 0.952       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.106      |
|    n_updates            | 820         |
|    policy_gradient_loss | -0.0678     |
|    value_loss           | 0.000112    |
-----------------------------------------

Eval num_timesteps=1360000, episode_reward=-20843.25 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -2.08e+04   |
| time/                   |             |
|    total_timesteps      | 1360000     |
| train/                  |             |
|    approx_kl            | 0.061146136 |
|    clip_fraction        | 0.419       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.7        |
|    explained_variance   | 0.961       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.122      |
|    n_updates            | 830         |
|    policy_gradient_loss | -0.0666     |
|    value_loss           | 0.000107    |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -2.71e+04 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 84        |
|    time_elapsed    | 11839     |
|    total_timesteps | 1376256   |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.65e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 85         |
|    time_elapsed         | 11978      |
|    total_timesteps      | 1392640    |
| train/                  |            |
|    approx_kl            | 0.06351592 |
|    clip_fraction        | 0.427      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.7       |
|    explained_variance   | 0.892      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0877    |
|    n_updates            | 840        |
|    policy_gradient_loss | -0.0662    |
|    value_loss           | 0.00011    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -2.54e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 86          |
|    time_elapsed         | 12117       |
|    total_timesteps      | 1409024     |
| train/                  |             |
|    approx_kl            | 0.068031035 |
|    clip_fraction        | 0.432       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.67       |
|    explained_variance   | 0.939       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.116      |
|    n_updates            | 850         |
|    policy_gradient_loss | -0.0654     |
|    value_loss           | 0.000117    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.48e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 87         |
|    time_elapsed         | 12257      |
|    total_timesteps      | 1425408    |
| train/                  |            |
|    approx_kl            | 0.06587799 |
|    clip_fraction        | 0.432      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.66      |
|    explained_variance   | 0.93       |
|    learning_rate        | 0.0003     |
|    loss                 | -0.149     |
|    n_updates            | 860        |
|    policy_gradient_loss | -0.0685    |
|    value_loss           | 0.000123   |
----------------------------------------

Eval num_timesteps=1440000, episode_reward=-29518.65 +/- 0.00

Episode length: 1440.00 +/- 0.00

---------------------------------------
| eval/                   |           |
|    mean_ep_length       | 1.44e+03  |
|    mean_reward          | -2.95e+04 |
| time/                   |           |
|    total_timesteps      | 1440000   |
| train/                  |           |
|    approx_kl            | 0.0657579 |
|    clip_fraction        | 0.424     |
|    clip_range           | 0.2       |
|    entropy_loss         | -3.58     |
|    explained_variance   | 0.965     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.127    |
|    n_updates            | 870       |
|    policy_gradient_loss | -0.0706   |
|    value_loss           | 0.000102  |
---------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -2.37e+04 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 88        |
|    time_elapsed    | 12404     |
|    total_timesteps | 1441792   |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -2.33e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 89          |
|    time_elapsed         | 12544       |
|    total_timesteps      | 1458176     |
| train/                  |             |
|    approx_kl            | 0.063335374 |
|    clip_fraction        | 0.418       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.39       |
|    explained_variance   | 0.963       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.13       |
|    n_updates            | 880         |
|    policy_gradient_loss | -0.064      |
|    value_loss           | 7.64e-05    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2.22e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 90         |
|    time_elapsed         | 12684      |
|    total_timesteps      | 1474560    |
| train/                  |            |
|    approx_kl            | 0.06743401 |
|    clip_fraction        | 0.432      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.35      |
|    explained_variance   | 0.96       |
|    learning_rate        | 0.0003     |
|    loss                 | -0.125     |
|    n_updates            | 890        |
|    policy_gradient_loss | -0.067     |
|    value_loss           | 7.83e-05   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -2.18e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 91          |
|    time_elapsed         | 12824       |
|    total_timesteps      | 1490944     |
| train/                  |             |
|    approx_kl            | 0.062375598 |
|    clip_fraction        | 0.415       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.34       |
|    explained_variance   | 0.954       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.108      |
|    n_updates            | 900         |
|    policy_gradient_loss | -0.063      |
|    value_loss           | 8.24e-05    |
-----------------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 1.44e+03  |
|    ep_rew_mean          | -2.14e+04 |
| time/                   |           |
|    fps                  | 116       |
|    iterations           | 92        |
|    time_elapsed         | 12975     |
|    total_timesteps      | 1507328   |
| train/                  |           |
|    approx_kl            | 0.0692452 |
|    clip_fraction        | 0.437     |
|    clip_range           | 0.2       |
|    entropy_loss         | -3.35     |
|    explained_variance   | 0.933     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.12     |
|    n_updates            | 910       |
|    policy_gradient_loss | -0.0699   |
|    value_loss           | 9.29e-05  |
---------------------------------------

Eval num_timesteps=1520000, episode_reward=-37401.44 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -3.74e+04  |
| time/                   |            |
|    total_timesteps      | 1520000    |
| train/                  |            |
|    approx_kl            | 0.06776564 |
|    clip_fraction        | 0.421      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.14      |
|    explained_variance   | 0.955      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.123     |
|    n_updates            | 920        |
|    policy_gradient_loss | -0.0654    |
|    value_loss           | 8.42e-05   |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -2.01e+04 |
| time/              |           |
|    fps             | 116       |
|    iterations      | 93        |
|    time_elapsed    | 13126     |
|    total_timesteps | 1523712   |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -2e+04     |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 94         |
|    time_elapsed         | 13268      |
|    total_timesteps      | 1540096    |
| train/                  |            |
|    approx_kl            | 0.06002878 |
|    clip_fraction        | 0.402      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.01      |
|    explained_variance   | 0.964      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.132     |
|    n_updates            | 930        |
|    policy_gradient_loss | -0.0644    |
|    value_loss           | 6.71e-05   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.96e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 95          |
|    time_elapsed         | 13410       |
|    total_timesteps      | 1556480     |
| train/                  |             |
|    approx_kl            | 0.070125006 |
|    clip_fraction        | 0.411       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.17       |
|    explained_variance   | 0.978       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.134      |
|    n_updates            | 940         |
|    policy_gradient_loss | -0.0679     |
|    value_loss           | 8.37e-05    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.92e+04   |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 96          |
|    time_elapsed         | 13554       |
|    total_timesteps      | 1572864     |
| train/                  |             |
|    approx_kl            | 0.071290694 |
|    clip_fraction        | 0.44        |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.23       |
|    explained_variance   | 0.962       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.128      |
|    n_updates            | 950         |
|    policy_gradient_loss | -0.0711     |
|    value_loss           | 0.000105    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.9e+04    |
| time/                   |             |
|    fps                  | 116         |
|    iterations           | 97          |
|    time_elapsed         | 13695       |
|    total_timesteps      | 1589248     |
| train/                  |             |
|    approx_kl            | 0.067772046 |
|    clip_fraction        | 0.424       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.07       |
|    explained_variance   | 0.977       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.137      |
|    n_updates            | 960         |
|    policy_gradient_loss | -0.0676     |
|    value_loss           | 7.67e-05    |
-----------------------------------------

Eval num_timesteps=1600000, episode_reward=-23402.73 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -2.34e+04  |
| time/                   |            |
|    total_timesteps      | 1600000    |
| train/                  |            |
|    approx_kl            | 0.06914088 |
|    clip_fraction        | 0.424      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.04      |
|    explained_variance   | 0.964      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.126     |
|    n_updates            | 970        |
|    policy_gradient_loss | -0.0703    |
|    value_loss           | 9.73e-05   |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -1.89e+04 |
| time/              |           |
|    fps             | 115       |
|    iterations      | 98        |
|    time_elapsed    | 13845     |
|    total_timesteps | 1605632   |
----------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 1.44e+03  |
|    ep_rew_mean          | -1.85e+04 |
| time/                   |           |
|    fps                  | 115       |
|    iterations           | 99        |
|    time_elapsed         | 13987     |
|    total_timesteps      | 1622016   |
| train/                  |           |
|    approx_kl            | 0.0645529 |
|    clip_fraction        | 0.405     |
|    clip_range           | 0.2       |
|    entropy_loss         | -2.89     |
|    explained_variance   | 0.975     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.115    |
|    n_updates            | 980       |
|    policy_gradient_loss | -0.0635   |
|    value_loss           | 7.06e-05  |
---------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.73e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 100        |
|    time_elapsed         | 14128      |
|    total_timesteps      | 1638400    |
| train/                  |            |
|    approx_kl            | 0.06558834 |
|    clip_fraction        | 0.404      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.82      |
|    explained_variance   | 0.928      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.15      |
|    n_updates            | 990        |
|    policy_gradient_loss | -0.0658    |
|    value_loss           | 7.18e-05   |
----------------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 1.44e+03  |
|    ep_rew_mean          | -1.72e+04 |
| time/                   |           |
|    fps                  | 115       |
|    iterations           | 101       |
|    time_elapsed         | 14268     |
|    total_timesteps      | 1654784   |
| train/                  |           |
|    approx_kl            | 0.0654707 |
|    clip_fraction        | 0.405     |
|    clip_range           | 0.2       |
|    entropy_loss         | -2.74     |
|    explained_variance   | 0.935     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.124    |
|    n_updates            | 1000      |
|    policy_gradient_loss | -0.0663   |
|    value_loss           | 6.79e-05  |
---------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.72e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 102        |
|    time_elapsed         | 14407      |
|    total_timesteps      | 1671168    |
| train/                  |            |
|    approx_kl            | 0.07167548 |
|    clip_fraction        | 0.429      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.98      |
|    explained_variance   | 0.921      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.123     |
|    n_updates            | 1010       |
|    policy_gradient_loss | -0.069     |
|    value_loss           | 9.41e-05   |
----------------------------------------

Eval num_timesteps=1680000, episode_reward=-22047.16 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -2.2e+04   |
| time/                   |            |
|    total_timesteps      | 1680000    |
| train/                  |            |
|    approx_kl            | 0.06385507 |
|    clip_fraction        | 0.399      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.67      |
|    explained_variance   | 0.966      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.112     |
|    n_updates            | 1020       |
|    policy_gradient_loss | -0.0673    |
|    value_loss           | 6.11e-05   |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -1.64e+04 |
| time/              |           |
|    fps             | 115       |
|    iterations      | 103       |
|    time_elapsed    | 14555     |
|    total_timesteps | 1687552   |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.58e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 104        |
|    time_elapsed         | 14694      |
|    total_timesteps      | 1703936    |
| train/                  |            |
|    approx_kl            | 0.06556325 |
|    clip_fraction        | 0.398      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.59      |
|    explained_variance   | 0.937      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.125     |
|    n_updates            | 1030       |
|    policy_gradient_loss | -0.0635    |
|    value_loss           | 7.66e-05   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.5e+04   |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 105        |
|    time_elapsed         | 14833      |
|    total_timesteps      | 1720320    |
| train/                  |            |
|    approx_kl            | 0.06559956 |
|    clip_fraction        | 0.41       |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.62      |
|    explained_variance   | 0.945      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.109     |
|    n_updates            | 1040       |
|    policy_gradient_loss | -0.0648    |
|    value_loss           | 7.83e-05   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.42e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 106        |
|    time_elapsed         | 14973      |
|    total_timesteps      | 1736704    |
| train/                  |            |
|    approx_kl            | 0.06792934 |
|    clip_fraction        | 0.41       |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.6       |
|    explained_variance   | 0.947      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0959    |
|    n_updates            | 1050       |
|    policy_gradient_loss | -0.0668    |
|    value_loss           | 7.37e-05   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.36e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 107        |
|    time_elapsed         | 15113      |
|    total_timesteps      | 1753088    |
| train/                  |            |
|    approx_kl            | 0.06469935 |
|    clip_fraction        | 0.388      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.46      |
|    explained_variance   | 0.952      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.115     |
|    n_updates            | 1060       |
|    policy_gradient_loss | -0.0648    |
|    value_loss           | 5.55e-05   |
----------------------------------------

Eval num_timesteps=1760000, episode_reward=-20561.95 +/- 0.00

Episode length: 1440.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.44e+03    |
|    mean_reward          | -2.06e+04   |
| time/                   |             |
|    total_timesteps      | 1760000     |
| train/                  |             |
|    approx_kl            | 0.065744266 |
|    clip_fraction        | 0.395       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.55       |
|    explained_variance   | 0.965       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.132      |
|    n_updates            | 1070        |
|    policy_gradient_loss | -0.0652     |
|    value_loss           | 6.74e-05    |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -1.36e+04 |
| time/              |           |
|    fps             | 115       |
|    iterations      | 108       |
|    time_elapsed    | 15260     |
|    total_timesteps | 1769472   |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.34e+04   |
| time/                   |             |
|    fps                  | 115         |
|    iterations           | 109         |
|    time_elapsed         | 15400       |
|    total_timesteps      | 1785856     |
| train/                  |             |
|    approx_kl            | 0.066305384 |
|    clip_fraction        | 0.398       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.49       |
|    explained_variance   | 0.965       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.124      |
|    n_updates            | 1080        |
|    policy_gradient_loss | -0.0661     |
|    value_loss           | 4.8e-05     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.29e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 110        |
|    time_elapsed         | 15540      |
|    total_timesteps      | 1802240    |
| train/                  |            |
|    approx_kl            | 0.06812334 |
|    clip_fraction        | 0.41       |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.51      |
|    explained_variance   | 0.962      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.102     |
|    n_updates            | 1090       |
|    policy_gradient_loss | -0.0669    |
|    value_loss           | 7.76e-05   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.24e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 111        |
|    time_elapsed         | 15679      |
|    total_timesteps      | 1818624    |
| train/                  |            |
|    approx_kl            | 0.06323826 |
|    clip_fraction        | 0.376      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.26      |
|    explained_variance   | 0.957      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.111     |
|    n_updates            | 1100       |
|    policy_gradient_loss | -0.0618    |
|    value_loss           | 5.42e-05   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.23e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 112        |
|    time_elapsed         | 15819      |
|    total_timesteps      | 1835008    |
| train/                  |            |
|    approx_kl            | 0.06628005 |
|    clip_fraction        | 0.384      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.22      |
|    explained_variance   | 0.959      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.113     |
|    n_updates            | 1110       |
|    policy_gradient_loss | -0.0633    |
|    value_loss           | 4.38e-05   |
----------------------------------------

Eval num_timesteps=1840000, episode_reward=-15021.47 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -1.5e+04   |
| time/                   |            |
|    total_timesteps      | 1840000    |
| train/                  |            |
|    approx_kl            | 0.06974986 |
|    clip_fraction        | 0.389      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.24      |
|    explained_variance   | 0.966      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.112     |
|    n_updates            | 1120       |
|    policy_gradient_loss | -0.0633    |
|    value_loss           | 5.12e-05   |
----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -1.21e+04 |
| time/              |           |
|    fps             | 115       |
|    iterations      | 113       |
|    time_elapsed    | 15966     |
|    total_timesteps | 1851392   |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.44e+03    |
|    ep_rew_mean          | -1.17e+04   |
| time/                   |             |
|    fps                  | 115         |
|    iterations           | 114         |
|    time_elapsed         | 16106       |
|    total_timesteps      | 1867776     |
| train/                  |             |
|    approx_kl            | 0.077002294 |
|    clip_fraction        | 0.408       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.33       |
|    explained_variance   | 0.934       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.127      |
|    n_updates            | 1130        |
|    policy_gradient_loss | -0.068      |
|    value_loss           | 6.21e-05    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.19e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 115        |
|    time_elapsed         | 16245      |
|    total_timesteps      | 1884160    |
| train/                  |            |
|    approx_kl            | 0.07522808 |
|    clip_fraction        | 0.411      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.29      |
|    explained_variance   | 0.971      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.116     |
|    n_updates            | 1140       |
|    policy_gradient_loss | -0.0657    |
|    value_loss           | 4.76e-05   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.17e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 116        |
|    time_elapsed         | 16385      |
|    total_timesteps      | 1900544    |
| train/                  |            |
|    approx_kl            | 0.07202757 |
|    clip_fraction        | 0.401      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.27      |
|    explained_variance   | 0.971      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.104     |
|    n_updates            | 1150       |
|    policy_gradient_loss | -0.0616    |
|    value_loss           | 4.7e-05    |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.11e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 117        |
|    time_elapsed         | 16525      |
|    total_timesteps      | 1916928    |
| train/                  |            |
|    approx_kl            | 0.07060522 |
|    clip_fraction        | 0.399      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.1       |
|    explained_variance   | 0.963      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.125     |
|    n_updates            | 1160       |
|    policy_gradient_loss | -0.0652    |
|    value_loss           | 4.49e-05   |
----------------------------------------

Eval num_timesteps=1920000, episode_reward=-12803.86 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -1.28e+04  |
| time/                   |            |
|    total_timesteps      | 1920000    |
| train/                  |            |
|    approx_kl            | 0.06943188 |
|    clip_fraction        | 0.396      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.11      |
|    explained_variance   | 0.972      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.1       |
|    n_updates            | 1170       |
|    policy_gradient_loss | -0.0641    |
|    value_loss           | 3.93e-05   |
----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.44e+03  |
|    ep_rew_mean     | -1.11e+04 |
| time/              |           |
|    fps             | 115       |
|    iterations      | 118       |
|    time_elapsed    | 16672     |
|    total_timesteps | 1933312   |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.07e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 119        |
|    time_elapsed         | 16811      |
|    total_timesteps      | 1949696    |
| train/                  |            |
|    approx_kl            | 0.07588082 |
|    clip_fraction        | 0.406      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.11      |
|    explained_variance   | 0.947      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.109     |
|    n_updates            | 1180       |
|    policy_gradient_loss | -0.0674    |
|    value_loss           | 6.03e-05   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.08e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 120        |
|    time_elapsed         | 16950      |
|    total_timesteps      | 1966080    |
| train/                  |            |
|    approx_kl            | 0.07124499 |
|    clip_fraction        | 0.39       |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.96      |
|    explained_variance   | 0.957      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.107     |
|    n_updates            | 1190       |
|    policy_gradient_loss | -0.0627    |
|    value_loss           | 3.68e-05   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.03e+04  |
| time/                   |            |
|    fps                  | 115        |
|    iterations           | 121        |
|    time_elapsed         | 17091      |
|    total_timesteps      | 1982464    |
| train/                  |            |
|    approx_kl            | 0.07606472 |
|    clip_fraction        | 0.397      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.08      |
|    explained_variance   | 0.98       |
|    learning_rate        | 0.0003     |
|    loss                 | -0.102     |
|    n_updates            | 1200       |
|    policy_gradient_loss | -0.0641    |
|    value_loss           | 4.02e-05   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.44e+03   |
|    ep_rew_mean          | -1.03e+04  |
| time/                   |            |
|    fps                  | 116        |
|    iterations           | 122        |
|    time_elapsed         | 17231      |
|    total_timesteps      | 1998848    |
| train/                  |            |
|    approx_kl            | 0.07536402 |
|    clip_fraction        | 0.39       |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.9       |
|    explained_variance   | 0.967      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.114     |
|    n_updates            | 1210       |
|    policy_gradient_loss | -0.061     |
|    value_loss           | 3.47e-05   |
----------------------------------------

Eval num_timesteps=2000000, episode_reward=-11419.96 +/- 0.00

Episode length: 1440.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.44e+03   |
|    mean_reward          | -1.14e+04  |
| time/                   |            |
|    total_timesteps      | 2000000    |
| train/                  |            |
|    approx_kl            | 0.07499173 |
|    clip_fraction        | 0.398      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2         |
|    explained_variance   | 0.974      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0938    |
|    n_updates            | 1220       |
|    policy_gradient_loss | -0.0628    |
|    value_loss           | 3.59e-05   |
----------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 1.44e+03 |
|    ep_rew_mean     | -1e+04   |
| time/              |          |
|    fps             | 115      |
|    iterations      | 123      |
|    time_elapsed    | 17378    |
|    total_timesteps | 2015232  |
---------------------------------

Training completed in 4:49:50.497206
Model saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\rl_models\ppo_cost.zip
VecNormalize saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\rl_models\ppo_cost_vecnormalize.pkl

✅ Training complete for both scenarios!

In [4]:
# ============================================================
# EVALUATION (Full Test Set)
# ============================================================
print("=" * 60)
print("📊 EVALUATION ON FULL TEST SET")
print("=" * 60)
print(f"   • episode_length: {EVAL_EPISODE_LENGTH} steps (full test)")
print("=" * 60)

results = {}

for scenario in [SCENARIO_OVERLOAD, SCENARIO_COST]:
    print(f"\n🔍 Evaluating {scenario.upper()} scenario...")
    comp = evaluate_scenario(
        scenario,
        episode_length=EVAL_EPISODE_LENGTH,  # Full test set
        horizon=exp_config.horizon,
    )
    results[scenario] = comp
    print_comparison(comp)

print("\n✅ Evaluation complete!")
print("📁 Results saved to: results/ppo_schedule_test_*.csv")
results

============================================================
📊 EVALUATION ON FULL TEST SET
============================================================
   • episode_length: 17150 steps (full test)
============================================================

🔍 Evaluating OVERLOAD scenario...

============================================================
Evaluating scenario: OVERLOAD
============================================================
Latest model: models\random_forest_cpu_total_usage_20251111_221930.pkl
✓ Model loaded: models\random_forest_cpu_total_usage_20251111_221930.pkl
  Model: random_forest
  Target: cpu_total_usage
  Saved at: 2025-11-11 22:19:30
Latest model: models\svr_memory_usage_pct_20251111_184735.pkl
✓ Model loaded: models\svr_memory_usage_pct_20251111_184735.pkl
  Model: svr
  Target: memory_usage_pct
  Saved at: 2025-11-11 18:47:35
Latest model: models\random_forest_system_load_20251111_221944.pkl
✓ Model loaded: models\random_forest_system_load_20251111_221944.pkl
  Model: random_forest
  Target: system_load
  Saved at: 2025-11-11 22:19:44
Loaded model from E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\rl_models\ppo_overload.zip

Running PPO rollout for scenario: overload
Latest model: models\random_forest_cpu_total_usage_20251111_221930.pkl
✓ Model loaded: models\random_forest_cpu_total_usage_20251111_221930.pkl
  Model: random_forest
  Target: cpu_total_usage
  Saved at: 2025-11-11 22:19:30
Latest model: models\svr_memory_usage_pct_20251111_184735.pkl
✓ Model loaded: models\svr_memory_usage_pct_20251111_184735.pkl
  Model: svr
  Target: memory_usage_pct
  Saved at: 2025-11-11 18:47:35
Latest model: models\random_forest_system_load_20251111_221944.pkl
✓ Model loaded: models\random_forest_system_load_20251111_221944.pkl
  Model: random_forest
  Target: system_load
  Saved at: 2025-11-11 22:19:44
PPO schedule saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\forecast_result\ppo_schedule_test_overload.csv
PPO 30min bucket saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\forecast_result\ppo_schedule_30min_overload.csv
Warning: LP schedule not found at E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\forecast_result\vm_schedule.csv
Run 'python vm_resource_planner.py' first to generate baseline.

============================================================
RESULTS: OVERLOAD
============================================================

PPO Performance:
  Total VM Cost: $185.3248
  Total Switching Cost: $20.8000
  Total Cost: $206.1248
  SLA Violations: 5 (0.0%)
  Mean CPU Utilization: 0.1%
  Mean Memory Utilization: 0.0%

🔍 Evaluating COST scenario...

============================================================
Evaluating scenario: COST
============================================================
Latest model: models\random_forest_cpu_total_usage_20251111_221930.pkl
✓ Model loaded: models\random_forest_cpu_total_usage_20251111_221930.pkl
  Model: random_forest
  Target: cpu_total_usage
  Saved at: 2025-11-11 22:19:30
Latest model: models\svr_memory_usage_pct_20251111_184735.pkl
✓ Model loaded: models\svr_memory_usage_pct_20251111_184735.pkl
  Model: svr
  Target: memory_usage_pct
  Saved at: 2025-11-11 18:47:35
Latest model: models\random_forest_system_load_20251111_221944.pkl
✓ Model loaded: models\random_forest_system_load_20251111_221944.pkl
  Model: random_forest
  Target: system_load
  Saved at: 2025-11-11 22:19:44
Loaded model from E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\rl_models\ppo_cost.zip

Running PPO rollout for scenario: cost
Latest model: models\random_forest_cpu_total_usage_20251111_221930.pkl
✓ Model loaded: models\random_forest_cpu_total_usage_20251111_221930.pkl
  Model: random_forest
  Target: cpu_total_usage
  Saved at: 2025-11-11 22:19:30
Latest model: models\svr_memory_usage_pct_20251111_184735.pkl
✓ Model loaded: models\svr_memory_usage_pct_20251111_184735.pkl
  Model: svr
  Target: memory_usage_pct
  Saved at: 2025-11-11 18:47:35
Latest model: models\random_forest_system_load_20251111_221944.pkl
✓ Model loaded: models\random_forest_system_load_20251111_221944.pkl
  Model: random_forest
  Target: system_load
  Saved at: 2025-11-11 22:19:44
PPO schedule saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\forecast_result\ppo_schedule_test_cost.csv
PPO 30min bucket saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\forecast_result\ppo_schedule_30min_cost.csv
Warning: LP schedule not found at E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\forecast_result\vm_schedule.csv
Run 'python vm_resource_planner.py' first to generate baseline.

============================================================
RESULTS: COST
============================================================

PPO Performance:
  Total VM Cost: $101.2704
  Total Switching Cost: $16.2300
  Total Cost: $117.5004
  SLA Violations: 174 (1.0%)
  Mean CPU Utilization: 1.1%
  Mean Memory Utilization: 0.0%

✅ Evaluation complete!
📁 Results saved to: results/ppo_schedule_test_*.csv

{'overload': {'scenario': 'overload',
  'timestamp': '2025-12-17 09:58:40',
  'ppo': {'total_vm_cost': 185.32479999999998,
   'total_switching_cost': 20.8,
   'total_cost': 206.12479999999996,
   'sla_violations': 5,
   'sla_violation_rate': 0.0002915451895043732,
   'mean_cpu_utilization': 0.14487595033549622,
   'mean_mem_utilization': 0.0,
   'n_steps': 17150},
  'ppo_30min': {'total_vm_cost': 0.0,
   'total_switching_cost': 0.0,
   'total_cost': 0.0,
   'sla_violations': 5,
   'sla_violation_rate': 0.00029036004645760743,
   'n_buckets': 287}},
 'cost': {'scenario': 'cost',
  'timestamp': '2025-12-17 10:00:40',
  'ppo': {'total_vm_cost': 101.2704,
   'total_switching_cost': 16.23,
   'total_cost': 117.50039999999998,
   'sla_violations': 174,
   'sla_violation_rate': 0.010145772594752186,
   'mean_cpu_utilization': 1.1174137403722844,
   'mean_mem_utilization': 0.0,
   'n_steps': 17150},
  'ppo_30min': {'total_vm_cost': 0.0,
   'total_switching_cost': 0.0,
   'total_cost': 0.0,
   'sla_violations': 174,
   'sla_violation_rate': 0.01010452961672474,
   'n_buckets': 287}}}

In [5]:
# Inspect generated PPO schedules (PER-STEP results)

import pandas as pd
import numpy as np
from pathlib import Path

RESULTS_DIR = Path("forecast_result")

# Load PPO per-step schedules
ppo_overload_path = RESULTS_DIR / "ppo_schedule_test_overload.csv"
ppo_cost_path = RESULTS_DIR / "ppo_schedule_test_cost.csv"

print("=== PPO Per-Step Schedules ===")
print(f"PPO overload: {ppo_overload_path.exists()}")
print(f"PPO cost: {ppo_cost_path.exists()}")

ppo_overload_df = pd.read_csv(ppo_overload_path) if ppo_overload_path.exists() else None
ppo_cost_df = pd.read_csv(ppo_cost_path) if ppo_cost_path.exists() else None

if ppo_overload_df is not None:
    print(f"\nPPO Overload: {len(ppo_overload_df)} steps")
    display(ppo_overload_df.head(10))

if ppo_cost_df is not None:
    print(f"\nPPO Cost: {len(ppo_cost_df)} steps")
    display(ppo_cost_df.head(10))

=== PPO Per-Step Schedules ===
PPO overload: True
PPO cost: True

PPO Overload: 17150 steps

,timestamp,allocation,vm_cost_per_hour,switching_cost,total_cost_per_hour,cpu_allocated_cores,mem_allocated_gb,cpu_vm_only,mem_vm_only,cpu_required_cores,mem_required_gb,cpu_overflow_cores,mem_overflow_gb,cpu_utilization_pct,mem_utilization_pct,sla_violation_flag
0,1970-01-25 01:05:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.24,0.258175,0.0,0,0.0,0.0,0
1,1970-01-25 01:06:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.22,0.258186,0.0,0,0.0,0.0,0
2,1970-01-25 01:06:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.13,0.258044,0.0,0,0.0,0.0,0
3,1970-01-25 01:07:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.08,0.257840,0.0,0,0.0,0.0,0
4,1970-01-25 01:07:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.10,0.258327,0.0,0,0.0,0.0,0
5,1970-01-25 01:08:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.23,0.258050,0.0,0,0.0,0.0,0
6,1970-01-25 01:08:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.14,0.258136,0.0,0,0.0,0.0,0
7,1970-01-25 01:09:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.21,0.258079,0.0,0,0.0,0.0,0
8,1970-01-25 01:09:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.12,0.258266,0.0,0,0.0,0.0,0
9,1970-01-25 01:10:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.07,0.258260,0.0,0,0.0,0.0,0

PPO Cost: 17150 steps

,timestamp,allocation,vm_cost_per_hour,switching_cost,total_cost_per_hour,cpu_allocated_cores,mem_allocated_gb,cpu_vm_only,mem_vm_only,cpu_required_cores,mem_required_gb,cpu_overflow_cores,mem_overflow_gb,cpu_utilization_pct,mem_utilization_pct,sla_violation_flag
0,1970-01-25 01:05:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.24,0.258175,0.0,0,0.0,0.0,0
1,1970-01-25 01:06:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.22,0.258186,0.0,0,0.0,0.0,0
2,1970-01-25 01:06:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.13,0.258044,0.0,0,0.0,0.0,0
3,1970-01-25 01:07:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.08,0.257840,0.0,0,0.0,0.0,0
4,1970-01-25 01:07:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.10,0.258327,0.0,0,0.0,0.0,0
5,1970-01-25 01:08:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.23,0.258050,0.0,0,0.0,0.0,0
6,1970-01-25 01:08:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.14,0.258136,0.0,0,0.0,0.0,0
7,1970-01-25 01:09:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.21,0.258079,0.0,0,0.0,0.0,0
8,1970-01-25 01:09:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.12,0.258266,0.0,0,0.0,0.0,0
9,1970-01-25 01:10:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.07,0.258260,0.0,0,0.0,0.0,0