# PPO VM Allocation Experiments

This notebook trains and evaluates PPO agents for VM allocation using the existing DRL pipeline:

- `rl/environment.py`: `VMAllocationEnv` (Gymnasium environment)
- `rl/config.py`: PPO and reward configuration
- `train_ppo.py`: training script
- `eval_ppo.py`: evaluation script

You can use this notebook to:
- Run quick training experiments (e.g., smaller `total_timesteps`)
- Evaluate PPO and inspect per-step schedules and metrics

**Note**: LP vs PPO comparison is done in `lp_vs_ppo_comparison.ipynb`.

In [1]:
# Imports and configuration

from pathlib import Path

# Module imports
import importlib
import train_ppo as train_ppo_module
import eval_ppo as eval_ppo_module
import rl.config as rl_config_module

from rl.config import PPOConfig, SCENARIO_OVERLOAD, SCENARIO_COST
from train_ppo import train_ppo
from eval_ppo import evaluate_scenario, print_comparison

# Reload modules to pick up latest code when notebook stays open
importlib.reload(train_ppo_module)
importlib.reload(eval_ppo_module)
importlib.reload(rl_config_module)

# Refresh config after reload
from rl.config import PPOConfig, SCENARIO_OVERLOAD, SCENARIO_COST

PROJECT_ROOT = Path.cwd()
print("Project root:", PROJECT_ROOT)

# Show current default PPO configuration
config = PPOConfig()
config

Project root: e:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure

PPOConfig(learning_rate=0.0003, n_steps=2048, batch_size=64, n_epochs=10, gamma=0.99, gae_lambda=0.95, clip_range=0.2, clip_range_vf=None, ent_coef=0.01, vf_coef=0.5, max_grad_norm=0.5, episode_length=480, horizon=120, total_timesteps=1000000, tensorboard_log='./tensorboard_logs/', log_interval=10, save_freq=10000)

In [2]:
# Configuration (for training or evaluation)
from copy import deepcopy

# Number of parallel envs (increase if you have CPU/GPU resources)
N_ENVS = 8

exp_config = deepcopy(config)

# Training settings (if you want to train)
exp_config.total_timesteps = 1_000_000

# Episode length for evaluation:
# - 480 = 4 hours (default, same as training)
# - 17150 = full test set (~6 days)
exp_config.episode_length = 17150  # evaluate full test set

print("Configuration:")
print("  total_timesteps =", exp_config.total_timesteps, "(for training)")
print("  episode_length  =", exp_config.episode_length, "steps (for evaluation)")
print("  n_envs          =", N_ENVS)

Configuration:
  total_timesteps = 1000000 (for training)
  episode_length  = 17150 steps (for evaluation)
  n_envs          = 8

In [3]:

print("Training configuration:")
print("  total_timesteps =", exp_config.total_timesteps)
print("  episode_length  =", exp_config.episode_length)
print("  horizon         =", exp_config.horizon)
print("  n_envs          =", N_ENVS)

# Train overload-first scenario
model_overload = train_ppo(
    scenario=SCENARIO_OVERLOAD,
    config=exp_config,
    total_timesteps=exp_config.total_timesteps,
    n_envs=N_ENVS,
    continue_training=False,
)

# Train cost-first scenario
model_cost = train_ppo(
    scenario=SCENARIO_COST,
    config=exp_config,
    total_timesteps=exp_config.total_timesteps,
    n_envs=N_ENVS,
    continue_training=False,
)

Training configuration:
  total_timesteps = 1000000
  episode_length  = 17150
  horizon         = 120
  n_envs          = 8

============================================================
Training PPO for scenario: OVERLOAD
============================================================
Latest model: models\random_forest_cpu_total_usage_20251111_221930.pkl
✓ Model loaded: models\random_forest_cpu_total_usage_20251111_221930.pkl
  Model: random_forest
  Target: cpu_total_usage
  Saved at: 2025-11-11 22:19:30
Latest model: models\svr_memory_usage_pct_20251111_184735.pkl
✓ Model loaded: models\svr_memory_usage_pct_20251111_184735.pkl
  Model: svr
  Target: memory_usage_pct
  Saved at: 2025-11-11 18:47:35
Latest model: models\random_forest_system_load_20251111_221944.pkl
✓ Model loaded: models\random_forest_system_load_20251111_221944.pkl
  Model: random_forest
  Target: system_load
  Saved at: 2025-11-11 22:19:44
Creating new PPO model
Using cpu device

Starting training for 1,000,000 timesteps...
Logging to ./tensorboard_logs/PPO_11

Output()

------------------------------
| time/              |       |
|    fps             | 101   |
|    iterations      | 1     |
|    time_elapsed    | 161   |
|    total_timesteps | 16384 |
------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 104         |
|    iterations           | 2           |
|    time_elapsed         | 314         |
|    total_timesteps      | 32768       |
| train/                  |             |
|    approx_kl            | 0.031307638 |
|    clip_fraction        | 0.275       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.57       |
|    explained_variance   | 0.267       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.0172      |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0524     |
|    value_loss           | 0.153       |
-----------------------------------------

----------------------------------------
| time/                   |            |
|    fps                  | 107        |
|    iterations           | 3          |
|    time_elapsed         | 459        |
|    total_timesteps      | 49152      |
| train/                  |            |
|    approx_kl            | 0.03115097 |
|    clip_fraction        | 0.323      |
|    clip_range           | 0.2        |
|    entropy_loss         | -9.54      |
|    explained_variance   | 0.61       |
|    learning_rate        | 0.0003     |
|    loss                 | -0.15      |
|    n_updates            | 20         |
|    policy_gradient_loss | -0.0648    |
|    value_loss           | 0.0523     |
----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 108         |
|    iterations           | 4           |
|    time_elapsed         | 603         |
|    total_timesteps      | 65536       |
| train/                  |             |
|    approx_kl            | 0.033187386 |
|    clip_fraction        | 0.362       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.49       |
|    explained_variance   | 0.707       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.178      |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.0683     |
|    value_loss           | 0.0391      |
-----------------------------------------

Eval num_timesteps=80000, episode_reward=-1124869.72 +/- 0.00

Episode length: 17150.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.72e+04    |
|    mean_reward          | -1.12e+06   |
| time/                   |             |
|    total_timesteps      | 80000       |
| train/                  |             |
|    approx_kl            | 0.037628636 |
|    clip_fraction        | 0.394       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.43       |
|    explained_variance   | 0.76        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.176      |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.073      |
|    value_loss           | 0.0324      |
-----------------------------------------

New best mean reward!

------------------------------
| time/              |       |
|    fps             | 96    |
|    iterations      | 5     |
|    time_elapsed    | 848   |
|    total_timesteps | 81920 |
------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 98          |
|    iterations           | 6           |
|    time_elapsed         | 993         |
|    total_timesteps      | 98304       |
| train/                  |             |
|    approx_kl            | 0.038650878 |
|    clip_fraction        | 0.402       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.35       |
|    explained_variance   | 0.788       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.163      |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.0732     |
|    value_loss           | 0.0247      |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 7           |
|    time_elapsed         | 1146        |
|    total_timesteps      | 114688      |
| train/                  |             |
|    approx_kl            | 0.040836144 |
|    clip_fraction        | 0.419       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.28       |
|    explained_variance   | 0.802       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.16       |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.0755     |
|    value_loss           | 0.0213      |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 101         |
|    iterations           | 8           |
|    time_elapsed         | 1292        |
|    total_timesteps      | 131072      |
| train/                  |             |
|    approx_kl            | 0.044555195 |
|    clip_fraction        | 0.431       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.2        |
|    explained_variance   | 0.811       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.207      |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.0797     |
|    value_loss           | 0.0173      |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -4.55e+06   |
| time/                   |             |
|    fps                  | 102         |
|    iterations           | 9           |
|    time_elapsed         | 1436        |
|    total_timesteps      | 147456      |
| train/                  |             |
|    approx_kl            | 0.043919444 |
|    clip_fraction        | 0.431       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.1        |
|    explained_variance   | 0.821       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.181      |
|    n_updates            | 80          |
|    policy_gradient_loss | -0.0772     |
|    value_loss           | 0.0128      |
-----------------------------------------

Eval num_timesteps=160000, episode_reward=-1156107.72 +/- 0.00

Episode length: 17150.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.72e+04    |
|    mean_reward          | -1.16e+06   |
| time/                   |             |
|    total_timesteps      | 160000      |
| train/                  |             |
|    approx_kl            | 0.043315068 |
|    clip_fraction        | 0.428       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.98       |
|    explained_variance   | 0.88        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.172      |
|    n_updates            | 90          |
|    policy_gradient_loss | -0.0741     |
|    value_loss           | 0.0118      |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -4.55e+06 |
| time/              |           |
|    fps             | 97        |
|    iterations      | 10        |
|    time_elapsed    | 1680      |
|    total_timesteps | 163840    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -4.55e+06   |
| time/                   |             |
|    fps                  | 99          |
|    iterations           | 11          |
|    time_elapsed         | 1819        |
|    total_timesteps      | 180224      |
| train/                  |             |
|    approx_kl            | 0.047616504 |
|    clip_fraction        | 0.44        |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.92       |
|    explained_variance   | 0.895       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.208      |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.0777     |
|    value_loss           | 0.00884     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -4.55e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 12          |
|    time_elapsed         | 1960        |
|    total_timesteps      | 196608      |
| train/                  |             |
|    approx_kl            | 0.047744393 |
|    clip_fraction        | 0.443       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.81       |
|    explained_variance   | 0.918       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.166      |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.077      |
|    value_loss           | 0.00723     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -4.55e+06  |
| time/                   |            |
|    fps                  | 100        |
|    iterations           | 13         |
|    time_elapsed         | 2120       |
|    total_timesteps      | 212992     |
| train/                  |            |
|    approx_kl            | 0.04885629 |
|    clip_fraction        | 0.442      |
|    clip_range           | 0.2        |
|    entropy_loss         | -8.7       |
|    explained_variance   | 0.904      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.193     |
|    n_updates            | 120        |
|    policy_gradient_loss | -0.0759    |
|    value_loss           | 0.00679    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -4.55e+06   |
| time/                   |             |
|    fps                  | 101         |
|    iterations           | 14          |
|    time_elapsed         | 2265        |
|    total_timesteps      | 229376      |
| train/                  |             |
|    approx_kl            | 0.050534055 |
|    clip_fraction        | 0.456       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.63       |
|    explained_variance   | 0.914       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.182      |
|    n_updates            | 130         |
|    policy_gradient_loss | -0.0791     |
|    value_loss           | 0.00579     |
-----------------------------------------

Eval num_timesteps=240000, episode_reward=-919701.03 +/- 0.00

Episode length: 17150.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.72e+04    |
|    mean_reward          | -9.2e+05    |
| time/                   |             |
|    total_timesteps      | 240000      |
| train/                  |             |
|    approx_kl            | 0.053580016 |
|    clip_fraction        | 0.455       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.53       |
|    explained_variance   | 0.909       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.178      |
|    n_updates            | 140         |
|    policy_gradient_loss | -0.0781     |
|    value_loss           | 0.00517     |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -4.55e+06 |
| time/              |           |
|    fps             | 98        |
|    iterations      | 15        |
|    time_elapsed    | 2506      |
|    total_timesteps | 245760    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -4.55e+06   |
| time/                   |             |
|    fps                  | 98          |
|    iterations           | 16          |
|    time_elapsed         | 2649        |
|    total_timesteps      | 262144      |
| train/                  |             |
|    approx_kl            | 0.051575623 |
|    clip_fraction        | 0.46        |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.37       |
|    explained_variance   | 0.928       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.205      |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.0767     |
|    value_loss           | 0.00458     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -3.74e+06   |
| time/                   |             |
|    fps                  | 99          |
|    iterations           | 17          |
|    time_elapsed         | 2792        |
|    total_timesteps      | 278528      |
| train/                  |             |
|    approx_kl            | 0.051432423 |
|    clip_fraction        | 0.453       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.24       |
|    explained_variance   | 0.926       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.16       |
|    n_updates            | 160         |
|    policy_gradient_loss | -0.0728     |
|    value_loss           | 0.00414     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -3.74e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 18          |
|    time_elapsed         | 2936        |
|    total_timesteps      | 294912      |
| train/                  |             |
|    approx_kl            | 0.053001106 |
|    clip_fraction        | 0.455       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.15       |
|    explained_variance   | 0.933       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.197      |
|    n_updates            | 170         |
|    policy_gradient_loss | -0.0774     |
|    value_loss           | 0.00334     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -3.74e+06   |
| time/                   |             |
|    fps                  | 101         |
|    iterations           | 19          |
|    time_elapsed         | 3079        |
|    total_timesteps      | 311296      |
| train/                  |             |
|    approx_kl            | 0.053280167 |
|    clip_fraction        | 0.459       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.05       |
|    explained_variance   | 0.938       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.182      |
|    n_updates            | 180         |
|    policy_gradient_loss | -0.0777     |
|    value_loss           | 0.0033      |
-----------------------------------------

Eval num_timesteps=320000, episode_reward=-642127.17 +/- 0.00

Episode length: 17150.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.72e+04    |
|    mean_reward          | -6.42e+05   |
| time/                   |             |
|    total_timesteps      | 320000      |
| train/                  |             |
|    approx_kl            | 0.050184954 |
|    clip_fraction        | 0.444       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.86       |
|    explained_variance   | 0.946       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.187      |
|    n_updates            | 190         |
|    policy_gradient_loss | -0.0693     |
|    value_loss           | 0.00272     |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -3.74e+06 |
| time/              |           |
|    fps             | 98        |
|    iterations      | 20        |
|    time_elapsed    | 3318      |
|    total_timesteps | 327680    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -3.74e+06  |
| time/                   |            |
|    fps                  | 99         |
|    iterations           | 21         |
|    time_elapsed         | 3460       |
|    total_timesteps      | 344064     |
| train/                  |            |
|    approx_kl            | 0.05394958 |
|    clip_fraction        | 0.45       |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.84      |
|    explained_variance   | 0.919      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.185     |
|    n_updates            | 200        |
|    policy_gradient_loss | -0.0759    |
|    value_loss           | 0.00254    |
----------------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 1.72e+04  |
|    ep_rew_mean          | -3.74e+06 |
| time/                   |           |
|    fps                  | 100       |
|    iterations           | 22        |
|    time_elapsed         | 3602      |
|    total_timesteps      | 360448    |
| train/                  |           |
|    approx_kl            | 0.0539239 |
|    clip_fraction        | 0.449     |
|    clip_range           | 0.2       |
|    entropy_loss         | -7.74     |
|    explained_variance   | 0.937     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.181    |
|    n_updates            | 210       |
|    policy_gradient_loss | -0.0719   |
|    value_loss           | 0.00224   |
---------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -3.74e+06  |
| time/                   |            |
|    fps                  | 100        |
|    iterations           | 23         |
|    time_elapsed         | 3743       |
|    total_timesteps      | 376832     |
| train/                  |            |
|    approx_kl            | 0.05120954 |
|    clip_fraction        | 0.441      |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.59      |
|    explained_variance   | 0.925      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.167     |
|    n_updates            | 220        |
|    policy_gradient_loss | -0.0696    |
|    value_loss           | 0.00204    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -3.74e+06   |
| time/                   |             |
|    fps                  | 101         |
|    iterations           | 24          |
|    time_elapsed         | 3886        |
|    total_timesteps      | 393216      |
| train/                  |             |
|    approx_kl            | 0.054338083 |
|    clip_fraction        | 0.449       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.52       |
|    explained_variance   | 0.951       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.189      |
|    n_updates            | 230         |
|    policy_gradient_loss | -0.0737     |
|    value_loss           | 0.00179     |
-----------------------------------------

Eval num_timesteps=400000, episode_reward=-1414856.46 +/- 0.00

Episode length: 17150.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.72e+04    |
|    mean_reward          | -1.41e+06   |
| time/                   |             |
|    total_timesteps      | 400000      |
| train/                  |             |
|    approx_kl            | 0.055134818 |
|    clip_fraction        | 0.459       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.47       |
|    explained_variance   | 0.939       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.156      |
|    n_updates            | 240         |
|    policy_gradient_loss | -0.0728     |
|    value_loss           | 0.00175     |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -3.74e+06 |
| time/              |           |
|    fps             | 99        |
|    iterations      | 25        |
|    time_elapsed    | 4125      |
|    total_timesteps | 409600    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -3.12e+06   |
| time/                   |             |
|    fps                  | 99          |
|    iterations           | 26          |
|    time_elapsed         | 4267        |
|    total_timesteps      | 425984      |
| train/                  |             |
|    approx_kl            | 0.055575214 |
|    clip_fraction        | 0.457       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.35       |
|    explained_variance   | 0.919       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.162      |
|    n_updates            | 250         |
|    policy_gradient_loss | -0.0713     |
|    value_loss           | 0.00163     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -3.12e+06  |
| time/                   |            |
|    fps                  | 100        |
|    iterations           | 27         |
|    time_elapsed         | 4408       |
|    total_timesteps      | 442368     |
| train/                  |            |
|    approx_kl            | 0.04890314 |
|    clip_fraction        | 0.43       |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.11      |
|    explained_variance   | 0.939      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.173     |
|    n_updates            | 260        |
|    policy_gradient_loss | -0.0623    |
|    value_loss           | 0.00131    |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -3.12e+06  |
| time/                   |            |
|    fps                  | 100        |
|    iterations           | 28         |
|    time_elapsed         | 4550       |
|    total_timesteps      | 458752     |
| train/                  |            |
|    approx_kl            | 0.05834821 |
|    clip_fraction        | 0.461      |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.15      |
|    explained_variance   | 0.936      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.183     |
|    n_updates            | 270        |
|    policy_gradient_loss | -0.0735    |
|    value_loss           | 0.00134    |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -3.12e+06  |
| time/                   |            |
|    fps                  | 101        |
|    iterations           | 29         |
|    time_elapsed         | 4692       |
|    total_timesteps      | 475136     |
| train/                  |            |
|    approx_kl            | 0.05992679 |
|    clip_fraction        | 0.461      |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.09      |
|    explained_variance   | 0.921      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.151     |
|    n_updates            | 280        |
|    policy_gradient_loss | -0.0759    |
|    value_loss           | 0.00134    |
----------------------------------------

Eval num_timesteps=480000, episode_reward=-1559655.78 +/- 0.00

Episode length: 17150.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.72e+04    |
|    mean_reward          | -1.56e+06   |
| time/                   |             |
|    total_timesteps      | 480000      |
| train/                  |             |
|    approx_kl            | 0.054439984 |
|    clip_fraction        | 0.444       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.94       |
|    explained_variance   | 0.935       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.176      |
|    n_updates            | 290         |
|    policy_gradient_loss | -0.0675     |
|    value_loss           | 0.00119     |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -3.12e+06 |
| time/              |           |
|    fps             | 99        |
|    iterations      | 30        |
|    time_elapsed    | 4932      |
|    total_timesteps | 491520    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -3.12e+06  |
| time/                   |            |
|    fps                  | 100        |
|    iterations           | 31         |
|    time_elapsed         | 5075       |
|    total_timesteps      | 507904     |
| train/                  |            |
|    approx_kl            | 0.05999849 |
|    clip_fraction        | 0.467      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.99      |
|    explained_variance   | 0.863      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.177     |
|    n_updates            | 300        |
|    policy_gradient_loss | -0.0732    |
|    value_loss           | 0.00132    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -3.12e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 32          |
|    time_elapsed         | 5217        |
|    total_timesteps      | 524288      |
| train/                  |             |
|    approx_kl            | 0.059935294 |
|    clip_fraction        | 0.461       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.87       |
|    explained_variance   | 0.908       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.188      |
|    n_updates            | 310         |
|    policy_gradient_loss | -0.0716     |
|    value_loss           | 0.00107     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -3.12e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 33          |
|    time_elapsed         | 5359        |
|    total_timesteps      | 540672      |
| train/                  |             |
|    approx_kl            | 0.057314105 |
|    clip_fraction        | 0.453       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.78       |
|    explained_variance   | 0.882       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.166      |
|    n_updates            | 320         |
|    policy_gradient_loss | -0.073      |
|    value_loss           | 0.000993    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.66e+06   |
| time/                   |             |
|    fps                  | 101         |
|    iterations           | 34          |
|    time_elapsed         | 5502        |
|    total_timesteps      | 557056      |
| train/                  |             |
|    approx_kl            | 0.058123067 |
|    clip_fraction        | 0.458       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.68       |
|    explained_variance   | 0.892       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.146      |
|    n_updates            | 330         |
|    policy_gradient_loss | -0.0676     |
|    value_loss           | 0.00101     |
-----------------------------------------

Eval num_timesteps=560000, episode_reward=-1999805.26 +/- 0.00

Episode length: 17150.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.72e+04   |
|    mean_reward          | -2e+06     |
| time/                   |            |
|    total_timesteps      | 560000     |
| train/                  |            |
|    approx_kl            | 0.05807098 |
|    clip_fraction        | 0.466      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.53      |
|    explained_variance   | 0.855      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.161     |
|    n_updates            | 340        |
|    policy_gradient_loss | -0.0702    |
|    value_loss           | 0.000731   |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -2.66e+06 |
| time/              |           |
|    fps             | 99        |
|    iterations      | 35        |
|    time_elapsed    | 5740      |
|    total_timesteps | 573440    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.66e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 36          |
|    time_elapsed         | 5882        |
|    total_timesteps      | 589824      |
| train/                  |             |
|    approx_kl            | 0.057183146 |
|    clip_fraction        | 0.458       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.51       |
|    explained_variance   | 0.803       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.194      |
|    n_updates            | 350         |
|    policy_gradient_loss | -0.0724     |
|    value_loss           | 0.000743    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.66e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 37          |
|    time_elapsed         | 6024        |
|    total_timesteps      | 606208      |
| train/                  |             |
|    approx_kl            | 0.057215024 |
|    clip_fraction        | 0.466       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.28       |
|    explained_variance   | 0.856       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.172      |
|    n_updates            | 360         |
|    policy_gradient_loss | -0.0705     |
|    value_loss           | 0.000532    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.66e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 38          |
|    time_elapsed         | 6166        |
|    total_timesteps      | 622592      |
| train/                  |             |
|    approx_kl            | 0.060681686 |
|    clip_fraction        | 0.462       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.22       |
|    explained_variance   | 0.844       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.172      |
|    n_updates            | 370         |
|    policy_gradient_loss | -0.0688     |
|    value_loss           | 0.000552    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -2.66e+06  |
| time/                   |            |
|    fps                  | 101        |
|    iterations           | 39         |
|    time_elapsed         | 6307       |
|    total_timesteps      | 638976     |
| train/                  |            |
|    approx_kl            | 0.05659768 |
|    clip_fraction        | 0.456      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.12      |
|    explained_variance   | 0.861      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.142     |
|    n_updates            | 380        |
|    policy_gradient_loss | -0.0636    |
|    value_loss           | 0.000577   |
----------------------------------------

Eval num_timesteps=640000, episode_reward=-1952849.84 +/- 0.00

Episode length: 17150.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.72e+04    |
|    mean_reward          | -1.95e+06   |
| time/                   |             |
|    total_timesteps      | 640000      |
| train/                  |             |
|    approx_kl            | 0.059909046 |
|    clip_fraction        | 0.45        |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.13       |
|    explained_variance   | 0.848       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.162      |
|    n_updates            | 390         |
|    policy_gradient_loss | -0.0599     |
|    value_loss           | 0.000639    |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -2.66e+06 |
| time/              |           |
|    fps             | 100       |
|    iterations      | 40        |
|    time_elapsed    | 6546      |
|    total_timesteps | 655360    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.66e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 41          |
|    time_elapsed         | 6689        |
|    total_timesteps      | 671744      |
| train/                  |             |
|    approx_kl            | 0.061728038 |
|    clip_fraction        | 0.456       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.11       |
|    explained_variance   | 0.882       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.165      |
|    n_updates            | 400         |
|    policy_gradient_loss | -0.0654     |
|    value_loss           | 0.000589    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.32e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 42          |
|    time_elapsed         | 6833        |
|    total_timesteps      | 688128      |
| train/                  |             |
|    approx_kl            | 0.060738254 |
|    clip_fraction        | 0.461       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.05       |
|    explained_variance   | 0.875       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.129      |
|    n_updates            | 410         |
|    policy_gradient_loss | -0.0598     |
|    value_loss           | 0.000565    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.32e+06   |
| time/                   |             |
|    fps                  | 101         |
|    iterations           | 43          |
|    time_elapsed         | 6974        |
|    total_timesteps      | 704512      |
| train/                  |             |
|    approx_kl            | 0.056908667 |
|    clip_fraction        | 0.441       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.93       |
|    explained_variance   | 0.903       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.105      |
|    n_updates            | 420         |
|    policy_gradient_loss | -0.0597     |
|    value_loss           | 0.000452    |
-----------------------------------------

Eval num_timesteps=720000, episode_reward=-1933519.12 +/- 0.00

Episode length: 17150.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.72e+04    |
|    mean_reward          | -1.93e+06   |
| time/                   |             |
|    total_timesteps      | 720000      |
| train/                  |             |
|    approx_kl            | 0.061003238 |
|    clip_fraction        | 0.47        |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.8        |
|    explained_variance   | 0.858       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.176      |
|    n_updates            | 430         |
|    policy_gradient_loss | -0.0735     |
|    value_loss           | 0.000427    |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -2.32e+06 |
| time/              |           |
|    fps             | 99        |
|    iterations      | 44        |
|    time_elapsed    | 7212      |
|    total_timesteps | 720896    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.32e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 45          |
|    time_elapsed         | 7354        |
|    total_timesteps      | 737280      |
| train/                  |             |
|    approx_kl            | 0.061917238 |
|    clip_fraction        | 0.469       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.61       |
|    explained_variance   | 0.88        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.136      |
|    n_updates            | 440         |
|    policy_gradient_loss | -0.0715     |
|    value_loss           | 0.000329    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.32e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 46          |
|    time_elapsed         | 7497        |
|    total_timesteps      | 753664      |
| train/                  |             |
|    approx_kl            | 0.054590564 |
|    clip_fraction        | 0.444       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.58       |
|    explained_variance   | 0.847       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.159      |
|    n_updates            | 450         |
|    policy_gradient_loss | -0.065      |
|    value_loss           | 0.000329    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.32e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 47          |
|    time_elapsed         | 7640        |
|    total_timesteps      | 770048      |
| train/                  |             |
|    approx_kl            | 0.062301666 |
|    clip_fraction        | 0.457       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.58       |
|    explained_variance   | 0.86        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.142      |
|    n_updates            | 460         |
|    policy_gradient_loss | -0.07       |
|    value_loss           | 0.000417    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -2.32e+06  |
| time/                   |            |
|    fps                  | 101        |
|    iterations           | 48         |
|    time_elapsed         | 7782       |
|    total_timesteps      | 786432     |
| train/                  |            |
|    approx_kl            | 0.06188401 |
|    clip_fraction        | 0.46       |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.42      |
|    explained_variance   | 0.884      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.153     |
|    n_updates            | 470        |
|    policy_gradient_loss | -0.0724    |
|    value_loss           | 0.000286   |
----------------------------------------

Eval num_timesteps=800000, episode_reward=-1702589.77 +/- 0.00

Episode length: 17150.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.72e+04   |
|    mean_reward          | -1.7e+06   |
| time/                   |            |
|    total_timesteps      | 800000     |
| train/                  |            |
|    approx_kl            | 0.06272963 |
|    clip_fraction        | 0.461      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.37      |
|    explained_variance   | 0.897      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.138     |
|    n_updates            | 480        |
|    policy_gradient_loss | -0.0713    |
|    value_loss           | 0.000297   |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -2.32e+06 |
| time/              |           |
|    fps             | 100       |
|    iterations      | 49        |
|    time_elapsed    | 8020      |
|    total_timesteps | 802816    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.32e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 50          |
|    time_elapsed         | 8162        |
|    total_timesteps      | 819200      |
| train/                  |             |
|    approx_kl            | 0.058974627 |
|    clip_fraction        | 0.445       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.32       |
|    explained_variance   | 0.902       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.17       |
|    n_updates            | 490         |
|    policy_gradient_loss | -0.0685     |
|    value_loss           | 0.000261    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -2.04e+06  |
| time/                   |            |
|    fps                  | 100        |
|    iterations           | 51         |
|    time_elapsed         | 8304       |
|    total_timesteps      | 835584     |
| train/                  |            |
|    approx_kl            | 0.05878009 |
|    clip_fraction        | 0.441      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.29      |
|    explained_variance   | 0.798      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.133     |
|    n_updates            | 500        |
|    policy_gradient_loss | -0.0475    |
|    value_loss           | 0.000315   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -2.04e+06  |
| time/                   |            |
|    fps                  | 100        |
|    iterations           | 52         |
|    time_elapsed         | 8448       |
|    total_timesteps      | 851968     |
| train/                  |            |
|    approx_kl            | 0.05897137 |
|    clip_fraction        | 0.443      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.14      |
|    explained_variance   | 0.897      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.142     |
|    n_updates            | 510        |
|    policy_gradient_loss | -0.0658    |
|    value_loss           | 0.000229   |
----------------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 1.72e+04  |
|    ep_rew_mean          | -2.04e+06 |
| time/                   |           |
|    fps                  | 101       |
|    iterations           | 53        |
|    time_elapsed         | 8590      |
|    total_timesteps      | 868352    |
| train/                  |           |
|    approx_kl            | 0.0591726 |
|    clip_fraction        | 0.437     |
|    clip_range           | 0.2       |
|    entropy_loss         | -5.08     |
|    explained_variance   | 0.907     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.119    |
|    n_updates            | 520       |
|    policy_gradient_loss | -0.068    |
|    value_loss           | 0.000194  |
---------------------------------------

Eval num_timesteps=880000, episode_reward=-1294351.61 +/- 0.00

Episode length: 17150.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.72e+04   |
|    mean_reward          | -1.29e+06  |
| time/                   |            |
|    total_timesteps      | 880000     |
| train/                  |            |
|    approx_kl            | 0.05845734 |
|    clip_fraction        | 0.438      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.97      |
|    explained_variance   | 0.899      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.134     |
|    n_updates            | 530        |
|    policy_gradient_loss | -0.0671    |
|    value_loss           | 0.000203   |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -2.04e+06 |
| time/              |           |
|    fps             | 100       |
|    iterations      | 54        |
|    time_elapsed    | 8828      |
|    total_timesteps | 884736    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.04e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 55          |
|    time_elapsed         | 8970        |
|    total_timesteps      | 901120      |
| train/                  |             |
|    approx_kl            | 0.065239996 |
|    clip_fraction        | 0.451       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.06       |
|    explained_variance   | 0.909       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.112      |
|    n_updates            | 540         |
|    policy_gradient_loss | -0.0594     |
|    value_loss           | 0.000314    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.04e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 56          |
|    time_elapsed         | 9112        |
|    total_timesteps      | 917504      |
| train/                  |             |
|    approx_kl            | 0.059762947 |
|    clip_fraction        | 0.419       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.01       |
|    explained_variance   | 0.905       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.112      |
|    n_updates            | 550         |
|    policy_gradient_loss | -0.06       |
|    value_loss           | 0.000306    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.04e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 57          |
|    time_elapsed         | 9255        |
|    total_timesteps      | 933888      |
| train/                  |             |
|    approx_kl            | 0.062067673 |
|    clip_fraction        | 0.442       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.95       |
|    explained_variance   | 0.93        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.107      |
|    n_updates            | 560         |
|    policy_gradient_loss | -0.0662     |
|    value_loss           | 0.000344    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -2.04e+06  |
| time/                   |            |
|    fps                  | 101        |
|    iterations           | 58         |
|    time_elapsed         | 9397       |
|    total_timesteps      | 950272     |
| train/                  |            |
|    approx_kl            | 0.06297711 |
|    clip_fraction        | 0.449      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.97      |
|    explained_variance   | 0.919      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.146     |
|    n_updates            | 570        |
|    policy_gradient_loss | -0.0695    |
|    value_loss           | 0.000306   |
----------------------------------------

Eval num_timesteps=960000, episode_reward=-1146734.34 +/- 0.00

Episode length: 17150.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.72e+04    |
|    mean_reward          | -1.15e+06   |
| time/                   |             |
|    total_timesteps      | 960000      |
| train/                  |             |
|    approx_kl            | 0.068610646 |
|    clip_fraction        | 0.453       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.12       |
|    explained_variance   | 0.945       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.134      |
|    n_updates            | 580         |
|    policy_gradient_loss | -0.0667     |
|    value_loss           | 0.000448    |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -1.83e+06 |
| time/              |           |
|    fps             | 100       |
|    iterations      | 59        |
|    time_elapsed    | 9636      |
|    total_timesteps | 966656    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -1.83e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 60          |
|    time_elapsed         | 9777        |
|    total_timesteps      | 983040      |
| train/                  |             |
|    approx_kl            | 0.063602395 |
|    clip_fraction        | 0.433       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.88       |
|    explained_variance   | 0.956       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.125      |
|    n_updates            | 590         |
|    policy_gradient_loss | -0.0607     |
|    value_loss           | 0.000353    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -1.83e+06   |
| time/                   |             |
|    fps                  | 100         |
|    iterations           | 61          |
|    time_elapsed         | 9919        |
|    total_timesteps      | 999424      |
| train/                  |             |
|    approx_kl            | 0.058780737 |
|    clip_fraction        | 0.419       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.52       |
|    explained_variance   | 0.924       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.13       |
|    n_updates            | 600         |
|    policy_gradient_loss | -0.0645     |
|    value_loss           | 0.000174    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -1.83e+06  |
| time/                   |            |
|    fps                  | 100        |
|    iterations           | 62         |
|    time_elapsed         | 10061      |
|    total_timesteps      | 1015808    |
| train/                  |            |
|    approx_kl            | 0.06639656 |
|    clip_fraction        | 0.441      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.69      |
|    explained_variance   | 0.937      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.136     |
|    n_updates            | 610        |
|    policy_gradient_loss | -0.0655    |
|    value_loss           | 0.000301   |
----------------------------------------

Training completed in 2:47:53.608202
Model saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\rl_models\ppo_overload.zip
VecNormalize saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\rl_models\ppo_overload_vecnormalize.pkl

============================================================
Training PPO for scenario: COST
============================================================
Latest model: models\random_forest_cpu_total_usage_20251111_221930.pkl
✓ Model loaded: models\random_forest_cpu_total_usage_20251111_221930.pkl
  Model: random_forest
  Target: cpu_total_usage
  Saved at: 2025-11-11 22:19:30
Latest model: models\svr_memory_usage_pct_20251111_184735.pkl
✓ Model loaded: models\svr_memory_usage_pct_20251111_184735.pkl
  Model: svr
  Target: memory_usage_pct
  Saved at: 2025-11-11 18:47:35
Latest model: models\random_forest_system_load_20251111_221944.pkl
✓ Model loaded: models\random_forest_system_load_20251111_221944.pkl
  Model: random_forest
  Target: system_load
  Saved at: 2025-11-11 22:19:44
Creating new PPO model
Using cpu device

Starting training for 1,000,000 timesteps...
Logging to ./tensorboard_logs/PPO_12

Output()

------------------------------
| time/              |       |
|    fps             | 126   |
|    iterations      | 1     |
|    time_elapsed    | 129   |
|    total_timesteps | 16384 |
------------------------------

----------------------------------------
| time/                   |            |
|    fps                  | 120        |
|    iterations           | 2          |
|    time_elapsed         | 271        |
|    total_timesteps      | 32768      |
| train/                  |            |
|    approx_kl            | 0.03146951 |
|    clip_fraction        | 0.284      |
|    clip_range           | 0.2        |
|    entropy_loss         | -9.57      |
|    explained_variance   | -0.11      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.16      |
|    n_updates            | 10         |
|    policy_gradient_loss | -0.0542    |
|    value_loss           | 0.162      |
----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 119         |
|    iterations           | 3           |
|    time_elapsed         | 412         |
|    total_timesteps      | 49152       |
| train/                  |             |
|    approx_kl            | 0.030611053 |
|    clip_fraction        | 0.321       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.54       |
|    explained_variance   | 0.6         |
|    learning_rate        | 0.0003      |
|    loss                 | -0.164      |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.0626     |
|    value_loss           | 0.0492      |
-----------------------------------------

----------------------------------------
| time/                   |            |
|    fps                  | 117        |
|    iterations           | 4          |
|    time_elapsed         | 555        |
|    total_timesteps      | 65536      |
| train/                  |            |
|    approx_kl            | 0.03352432 |
|    clip_fraction        | 0.353      |
|    clip_range           | 0.2        |
|    entropy_loss         | -9.5       |
|    explained_variance   | 0.521      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.198     |
|    n_updates            | 30         |
|    policy_gradient_loss | -0.0683    |
|    value_loss           | 0.0405     |
----------------------------------------

Eval num_timesteps=80000, episode_reward=-1335436.97 +/- 0.00

Episode length: 17150.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.72e+04    |
|    mean_reward          | -1.34e+06   |
| time/                   |             |
|    total_timesteps      | 80000       |
| train/                  |             |
|    approx_kl            | 0.036436386 |
|    clip_fraction        | 0.39        |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.44       |
|    explained_variance   | 0.674       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.189      |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0737     |
|    value_loss           | 0.0346      |
-----------------------------------------

New best mean reward!

------------------------------
| time/              |       |
|    fps             | 103   |
|    iterations      | 5     |
|    time_elapsed    | 793   |
|    total_timesteps | 81920 |
------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 104         |
|    iterations           | 6           |
|    time_elapsed         | 936         |
|    total_timesteps      | 98304       |
| train/                  |             |
|    approx_kl            | 0.037729688 |
|    clip_fraction        | 0.409       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.37       |
|    explained_variance   | 0.609       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.18       |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.074      |
|    value_loss           | 0.0288      |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 106         |
|    iterations           | 7           |
|    time_elapsed         | 1079        |
|    total_timesteps      | 114688      |
| train/                  |             |
|    approx_kl            | 0.040246084 |
|    clip_fraction        | 0.418       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.29       |
|    explained_variance   | 0.646       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.191      |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.0762     |
|    value_loss           | 0.0245      |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 107         |
|    iterations           | 8           |
|    time_elapsed         | 1221        |
|    total_timesteps      | 131072      |
| train/                  |             |
|    approx_kl            | 0.041607052 |
|    clip_fraction        | 0.428       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.21       |
|    explained_variance   | 0.668       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.192      |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.0772     |
|    value_loss           | 0.0182      |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -4.86e+06   |
| time/                   |             |
|    fps                  | 108         |
|    iterations           | 9           |
|    time_elapsed         | 1363        |
|    total_timesteps      | 147456      |
| train/                  |             |
|    approx_kl            | 0.044181377 |
|    clip_fraction        | 0.433       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.12       |
|    explained_variance   | 0.756       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.209      |
|    n_updates            | 80          |
|    policy_gradient_loss | -0.0776     |
|    value_loss           | 0.0131      |
-----------------------------------------

Eval num_timesteps=160000, episode_reward=-1017695.63 +/- 0.00

Episode length: 17150.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.72e+04    |
|    mean_reward          | -1.02e+06   |
| time/                   |             |
|    total_timesteps      | 160000      |
| train/                  |             |
|    approx_kl            | 0.041869193 |
|    clip_fraction        | 0.418       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9          |
|    explained_variance   | 0.768       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.16       |
|    n_updates            | 90          |
|    policy_gradient_loss | -0.0723     |
|    value_loss           | 0.0126      |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -4.86e+06 |
| time/              |           |
|    fps             | 102       |
|    iterations      | 10        |
|    time_elapsed    | 1601      |
|    total_timesteps | 163840    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -4.86e+06   |
| time/                   |             |
|    fps                  | 103         |
|    iterations           | 11          |
|    time_elapsed         | 1743        |
|    total_timesteps      | 180224      |
| train/                  |             |
|    approx_kl            | 0.044682935 |
|    clip_fraction        | 0.436       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.9        |
|    explained_variance   | 0.854       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.196      |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.0761     |
|    value_loss           | 0.00823     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -4.86e+06  |
| time/                   |            |
|    fps                  | 104        |
|    iterations           | 12         |
|    time_elapsed         | 1886       |
|    total_timesteps      | 196608     |
| train/                  |            |
|    approx_kl            | 0.04372204 |
|    clip_fraction        | 0.421      |
|    clip_range           | 0.2        |
|    entropy_loss         | -8.76      |
|    explained_variance   | 0.887      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.154     |
|    n_updates            | 110        |
|    policy_gradient_loss | -0.0699    |
|    value_loss           | 0.00694    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -4.86e+06   |
| time/                   |             |
|    fps                  | 104         |
|    iterations           | 13          |
|    time_elapsed         | 2029        |
|    total_timesteps      | 212992      |
| train/                  |             |
|    approx_kl            | 0.047553867 |
|    clip_fraction        | 0.444       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.67       |
|    explained_variance   | 0.888       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.191      |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.0745     |
|    value_loss           | 0.00628     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -4.86e+06  |
| time/                   |            |
|    fps                  | 105        |
|    iterations           | 14         |
|    time_elapsed         | 2172       |
|    total_timesteps      | 229376     |
| train/                  |            |
|    approx_kl            | 0.04720221 |
|    clip_fraction        | 0.431      |
|    clip_range           | 0.2        |
|    entropy_loss         | -8.56      |
|    explained_variance   | 0.92       |
|    learning_rate        | 0.0003     |
|    loss                 | -0.174     |
|    n_updates            | 130        |
|    policy_gradient_loss | -0.0714    |
|    value_loss           | 0.00542    |
----------------------------------------

Eval num_timesteps=240000, episode_reward=-1166959.76 +/- 0.00

Episode length: 17150.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.72e+04   |
|    mean_reward          | -1.17e+06  |
| time/                   |            |
|    total_timesteps      | 240000     |
| train/                  |            |
|    approx_kl            | 0.04976791 |
|    clip_fraction        | 0.443      |
|    clip_range           | 0.2        |
|    entropy_loss         | -8.48      |
|    explained_variance   | 0.903      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.205     |
|    n_updates            | 140        |
|    policy_gradient_loss | -0.0746    |
|    value_loss           | 0.00547    |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -4.86e+06 |
| time/              |           |
|    fps             | 101       |
|    iterations      | 15        |
|    time_elapsed    | 2410      |
|    total_timesteps | 245760    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -4.86e+06   |
| time/                   |             |
|    fps                  | 102         |
|    iterations           | 16          |
|    time_elapsed         | 2552        |
|    total_timesteps      | 262144      |
| train/                  |             |
|    approx_kl            | 0.051669993 |
|    clip_fraction        | 0.448       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.38       |
|    explained_variance   | 0.931       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.186      |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.0746     |
|    value_loss           | 0.00439     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -3.94e+06  |
| time/                   |            |
|    fps                  | 103        |
|    iterations           | 17         |
|    time_elapsed         | 2695       |
|    total_timesteps      | 278528     |
| train/                  |            |
|    approx_kl            | 0.05431117 |
|    clip_fraction        | 0.46       |
|    clip_range           | 0.2        |
|    entropy_loss         | -8.3       |
|    explained_variance   | 0.922      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.197     |
|    n_updates            | 160        |
|    policy_gradient_loss | -0.0789    |
|    value_loss           | 0.00372    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -3.94e+06   |
| time/                   |             |
|    fps                  | 103         |
|    iterations           | 18          |
|    time_elapsed         | 2838        |
|    total_timesteps      | 294912      |
| train/                  |             |
|    approx_kl            | 0.053950734 |
|    clip_fraction        | 0.448       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.18       |
|    explained_variance   | 0.923       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.19       |
|    n_updates            | 170         |
|    policy_gradient_loss | -0.0762     |
|    value_loss           | 0.00378     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -3.94e+06  |
| time/                   |            |
|    fps                  | 104        |
|    iterations           | 19         |
|    time_elapsed         | 2981       |
|    total_timesteps      | 311296     |
| train/                  |            |
|    approx_kl            | 0.05094648 |
|    clip_fraction        | 0.444      |
|    clip_range           | 0.2        |
|    entropy_loss         | -8.04      |
|    explained_variance   | 0.927      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.172     |
|    n_updates            | 180        |
|    policy_gradient_loss | -0.073     |
|    value_loss           | 0.00323    |
----------------------------------------

Eval num_timesteps=320000, episode_reward=-1222768.59 +/- 0.00

Episode length: 17150.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.72e+04    |
|    mean_reward          | -1.22e+06   |
| time/                   |             |
|    total_timesteps      | 320000      |
| train/                  |             |
|    approx_kl            | 0.053971346 |
|    clip_fraction        | 0.45        |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.95       |
|    explained_variance   | 0.933       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.178      |
|    n_updates            | 190         |
|    policy_gradient_loss | -0.0758     |
|    value_loss           | 0.00298     |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -3.94e+06 |
| time/              |           |
|    fps             | 101       |
|    iterations      | 20        |
|    time_elapsed    | 3219      |
|    total_timesteps | 327680    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -3.94e+06   |
| time/                   |             |
|    fps                  | 102         |
|    iterations           | 21          |
|    time_elapsed         | 3361        |
|    total_timesteps      | 344064      |
| train/                  |             |
|    approx_kl            | 0.053809725 |
|    clip_fraction        | 0.449       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.79       |
|    explained_variance   | 0.939       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.186      |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.073      |
|    value_loss           | 0.00274     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -3.94e+06   |
| time/                   |             |
|    fps                  | 102         |
|    iterations           | 22          |
|    time_elapsed         | 3503        |
|    total_timesteps      | 360448      |
| train/                  |             |
|    approx_kl            | 0.056693316 |
|    clip_fraction        | 0.462       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.75       |
|    explained_variance   | 0.917       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.185      |
|    n_updates            | 210         |
|    policy_gradient_loss | -0.0708     |
|    value_loss           | 0.00271     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -3.94e+06   |
| time/                   |             |
|    fps                  | 103         |
|    iterations           | 23          |
|    time_elapsed         | 3646        |
|    total_timesteps      | 376832      |
| train/                  |             |
|    approx_kl            | 0.054028094 |
|    clip_fraction        | 0.452       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.69       |
|    explained_variance   | 0.912       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.176      |
|    n_updates            | 220         |
|    policy_gradient_loss | -0.0678     |
|    value_loss           | 0.00234     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -3.94e+06   |
| time/                   |             |
|    fps                  | 103         |
|    iterations           | 24          |
|    time_elapsed         | 3788        |
|    total_timesteps      | 393216      |
| train/                  |             |
|    approx_kl            | 0.058626696 |
|    clip_fraction        | 0.459       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.63       |
|    explained_variance   | 0.892       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.161      |
|    n_updates            | 230         |
|    policy_gradient_loss | -0.0654     |
|    value_loss           | 0.00216     |
-----------------------------------------

Eval num_timesteps=400000, episode_reward=-1502320.56 +/- 0.00

Episode length: 17150.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.72e+04   |
|    mean_reward          | -1.5e+06   |
| time/                   |            |
|    total_timesteps      | 400000     |
| train/                  |            |
|    approx_kl            | 0.05677532 |
|    clip_fraction        | 0.459      |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.62      |
|    explained_variance   | 0.902      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.152     |
|    n_updates            | 240        |
|    policy_gradient_loss | -0.0625    |
|    value_loss           | 0.00262    |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -3.94e+06 |
| time/              |           |
|    fps             | 101       |
|    iterations      | 25        |
|    time_elapsed    | 4026      |
|    total_timesteps | 409600    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -3.31e+06  |
| time/                   |            |
|    fps                  | 102        |
|    iterations           | 26         |
|    time_elapsed         | 4168       |
|    total_timesteps      | 425984     |
| train/                  |            |
|    approx_kl            | 0.05507779 |
|    clip_fraction        | 0.45       |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.46      |
|    explained_variance   | 0.945      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.178     |
|    n_updates            | 250        |
|    policy_gradient_loss | -0.0675    |
|    value_loss           | 0.00206    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -3.31e+06   |
| time/                   |             |
|    fps                  | 102         |
|    iterations           | 27          |
|    time_elapsed         | 4311        |
|    total_timesteps      | 442368      |
| train/                  |             |
|    approx_kl            | 0.054365367 |
|    clip_fraction        | 0.444       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.24       |
|    explained_variance   | 0.935       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.193      |
|    n_updates            | 260         |
|    policy_gradient_loss | -0.0689     |
|    value_loss           | 0.00166     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -3.31e+06  |
| time/                   |            |
|    fps                  | 103        |
|    iterations           | 28         |
|    time_elapsed         | 4453       |
|    total_timesteps      | 458752     |
| train/                  |            |
|    approx_kl            | 0.05794422 |
|    clip_fraction        | 0.455      |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.28      |
|    explained_variance   | 0.917      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.187     |
|    n_updates            | 270        |
|    policy_gradient_loss | -0.0672    |
|    value_loss           | 0.002      |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -3.31e+06   |
| time/                   |             |
|    fps                  | 103         |
|    iterations           | 29          |
|    time_elapsed         | 4595        |
|    total_timesteps      | 475136      |
| train/                  |             |
|    approx_kl            | 0.052533995 |
|    clip_fraction        | 0.439       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.17       |
|    explained_variance   | 0.948       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.125      |
|    n_updates            | 280         |
|    policy_gradient_loss | -0.0622     |
|    value_loss           | 0.00173     |
-----------------------------------------

Eval num_timesteps=480000, episode_reward=-1413036.02 +/- 0.00

Episode length: 17150.00 +/- 0.00

---------------------------------------
| eval/                   |           |
|    mean_ep_length       | 1.72e+04  |
|    mean_reward          | -1.41e+06 |
| time/                   |           |
|    total_timesteps      | 480000    |
| train/                  |           |
|    approx_kl            | 0.0566243 |
|    clip_fraction        | 0.454     |
|    clip_range           | 0.2       |
|    entropy_loss         | -7.09     |
|    explained_variance   | 0.937     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.16     |
|    n_updates            | 290       |
|    policy_gradient_loss | -0.0735   |
|    value_loss           | 0.00154   |
---------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -3.31e+06 |
| time/              |           |
|    fps             | 101       |
|    iterations      | 30        |
|    time_elapsed    | 4833      |
|    total_timesteps | 491520    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -3.31e+06  |
| time/                   |            |
|    fps                  | 102        |
|    iterations           | 31         |
|    time_elapsed         | 4975       |
|    total_timesteps      | 507904     |
| train/                  |            |
|    approx_kl            | 0.05622244 |
|    clip_fraction        | 0.445      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.95      |
|    explained_variance   | 0.951      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.141     |
|    n_updates            | 300        |
|    policy_gradient_loss | -0.0715    |
|    value_loss           | 0.00122    |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -3.31e+06  |
| time/                   |            |
|    fps                  | 102        |
|    iterations           | 32         |
|    time_elapsed         | 5117       |
|    total_timesteps      | 524288     |
| train/                  |            |
|    approx_kl            | 0.05449302 |
|    clip_fraction        | 0.44       |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.89      |
|    explained_variance   | 0.922      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.17      |
|    n_updates            | 310        |
|    policy_gradient_loss | -0.068     |
|    value_loss           | 0.00128    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -3.31e+06   |
| time/                   |             |
|    fps                  | 102         |
|    iterations           | 33          |
|    time_elapsed         | 5259        |
|    total_timesteps      | 540672      |
| train/                  |             |
|    approx_kl            | 0.057833713 |
|    clip_fraction        | 0.445       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.82       |
|    explained_variance   | 0.948       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.174      |
|    n_updates            | 320         |
|    policy_gradient_loss | -0.0689     |
|    value_loss           | 0.00119     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -2.85e+06  |
| time/                   |            |
|    fps                  | 103        |
|    iterations           | 34         |
|    time_elapsed         | 5401       |
|    total_timesteps      | 557056     |
| train/                  |            |
|    approx_kl            | 0.05694963 |
|    clip_fraction        | 0.45       |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.81      |
|    explained_variance   | 0.927      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.16      |
|    n_updates            | 330        |
|    policy_gradient_loss | -0.0728    |
|    value_loss           | 0.00141    |
----------------------------------------

Eval num_timesteps=560000, episode_reward=-1540606.15 +/- 0.00

Episode length: 17150.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.72e+04   |
|    mean_reward          | -1.54e+06  |
| time/                   |            |
|    total_timesteps      | 560000     |
| train/                  |            |
|    approx_kl            | 0.05721112 |
|    clip_fraction        | 0.443      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.75      |
|    explained_variance   | 0.933      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.152     |
|    n_updates            | 340        |
|    policy_gradient_loss | -0.0648    |
|    value_loss           | 0.00131    |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -2.85e+06 |
| time/              |           |
|    fps             | 101       |
|    iterations      | 35        |
|    time_elapsed    | 5640      |
|    total_timesteps | 573440    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -2.85e+06  |
| time/                   |            |
|    fps                  | 102        |
|    iterations           | 36         |
|    time_elapsed         | 5781       |
|    total_timesteps      | 589824     |
| train/                  |            |
|    approx_kl            | 0.05510655 |
|    clip_fraction        | 0.442      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.6       |
|    explained_variance   | 0.915      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.161     |
|    n_updates            | 350        |
|    policy_gradient_loss | -0.0705    |
|    value_loss           | 0.000928   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.85e+06   |
| time/                   |             |
|    fps                  | 102         |
|    iterations           | 37          |
|    time_elapsed         | 5923        |
|    total_timesteps      | 606208      |
| train/                  |             |
|    approx_kl            | 0.054537013 |
|    clip_fraction        | 0.442       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.5        |
|    explained_variance   | 0.91        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.165      |
|    n_updates            | 360         |
|    policy_gradient_loss | -0.0673     |
|    value_loss           | 0.000968    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -2.85e+06  |
| time/                   |            |
|    fps                  | 102        |
|    iterations           | 38         |
|    time_elapsed         | 6065       |
|    total_timesteps      | 622592     |
| train/                  |            |
|    approx_kl            | 0.05488681 |
|    clip_fraction        | 0.436      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.47      |
|    explained_variance   | 0.918      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.15      |
|    n_updates            | 370        |
|    policy_gradient_loss | -0.0673    |
|    value_loss           | 0.00077    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.85e+06   |
| time/                   |             |
|    fps                  | 102         |
|    iterations           | 39          |
|    time_elapsed         | 6207        |
|    total_timesteps      | 638976      |
| train/                  |             |
|    approx_kl            | 0.062022895 |
|    clip_fraction        | 0.453       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.54       |
|    explained_variance   | 0.937       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.153      |
|    n_updates            | 380         |
|    policy_gradient_loss | -0.0568     |
|    value_loss           | 0.000864    |
-----------------------------------------

Eval num_timesteps=640000, episode_reward=-1158521.72 +/- 0.00

Episode length: 17150.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 1.72e+04   |
|    mean_reward          | -1.16e+06  |
| time/                   |            |
|    total_timesteps      | 640000     |
| train/                  |            |
|    approx_kl            | 0.06132507 |
|    clip_fraction        | 0.458      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.53      |
|    explained_variance   | 0.957      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.167     |
|    n_updates            | 390        |
|    policy_gradient_loss | -0.0654    |
|    value_loss           | 0.0009     |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -2.85e+06 |
| time/              |           |
|    fps             | 101       |
|    iterations      | 40        |
|    time_elapsed    | 6445      |
|    total_timesteps | 655360    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -2.85e+06  |
| time/                   |            |
|    fps                  | 101        |
|    iterations           | 41         |
|    time_elapsed         | 6588       |
|    total_timesteps      | 671744     |
| train/                  |            |
|    approx_kl            | 0.06399976 |
|    clip_fraction        | 0.465      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.52      |
|    explained_variance   | 0.962      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.168     |
|    n_updates            | 400        |
|    policy_gradient_loss | -0.0646    |
|    value_loss           | 0.00108    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.51e+06   |
| time/                   |             |
|    fps                  | 102         |
|    iterations           | 42          |
|    time_elapsed         | 6730        |
|    total_timesteps      | 688128      |
| train/                  |             |
|    approx_kl            | 0.061949722 |
|    clip_fraction        | 0.463       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.33       |
|    explained_variance   | 0.949       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.171      |
|    n_updates            | 410         |
|    policy_gradient_loss | -0.0731     |
|    value_loss           | 0.000851    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.51e+06   |
| time/                   |             |
|    fps                  | 102         |
|    iterations           | 43          |
|    time_elapsed         | 6872        |
|    total_timesteps      | 704512      |
| train/                  |             |
|    approx_kl            | 0.065444365 |
|    clip_fraction        | 0.464       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.25       |
|    explained_variance   | 0.961       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.148      |
|    n_updates            | 420         |
|    policy_gradient_loss | -0.0717     |
|    value_loss           | 0.000839    |
-----------------------------------------

Eval num_timesteps=720000, episode_reward=-1239707.09 +/- 0.00

Episode length: 17150.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.72e+04    |
|    mean_reward          | -1.24e+06   |
| time/                   |             |
|    total_timesteps      | 720000      |
| train/                  |             |
|    approx_kl            | 0.060108446 |
|    clip_fraction        | 0.454       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.07       |
|    explained_variance   | 0.916       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.177      |
|    n_updates            | 430         |
|    policy_gradient_loss | -0.0739     |
|    value_loss           | 0.00055     |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -2.51e+06 |
| time/              |           |
|    fps             | 101       |
|    iterations      | 44        |
|    time_elapsed    | 7110      |
|    total_timesteps | 720896    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.51e+06   |
| time/                   |             |
|    fps                  | 101         |
|    iterations           | 45          |
|    time_elapsed         | 7252        |
|    total_timesteps      | 737280      |
| train/                  |             |
|    approx_kl            | 0.061702155 |
|    clip_fraction        | 0.449       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6          |
|    explained_variance   | 0.928       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.174      |
|    n_updates            | 440         |
|    policy_gradient_loss | -0.0706     |
|    value_loss           | 0.000527    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.51e+06   |
| time/                   |             |
|    fps                  | 101         |
|    iterations           | 46          |
|    time_elapsed         | 7394        |
|    total_timesteps      | 753664      |
| train/                  |             |
|    approx_kl            | 0.062280312 |
|    clip_fraction        | 0.453       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.03       |
|    explained_variance   | 0.952       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.144      |
|    n_updates            | 450         |
|    policy_gradient_loss | -0.0657     |
|    value_loss           | 0.000719    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.51e+06   |
| time/                   |             |
|    fps                  | 102         |
|    iterations           | 47          |
|    time_elapsed         | 7536        |
|    total_timesteps      | 770048      |
| train/                  |             |
|    approx_kl            | 0.064408414 |
|    clip_fraction        | 0.461       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6          |
|    explained_variance   | 0.971       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.151      |
|    n_updates            | 460         |
|    policy_gradient_loss | -0.0636     |
|    value_loss           | 0.000717    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -2.51e+06  |
| time/                   |            |
|    fps                  | 102        |
|    iterations           | 48         |
|    time_elapsed         | 7679       |
|    total_timesteps      | 786432     |
| train/                  |            |
|    approx_kl            | 0.06491946 |
|    clip_fraction        | 0.461      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.92      |
|    explained_variance   | 0.973      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.107     |
|    n_updates            | 470        |
|    policy_gradient_loss | -0.064     |
|    value_loss           | 0.000727   |
----------------------------------------

Eval num_timesteps=800000, episode_reward=-877559.29 +/- 0.00

Episode length: 17150.00 +/- 0.00

---------------------------------------
| eval/                   |           |
|    mean_ep_length       | 1.72e+04  |
|    mean_reward          | -8.78e+05 |
| time/                   |           |
|    total_timesteps      | 800000    |
| train/                  |           |
|    approx_kl            | 0.0627585 |
|    clip_fraction        | 0.456     |
|    clip_range           | 0.2       |
|    entropy_loss         | -5.83     |
|    explained_variance   | 0.977     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.16     |
|    n_updates            | 480       |
|    policy_gradient_loss | -0.0658   |
|    value_loss           | 0.000698  |
---------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -2.51e+06 |
| time/              |           |
|    fps             | 101       |
|    iterations      | 49        |
|    time_elapsed    | 7916      |
|    total_timesteps | 802816    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.51e+06   |
| time/                   |             |
|    fps                  | 101         |
|    iterations           | 50          |
|    time_elapsed         | 8058        |
|    total_timesteps      | 819200      |
| train/                  |             |
|    approx_kl            | 0.061066188 |
|    clip_fraction        | 0.447       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.77       |
|    explained_variance   | 0.965       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.154      |
|    n_updates            | 490         |
|    policy_gradient_loss | -0.0642     |
|    value_loss           | 0.000557    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -2.24e+06  |
| time/                   |            |
|    fps                  | 101        |
|    iterations           | 51         |
|    time_elapsed         | 8200       |
|    total_timesteps      | 835584     |
| train/                  |            |
|    approx_kl            | 0.06341945 |
|    clip_fraction        | 0.459      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.69      |
|    explained_variance   | 0.933      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.138     |
|    n_updates            | 500        |
|    policy_gradient_loss | -0.0696    |
|    value_loss           | 0.000464   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.24e+06   |
| time/                   |             |
|    fps                  | 102         |
|    iterations           | 52          |
|    time_elapsed         | 8342        |
|    total_timesteps      | 851968      |
| train/                  |             |
|    approx_kl            | 0.059269108 |
|    clip_fraction        | 0.443       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.57       |
|    explained_variance   | 0.951       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.131      |
|    n_updates            | 510         |
|    policy_gradient_loss | -0.0684     |
|    value_loss           | 0.000384    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.24e+06   |
| time/                   |             |
|    fps                  | 102         |
|    iterations           | 53          |
|    time_elapsed         | 8484        |
|    total_timesteps      | 868352      |
| train/                  |             |
|    approx_kl            | 0.061402433 |
|    clip_fraction        | 0.441       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.49       |
|    explained_variance   | 0.956       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.153      |
|    n_updates            | 520         |
|    policy_gradient_loss | -0.0684     |
|    value_loss           | 0.000397    |
-----------------------------------------

Eval num_timesteps=880000, episode_reward=-618054.41 +/- 0.00

Episode length: 17150.00 +/- 0.00

---------------------------------------
| eval/                   |           |
|    mean_ep_length       | 1.72e+04  |
|    mean_reward          | -6.18e+05 |
| time/                   |           |
|    total_timesteps      | 880000    |
| train/                  |           |
|    approx_kl            | 0.0673884 |
|    clip_fraction        | 0.454     |
|    clip_range           | 0.2       |
|    entropy_loss         | -5.52     |
|    explained_variance   | 0.966     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.164    |
|    n_updates            | 530       |
|    policy_gradient_loss | -0.0703   |
|    value_loss           | 0.00036   |
---------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -2.24e+06 |
| time/              |           |
|    fps             | 101       |
|    iterations      | 54        |
|    time_elapsed    | 8723      |
|    total_timesteps | 884736    |
----------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 1.72e+04  |
|    ep_rew_mean          | -2.24e+06 |
| time/                   |           |
|    fps                  | 101       |
|    iterations           | 55        |
|    time_elapsed         | 8865      |
|    total_timesteps      | 901120    |
| train/                  |           |
|    approx_kl            | 0.0630735 |
|    clip_fraction        | 0.448     |
|    clip_range           | 0.2       |
|    entropy_loss         | -5.42     |
|    explained_variance   | 0.967     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.158    |
|    n_updates            | 540       |
|    policy_gradient_loss | -0.0646   |
|    value_loss           | 0.000353  |
---------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.24e+06   |
| time/                   |             |
|    fps                  | 101         |
|    iterations           | 56          |
|    time_elapsed         | 9007        |
|    total_timesteps      | 917504      |
| train/                  |             |
|    approx_kl            | 0.062483057 |
|    clip_fraction        | 0.449       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.41       |
|    explained_variance   | 0.972       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.138      |
|    n_updates            | 550         |
|    policy_gradient_loss | -0.0669     |
|    value_loss           | 0.00032     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.24e+06   |
| time/                   |             |
|    fps                  | 102         |
|    iterations           | 57          |
|    time_elapsed         | 9150        |
|    total_timesteps      | 933888      |
| train/                  |             |
|    approx_kl            | 0.062609114 |
|    clip_fraction        | 0.451       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.4        |
|    explained_variance   | 0.967       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.15       |
|    n_updates            | 560         |
|    policy_gradient_loss | -0.0677     |
|    value_loss           | 0.00037     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.24e+06   |
| time/                   |             |
|    fps                  | 102         |
|    iterations           | 58          |
|    time_elapsed         | 9293        |
|    total_timesteps      | 950272      |
| train/                  |             |
|    approx_kl            | 0.062824264 |
|    clip_fraction        | 0.455       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.28       |
|    explained_variance   | 0.947       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.153      |
|    n_updates            | 570         |
|    policy_gradient_loss | -0.0719     |
|    value_loss           | 0.000306    |
-----------------------------------------

Eval num_timesteps=960000, episode_reward=-483077.05 +/- 0.00

Episode length: 17150.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 1.72e+04    |
|    mean_reward          | -4.83e+05   |
| time/                   |             |
|    total_timesteps      | 960000      |
| train/                  |             |
|    approx_kl            | 0.062879264 |
|    clip_fraction        | 0.453       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.18       |
|    explained_variance   | 0.907       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.162      |
|    n_updates            | 580         |
|    policy_gradient_loss | -0.0728     |
|    value_loss           | 0.000253    |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 1.72e+04  |
|    ep_rew_mean     | -2.02e+06 |
| time/              |           |
|    fps             | 101       |
|    iterations      | 59        |
|    time_elapsed    | 9533      |
|    total_timesteps | 966656    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -2.02e+06  |
| time/                   |            |
|    fps                  | 101        |
|    iterations           | 60         |
|    time_elapsed         | 9674       |
|    total_timesteps      | 983040     |
| train/                  |            |
|    approx_kl            | 0.06703915 |
|    clip_fraction        | 0.46       |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.21      |
|    explained_variance   | 0.939      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.152     |
|    n_updates            | 590        |
|    policy_gradient_loss | -0.0739    |
|    value_loss           | 0.000262   |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 1.72e+04   |
|    ep_rew_mean          | -2.02e+06  |
| time/                   |            |
|    fps                  | 101        |
|    iterations           | 61         |
|    time_elapsed         | 9816       |
|    total_timesteps      | 999424     |
| train/                  |            |
|    approx_kl            | 0.06502309 |
|    clip_fraction        | 0.453      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.05      |
|    explained_variance   | 0.948      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.119     |
|    n_updates            | 600        |
|    policy_gradient_loss | -0.0748    |
|    value_loss           | 0.00019    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 1.72e+04    |
|    ep_rew_mean          | -2.02e+06   |
| time/                   |             |
|    fps                  | 102         |
|    iterations           | 62          |
|    time_elapsed         | 9958        |
|    total_timesteps      | 1015808     |
| train/                  |             |
|    approx_kl            | 0.067031845 |
|    clip_fraction        | 0.449       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.05       |
|    explained_variance   | 0.967       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.118      |
|    n_updates            | 610         |
|    policy_gradient_loss | -0.0683     |
|    value_loss           | 0.000185    |
-----------------------------------------

Training completed in 2:46:10.811818
Model saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\rl_models\ppo_cost.zip
VecNormalize saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\rl_models\ppo_cost_vecnormalize.pkl

In [ ]:
# Evaluation: run PPO on test set (per-step results)

results = {}

for scenario in [SCENARIO_OVERLOAD, SCENARIO_COST]:
    comp = evaluate_scenario(
        scenario,
        episode_length=exp_config.episode_length,
        horizon=exp_config.horizon,
    )
    results[scenario] = comp
    print_comparison(comp)

results

============================================================
Evaluating scenario: OVERLOAD
============================================================
Latest model: models\random_forest_cpu_total_usage_20251111_221930.pkl
✓ Model loaded: models\random_forest_cpu_total_usage_20251111_221930.pkl
  Model: random_forest
  Target: cpu_total_usage
  Saved at: 2025-11-11 22:19:30
Latest model: models\svr_memory_usage_pct_20251111_184735.pkl
✓ Model loaded: models\svr_memory_usage_pct_20251111_184735.pkl
  Model: svr
  Target: memory_usage_pct
  Saved at: 2025-11-11 18:47:35
Latest model: models\random_forest_system_load_20251111_221944.pkl
✓ Model loaded: models\random_forest_system_load_20251111_221944.pkl
  Model: random_forest
  Target: system_load
  Saved at: 2025-11-11 22:19:44
Warning: VecNormalize shape mismatch, skipping normalization. Details: spaces must have the same shape
Loaded model from E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\rl_models\ppo_overload.zip

Running PPO rollout for scenario: overload
Latest model: models\random_forest_cpu_total_usage_20251111_221930.pkl
✓ Model loaded: models\random_forest_cpu_total_usage_20251111_221930.pkl
  Model: random_forest
  Target: cpu_total_usage
  Saved at: 2025-11-11 22:19:30
Latest model: models\svr_memory_usage_pct_20251111_184735.pkl
✓ Model loaded: models\svr_memory_usage_pct_20251111_184735.pkl
  Model: svr
  Target: memory_usage_pct
  Saved at: 2025-11-11 18:47:35
Latest model: models\random_forest_system_load_20251111_221944.pkl
✓ Model loaded: models\random_forest_system_load_20251111_221944.pkl
  Model: random_forest
  Target: system_load
  Saved at: 2025-11-11 22:19:44

ValueError: Error: Unexpected observation shape (49,) for Box environment, please use (373,) or (n_env, 373) for the observation shape.

In [ ]:
# Inspect generated PPO schedules (PER-STEP results)

import pandas as pd
import numpy as np
from pathlib import Path

RESULTS_DIR = Path("forecast_result")

# Load PPO per-step schedules
ppo_overload_path = RESULTS_DIR / "ppo_schedule_test_overload.csv"
ppo_cost_path = RESULTS_DIR / "ppo_schedule_test_cost.csv"

print("=== PPO Per-Step Schedules ===")
print(f"PPO overload: {ppo_overload_path.exists()}")
print(f"PPO cost: {ppo_cost_path.exists()}")

ppo_overload_df = pd.read_csv(ppo_overload_path) if ppo_overload_path.exists() else None
ppo_cost_df = pd.read_csv(ppo_cost_path) if ppo_cost_path.exists() else None

if ppo_overload_df is not None:
    print(f"\nPPO Overload: {len(ppo_overload_df)} steps")
    display(ppo_overload_df.head(10))

if ppo_cost_df is not None:
    print(f"\nPPO Cost: {len(ppo_cost_df)} steps")
    display(ppo_cost_df.head(10))

=== PPO Per-Step Schedules ===
PPO overload: True
PPO cost: True

PPO Overload: 17150 steps

,timestamp,allocation,vm_cost_per_hour,switching_cost,total_cost_per_hour,cpu_allocated_cores,mem_allocated_gb,cpu_vm_only,mem_vm_only,cpu_required_cores,mem_required_gb,cpu_overflow_cores,mem_overflow_gb,cpu_utilization_pct,mem_utilization_pct,sla_violation_flag
0,1970-01-25 01:05:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.24,0.258175,0.0,0,0.0,0.0,0
1,1970-01-25 01:06:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.22,0.258186,0.0,0,0.0,0.0,0
2,1970-01-25 01:06:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.13,0.258044,0.0,0,0.0,0.0,0
3,1970-01-25 01:07:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.08,0.257840,0.0,0,0.0,0.0,0
4,1970-01-25 01:07:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.10,0.258327,0.0,0,0.0,0.0,0
5,1970-01-25 01:08:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.23,0.258050,0.0,0,0.0,0.0,0
6,1970-01-25 01:08:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.14,0.258136,0.0,0,0.0,0.0,0
7,1970-01-25 01:09:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.21,0.258079,0.0,0,0.0,0.0,0
8,1970-01-25 01:09:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.12,0.258266,0.0,0,0.0,0.0,0
9,1970-01-25 01:10:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.07,0.258260,0.0,0,0.0,0.0,0

PPO Cost: 17150 steps

,timestamp,allocation,vm_cost_per_hour,switching_cost,total_cost_per_hour,cpu_allocated_cores,mem_allocated_gb,cpu_vm_only,mem_vm_only,cpu_required_cores,mem_required_gb,cpu_overflow_cores,mem_overflow_gb,cpu_utilization_pct,mem_utilization_pct,sla_violation_flag
0,1970-01-25 01:05:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.24,0.258175,0.0,0,0.0,0.0,0
1,1970-01-25 01:06:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.22,0.258186,0.0,0,0.0,0.0,0
2,1970-01-25 01:06:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.13,0.258044,0.0,0,0.0,0.0,0
3,1970-01-25 01:07:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.08,0.257840,0.0,0,0.0,0.0,0
4,1970-01-25 01:07:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.10,0.258327,0.0,0,0.0,0.0,0
5,1970-01-25 01:08:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.23,0.258050,0.0,0,0.0,0.0,0
6,1970-01-25 01:08:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.14,0.258136,0.0,0,0.0,0.0,0
7,1970-01-25 01:09:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.21,0.258079,0.0,0,0.0,0.0,0
8,1970-01-25 01:09:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.12,0.258266,0.0,0,0.0,0.0,0
9,1970-01-25 01:10:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.07,0.258260,0.0,0,0.0,0.0,0