# PPO VM Allocation Experiments

This notebook trains and evaluates PPO agents for VM allocation using the existing DRL pipeline:

- `rl/environment.py`: `VMAllocationEnv` (Gymnasium environment)
- `rl/config.py`: PPO and reward configuration
- `train_ppo.py`: training script
- `eval_ppo.py`: evaluation and comparison with LP baseline

You can use this notebook to:
- Run quick training experiments (e.g., smaller `total_timesteps`)
- Evaluate PPO against the LP baseline
- Inspect the generated PPO schedules and metrics.

In [1]:
# Imports and configuration

from pathlib import Path

# Module imports
import importlib
import train_ppo as train_ppo_module
import eval_ppo as eval_ppo_module
import rl.config as rl_config_module

from rl.config import PPOConfig, SCENARIO_OVERLOAD, SCENARIO_COST
from train_ppo import train_ppo
from eval_ppo import evaluate_scenario, print_comparison

# Reload modules to pick up latest code when notebook stays open
importlib.reload(train_ppo_module)
importlib.reload(eval_ppo_module)
importlib.reload(rl_config_module)

# Refresh config after reload
from rl.config import PPOConfig, SCENARIO_OVERLOAD, SCENARIO_COST

PROJECT_ROOT = Path.cwd()
print("Project root:", PROJECT_ROOT)

# Show current default PPO configuration
config = PPOConfig()
config

Project root: e:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure

PPOConfig(learning_rate=0.0003, n_steps=2048, batch_size=64, n_epochs=10, gamma=0.99, gae_lambda=0.95, clip_range=0.2, clip_range_vf=None, ent_coef=0.01, vf_coef=0.5, max_grad_norm=0.5, episode_length=480, horizon=18, total_timesteps=1000000, tensorboard_log='./tensorboard_logs/', log_interval=10, save_freq=10000)

In [2]:
# Quick training config (adjust as needed)
from copy import deepcopy

# Number of parallel envs (increase if you have CPU/GPU resources)
N_ENVS = 8

exp_config = deepcopy(config)

# Default: 1,000,000 timesteps (recommended after reward tweaks)
# For a quick debug run, set to 50_000
exp_config.total_timesteps = 1_000_000

print("Training configuration override:")
print("  total_timesteps =", exp_config.total_timesteps)
print("  episode_length  =", exp_config.episode_length)
print("  horizon         =", exp_config.horizon)
print("  n_envs          =", N_ENVS)

Training configuration override:
  total_timesteps = 1000000
  episode_length  = 480
  horizon         = 18
  n_envs          = 8

In [4]:

print("Training configuration:")
print("  total_timesteps =", exp_config.total_timesteps)
print("  episode_length  =", exp_config.episode_length)
print("  horizon         =", exp_config.horizon)
print("  n_envs          =", N_ENVS)

# Train overload-first scenario
model_overload = train_ppo(
    scenario=SCENARIO_OVERLOAD,
    config=exp_config,
    total_timesteps=exp_config.total_timesteps,
    n_envs=N_ENVS,
    continue_training=False,
)

# Train cost-first scenario
model_cost = train_ppo(
    scenario=SCENARIO_COST,
    config=exp_config,
    total_timesteps=exp_config.total_timesteps,
    n_envs=N_ENVS,
    continue_training=False,
)

Training configuration:
  total_timesteps = 1000000
  episode_length  = 480
  horizon         = 18
  n_envs          = 8

============================================================
Training PPO for scenario: OVERLOAD
============================================================
Latest model: models\random_forest_cpu_total_usage_20251111_221930.pkl
✓ Model loaded: models\random_forest_cpu_total_usage_20251111_221930.pkl
  Model: random_forest
  Target: cpu_total_usage
  Saved at: 2025-11-11 22:19:30
Latest model: models\svr_memory_usage_pct_20251111_184735.pkl
✓ Model loaded: models\svr_memory_usage_pct_20251111_184735.pkl
  Model: svr
  Target: memory_usage_pct
  Saved at: 2025-11-11 18:47:35
Latest model: models\random_forest_system_load_20251111_221944.pkl
✓ Model loaded: models\random_forest_system_load_20251111_221944.pkl
  Model: random_forest
  Target: system_load
  Saved at: 2025-11-11 22:19:44
Creating new PPO model
Using cpu device

Starting training for 1,000,000 timesteps...
Logging to ./tensorboard_logs/PPO_9

Output()

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -1.05e+04 |
| time/              |           |
|    fps             | 733       |
|    iterations      | 1         |
|    time_elapsed    | 22        |
|    total_timesteps | 16384     |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.05e+04   |
| time/                   |             |
|    fps                  | 597         |
|    iterations           | 2           |
|    time_elapsed         | 54          |
|    total_timesteps      | 32768       |
| train/                  |             |
|    approx_kl            | 0.017610408 |
|    clip_fraction        | 0.191       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.58       |
|    explained_variance   | -0.691      |
|    learning_rate        | 0.0003      |
|    loss                 | 0.272       |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0294     |
|    value_loss           | 0.186       |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.04e+04   |
| time/                   |             |
|    fps                  | 571         |
|    iterations           | 3           |
|    time_elapsed         | 85          |
|    total_timesteps      | 49152       |
| train/                  |             |
|    approx_kl            | 0.017722454 |
|    clip_fraction        | 0.213       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.56       |
|    explained_variance   | 0.264       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.131      |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.0319     |
|    value_loss           | 0.0209      |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -1.01e+04  |
| time/                   |            |
|    fps                  | 561        |
|    iterations           | 4          |
|    time_elapsed         | 116        |
|    total_timesteps      | 65536      |
| train/                  |            |
|    approx_kl            | 0.02058186 |
|    clip_fraction        | 0.262      |
|    clip_range           | 0.2        |
|    entropy_loss         | -9.53      |
|    explained_variance   | 0.614      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.14      |
|    n_updates            | 30         |
|    policy_gradient_loss | -0.0388    |
|    value_loss           | 0.0108     |
----------------------------------------

Eval num_timesteps=80000, episode_reward=-5045.55 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -5.05e+03   |
| time/                   |             |
|    total_timesteps      | 80000       |
| train/                  |             |
|    approx_kl            | 0.020495534 |
|    clip_fraction        | 0.27        |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.49       |
|    explained_variance   | 0.635       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.131      |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0395     |
|    value_loss           | 0.00808     |
-----------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 480      |
|    ep_rew_mean     | -9.6e+03 |
| time/              |          |
|    fps             | 540      |
|    iterations      | 5        |
|    time_elapsed    | 151      |
|    total_timesteps | 81920    |
---------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -9.1e+03    |
| time/                   |             |
|    fps                  | 541         |
|    iterations           | 6           |
|    time_elapsed         | 181         |
|    total_timesteps      | 98304       |
| train/                  |             |
|    approx_kl            | 0.022435356 |
|    clip_fraction        | 0.309       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.42       |
|    explained_variance   | 0.655       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.142      |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.0443     |
|    value_loss           | 0.00591     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -8.53e+03   |
| time/                   |             |
|    fps                  | 530         |
|    iterations           | 7           |
|    time_elapsed         | 216         |
|    total_timesteps      | 114688      |
| train/                  |             |
|    approx_kl            | 0.023289245 |
|    clip_fraction        | 0.317       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.35       |
|    explained_variance   | 0.681       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.188      |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.0466     |
|    value_loss           | 0.00481     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -7.84e+03  |
| time/                   |            |
|    fps                  | 528        |
|    iterations           | 8          |
|    time_elapsed         | 247        |
|    total_timesteps      | 131072     |
| train/                  |            |
|    approx_kl            | 0.02328347 |
|    clip_fraction        | 0.334      |
|    clip_range           | 0.2        |
|    entropy_loss         | -9.25      |
|    explained_variance   | 0.669      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.149     |
|    n_updates            | 70         |
|    policy_gradient_loss | -0.0484    |
|    value_loss           | 0.00383    |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -7.28e+03  |
| time/                   |            |
|    fps                  | 529        |
|    iterations           | 9          |
|    time_elapsed         | 278        |
|    total_timesteps      | 147456     |
| train/                  |            |
|    approx_kl            | 0.02315952 |
|    clip_fraction        | 0.319      |
|    clip_range           | 0.2        |
|    entropy_loss         | -9.14      |
|    explained_variance   | 0.697      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.155     |
|    n_updates            | 80         |
|    policy_gradient_loss | -0.0475    |
|    value_loss           | 0.0037     |
----------------------------------------

Eval num_timesteps=160000, episode_reward=-3307.91 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -3.31e+03   |
| time/                   |             |
|    total_timesteps      | 160000      |
| train/                  |             |
|    approx_kl            | 0.023749396 |
|    clip_fraction        | 0.336       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.01       |
|    explained_variance   | 0.758       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0986     |
|    n_updates            | 90          |
|    policy_gradient_loss | -0.0496     |
|    value_loss           | 0.00287     |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -6.76e+03 |
| time/              |           |
|    fps             | 522       |
|    iterations      | 10        |
|    time_elapsed    | 313       |
|    total_timesteps | 163840    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -6.24e+03   |
| time/                   |             |
|    fps                  | 515         |
|    iterations           | 11          |
|    time_elapsed         | 349         |
|    total_timesteps      | 180224      |
| train/                  |             |
|    approx_kl            | 0.024440598 |
|    clip_fraction        | 0.333       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.89       |
|    explained_variance   | 0.73        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.153      |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.0497     |
|    value_loss           | 0.00282     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -5.65e+03   |
| time/                   |             |
|    fps                  | 510         |
|    iterations           | 12          |
|    time_elapsed         | 385         |
|    total_timesteps      | 196608      |
| train/                  |             |
|    approx_kl            | 0.024199117 |
|    clip_fraction        | 0.325       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.74       |
|    explained_variance   | 0.716       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.136      |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.0475     |
|    value_loss           | 0.00263     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -5.22e+03   |
| time/                   |             |
|    fps                  | 506         |
|    iterations           | 13          |
|    time_elapsed         | 420         |
|    total_timesteps      | 212992      |
| train/                  |             |
|    approx_kl            | 0.023872163 |
|    clip_fraction        | 0.321       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.56       |
|    explained_variance   | 0.772       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.121      |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.0469     |
|    value_loss           | 0.00245     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -4.82e+03  |
| time/                   |            |
|    fps                  | 505        |
|    iterations           | 14         |
|    time_elapsed         | 453        |
|    total_timesteps      | 229376     |
| train/                  |            |
|    approx_kl            | 0.02348869 |
|    clip_fraction        | 0.308      |
|    clip_range           | 0.2        |
|    entropy_loss         | -8.47      |
|    explained_variance   | 0.729      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.16      |
|    n_updates            | 130        |
|    policy_gradient_loss | -0.0455    |
|    value_loss           | 0.00229    |
----------------------------------------

Eval num_timesteps=240000, episode_reward=-1518.52 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -1.52e+03   |
| time/                   |             |
|    total_timesteps      | 240000      |
| train/                  |             |
|    approx_kl            | 0.021959106 |
|    clip_fraction        | 0.29        |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.32       |
|    explained_variance   | 0.756       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.135      |
|    n_updates            | 140         |
|    policy_gradient_loss | -0.0427     |
|    value_loss           | 0.00251     |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -4.48e+03 |
| time/              |           |
|    fps             | 503       |
|    iterations      | 15        |
|    time_elapsed    | 488       |
|    total_timesteps | 245760    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -4.17e+03   |
| time/                   |             |
|    fps                  | 502         |
|    iterations           | 16          |
|    time_elapsed         | 521         |
|    total_timesteps      | 262144      |
| train/                  |             |
|    approx_kl            | 0.024657018 |
|    clip_fraction        | 0.309       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.22       |
|    explained_variance   | 0.758       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.151      |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.0449     |
|    value_loss           | 0.00233     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -3.91e+03  |
| time/                   |            |
|    fps                  | 500        |
|    iterations           | 17         |
|    time_elapsed         | 556        |
|    total_timesteps      | 278528     |
| train/                  |            |
|    approx_kl            | 0.02305453 |
|    clip_fraction        | 0.295      |
|    clip_range           | 0.2        |
|    entropy_loss         | -8.06      |
|    explained_variance   | 0.787      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.126     |
|    n_updates            | 160        |
|    policy_gradient_loss | -0.0419    |
|    value_loss           | 0.00209    |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -3.59e+03  |
| time/                   |            |
|    fps                  | 497        |
|    iterations           | 18         |
|    time_elapsed         | 592        |
|    total_timesteps      | 294912     |
| train/                  |            |
|    approx_kl            | 0.02278167 |
|    clip_fraction        | 0.288      |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.92      |
|    explained_variance   | 0.772      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.146     |
|    n_updates            | 170        |
|    policy_gradient_loss | -0.0433    |
|    value_loss           | 0.00166    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -3.27e+03   |
| time/                   |             |
|    fps                  | 499         |
|    iterations           | 19          |
|    time_elapsed         | 622         |
|    total_timesteps      | 311296      |
| train/                  |             |
|    approx_kl            | 0.023007967 |
|    clip_fraction        | 0.287       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.76       |
|    explained_variance   | 0.758       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.147      |
|    n_updates            | 180         |
|    policy_gradient_loss | -0.0431     |
|    value_loss           | 0.00162     |
-----------------------------------------

Eval num_timesteps=320000, episode_reward=-1104.53 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -1.1e+03    |
| time/                   |             |
|    total_timesteps      | 320000      |
| train/                  |             |
|    approx_kl            | 0.023409814 |
|    clip_fraction        | 0.296       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.59       |
|    explained_variance   | 0.8         |
|    learning_rate        | 0.0003      |
|    loss                 | -0.106      |
|    n_updates            | 190         |
|    policy_gradient_loss | -0.0431     |
|    value_loss           | 0.0014      |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -3.04e+03 |
| time/              |           |
|    fps             | 501       |
|    iterations      | 20        |
|    time_elapsed    | 653       |
|    total_timesteps | 327680    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -2.85e+03   |
| time/                   |             |
|    fps                  | 504         |
|    iterations           | 21          |
|    time_elapsed         | 681         |
|    total_timesteps      | 344064      |
| train/                  |             |
|    approx_kl            | 0.021575272 |
|    clip_fraction        | 0.279       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.47       |
|    explained_variance   | 0.771       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.123      |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.0411     |
|    value_loss           | 0.00149     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -2.66e+03   |
| time/                   |             |
|    fps                  | 507         |
|    iterations           | 22          |
|    time_elapsed         | 709         |
|    total_timesteps      | 360448      |
| train/                  |             |
|    approx_kl            | 0.021661602 |
|    clip_fraction        | 0.269       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.38       |
|    explained_variance   | 0.819       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.138      |
|    n_updates            | 210         |
|    policy_gradient_loss | -0.0389     |
|    value_loss           | 0.00141     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -2.47e+03   |
| time/                   |             |
|    fps                  | 510         |
|    iterations           | 23          |
|    time_elapsed         | 737         |
|    total_timesteps      | 376832      |
| train/                  |             |
|    approx_kl            | 0.021808036 |
|    clip_fraction        | 0.276       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.15       |
|    explained_variance   | 0.826       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.118      |
|    n_updates            | 220         |
|    policy_gradient_loss | -0.0389     |
|    value_loss           | 0.000975    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -2.34e+03   |
| time/                   |             |
|    fps                  | 513         |
|    iterations           | 24          |
|    time_elapsed         | 765         |
|    total_timesteps      | 393216      |
| train/                  |             |
|    approx_kl            | 0.022162803 |
|    clip_fraction        | 0.273       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.08       |
|    explained_variance   | 0.819       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.126      |
|    n_updates            | 230         |
|    policy_gradient_loss | -0.0407     |
|    value_loss           | 0.00119     |
-----------------------------------------

Eval num_timesteps=400000, episode_reward=-966.75 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -967        |
| time/                   |             |
|    total_timesteps      | 400000      |
| train/                  |             |
|    approx_kl            | 0.021787234 |
|    clip_fraction        | 0.279       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.98       |
|    explained_variance   | 0.872       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.109      |
|    n_updates            | 240         |
|    policy_gradient_loss | -0.0419     |
|    value_loss           | 0.000994    |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -2.21e+03 |
| time/              |           |
|    fps             | 514       |
|    iterations      | 25        |
|    time_elapsed    | 796       |
|    total_timesteps | 409600    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -2.07e+03   |
| time/                   |             |
|    fps                  | 516         |
|    iterations           | 26          |
|    time_elapsed         | 825         |
|    total_timesteps      | 425984      |
| train/                  |             |
|    approx_kl            | 0.023256691 |
|    clip_fraction        | 0.282       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.8        |
|    explained_variance   | 0.891       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.117      |
|    n_updates            | 250         |
|    policy_gradient_loss | -0.0421     |
|    value_loss           | 0.000758    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.94e+03   |
| time/                   |             |
|    fps                  | 518         |
|    iterations           | 27          |
|    time_elapsed         | 853         |
|    total_timesteps      | 442368      |
| train/                  |             |
|    approx_kl            | 0.021985814 |
|    clip_fraction        | 0.272       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.71       |
|    explained_variance   | 0.882       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.125      |
|    n_updates            | 260         |
|    policy_gradient_loss | -0.039      |
|    value_loss           | 0.000834    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -1.87e+03  |
| time/                   |            |
|    fps                  | 520        |
|    iterations           | 28         |
|    time_elapsed         | 882        |
|    total_timesteps      | 458752     |
| train/                  |            |
|    approx_kl            | 0.02170115 |
|    clip_fraction        | 0.261      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.63      |
|    explained_variance   | 0.847      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.12      |
|    n_updates            | 270        |
|    policy_gradient_loss | -0.0376    |
|    value_loss           | 0.00112    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.77e+03   |
| time/                   |             |
|    fps                  | 522         |
|    iterations           | 29          |
|    time_elapsed         | 910         |
|    total_timesteps      | 475136      |
| train/                  |             |
|    approx_kl            | 0.021933889 |
|    clip_fraction        | 0.248       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.52       |
|    explained_variance   | 0.833       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.12       |
|    n_updates            | 280         |
|    policy_gradient_loss | -0.0369     |
|    value_loss           | 0.00129     |
-----------------------------------------

Eval num_timesteps=480000, episode_reward=-544.10 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -544        |
| time/                   |             |
|    total_timesteps      | 480000      |
| train/                  |             |
|    approx_kl            | 0.021217186 |
|    clip_fraction        | 0.257       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.34       |
|    explained_variance   | 0.854       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.113      |
|    n_updates            | 290         |
|    policy_gradient_loss | -0.0373     |
|    value_loss           | 0.000827    |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -1.63e+03 |
| time/              |           |
|    fps             | 522       |
|    iterations      | 30        |
|    time_elapsed    | 941       |
|    total_timesteps | 491520    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.52e+03   |
| time/                   |             |
|    fps                  | 523         |
|    iterations           | 31          |
|    time_elapsed         | 969         |
|    total_timesteps      | 507904      |
| train/                  |             |
|    approx_kl            | 0.021984305 |
|    clip_fraction        | 0.273       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.2        |
|    explained_variance   | 0.888       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.115      |
|    n_updates            | 300         |
|    policy_gradient_loss | -0.0383     |
|    value_loss           | 0.000612    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -1.44e+03  |
| time/                   |            |
|    fps                  | 523        |
|    iterations           | 32         |
|    time_elapsed         | 1001       |
|    total_timesteps      | 524288     |
| train/                  |            |
|    approx_kl            | 0.02157136 |
|    clip_fraction        | 0.258      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.1       |
|    explained_variance   | 0.879      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.103     |
|    n_updates            | 310        |
|    policy_gradient_loss | -0.0363    |
|    value_loss           | 0.000714   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.4e+03    |
| time/                   |             |
|    fps                  | 525         |
|    iterations           | 33          |
|    time_elapsed         | 1029        |
|    total_timesteps      | 540672      |
| train/                  |             |
|    approx_kl            | 0.022049315 |
|    clip_fraction        | 0.263       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.01       |
|    explained_variance   | 0.881       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.133      |
|    n_updates            | 320         |
|    policy_gradient_loss | -0.0377     |
|    value_loss           | 0.000667    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -1.37e+03  |
| time/                   |            |
|    fps                  | 526        |
|    iterations           | 34         |
|    time_elapsed         | 1058       |
|    total_timesteps      | 557056     |
| train/                  |            |
|    approx_kl            | 0.02063596 |
|    clip_fraction        | 0.239      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.94      |
|    explained_variance   | 0.893      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0696    |
|    n_updates            | 330        |
|    policy_gradient_loss | -0.0354    |
|    value_loss           | 0.000665   |
----------------------------------------

Eval num_timesteps=560000, episode_reward=-1003.76 +/- 0.00

Episode length: 480.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 480        |
|    mean_reward          | -1e+03     |
| time/                   |            |
|    total_timesteps      | 560000     |
| train/                  |            |
|    approx_kl            | 0.02150767 |
|    clip_fraction        | 0.248      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.91      |
|    explained_variance   | 0.924      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.115     |
|    n_updates            | 340        |
|    policy_gradient_loss | -0.0366    |
|    value_loss           | 0.000757   |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -1.32e+03 |
| time/              |           |
|    fps             | 526       |
|    iterations      | 35        |
|    time_elapsed    | 1088      |
|    total_timesteps | 573440    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.25e+03   |
| time/                   |             |
|    fps                  | 528         |
|    iterations           | 36          |
|    time_elapsed         | 1116        |
|    total_timesteps      | 589824      |
| train/                  |             |
|    approx_kl            | 0.021274984 |
|    clip_fraction        | 0.243       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.74       |
|    explained_variance   | 0.923       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.087      |
|    n_updates            | 350         |
|    policy_gradient_loss | -0.0362     |
|    value_loss           | 0.00064     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.16e+03   |
| time/                   |             |
|    fps                  | 526         |
|    iterations           | 37          |
|    time_elapsed         | 1150        |
|    total_timesteps      | 606208      |
| train/                  |             |
|    approx_kl            | 0.020177895 |
|    clip_fraction        | 0.243       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.58       |
|    explained_variance   | 0.934       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.132      |
|    n_updates            | 360         |
|    policy_gradient_loss | -0.0342     |
|    value_loss           | 0.000488    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.09e+03   |
| time/                   |             |
|    fps                  | 525         |
|    iterations           | 38          |
|    time_elapsed         | 1183        |
|    total_timesteps      | 622592      |
| train/                  |             |
|    approx_kl            | 0.021221306 |
|    clip_fraction        | 0.237       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.58       |
|    explained_variance   | 0.92        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0756     |
|    n_updates            | 370         |
|    policy_gradient_loss | -0.0347     |
|    value_loss           | 0.000585    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.06e+03   |
| time/                   |             |
|    fps                  | 526         |
|    iterations           | 39          |
|    time_elapsed         | 1214        |
|    total_timesteps      | 638976      |
| train/                  |             |
|    approx_kl            | 0.019977711 |
|    clip_fraction        | 0.229       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.51       |
|    explained_variance   | 0.909       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.114      |
|    n_updates            | 380         |
|    policy_gradient_loss | -0.034      |
|    value_loss           | 0.000667    |
-----------------------------------------

Eval num_timesteps=640000, episode_reward=-684.41 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -684        |
| time/                   |             |
|    total_timesteps      | 640000      |
| train/                  |             |
|    approx_kl            | 0.020103559 |
|    clip_fraction        | 0.235       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.35       |
|    explained_variance   | 0.93        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.107      |
|    n_updates            | 390         |
|    policy_gradient_loss | -0.0344     |
|    value_loss           | 0.000494    |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -1.03e+03 |
| time/              |           |
|    fps             | 525       |
|    iterations      | 40        |
|    time_elapsed    | 1246      |
|    total_timesteps | 655360    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -977       |
| time/                   |            |
|    fps                  | 526        |
|    iterations           | 41         |
|    time_elapsed         | 1275       |
|    total_timesteps      | 671744     |
| train/                  |            |
|    approx_kl            | 0.02095431 |
|    clip_fraction        | 0.239      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.35      |
|    explained_variance   | 0.941      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.109     |
|    n_updates            | 400        |
|    policy_gradient_loss | -0.0365    |
|    value_loss           | 0.000472   |
----------------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 480       |
|    ep_rew_mean          | -940      |
| time/                   |           |
|    fps                  | 527       |
|    iterations           | 42        |
|    time_elapsed         | 1304      |
|    total_timesteps      | 688128    |
| train/                  |           |
|    approx_kl            | 0.0189343 |
|    clip_fraction        | 0.226     |
|    clip_range           | 0.2       |
|    entropy_loss         | -5.16     |
|    explained_variance   | 0.935     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.0939   |
|    n_updates            | 410       |
|    policy_gradient_loss | -0.0332   |
|    value_loss           | 0.000359  |
---------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -858        |
| time/                   |             |
|    fps                  | 522         |
|    iterations           | 43          |
|    time_elapsed         | 1348        |
|    total_timesteps      | 704512      |
| train/                  |             |
|    approx_kl            | 0.022040924 |
|    clip_fraction        | 0.244       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.11       |
|    explained_variance   | 0.92        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.106      |
|    n_updates            | 420         |
|    policy_gradient_loss | -0.0341     |
|    value_loss           | 0.000361    |
-----------------------------------------

Eval num_timesteps=720000, episode_reward=-636.55 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -637        |
| time/                   |             |
|    total_timesteps      | 720000      |
| train/                  |             |
|    approx_kl            | 0.021194356 |
|    clip_fraction        | 0.246       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.97       |
|    explained_variance   | 0.931       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0743     |
|    n_updates            | 430         |
|    policy_gradient_loss | -0.0353     |
|    value_loss           | 0.000252    |
-----------------------------------------

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 480      |
|    ep_rew_mean     | -847     |
| time/              |          |
|    fps             | 519      |
|    iterations      | 44       |
|    time_elapsed    | 1386     |
|    total_timesteps | 720896   |
---------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -813        |
| time/                   |             |
|    fps                  | 519         |
|    iterations           | 45          |
|    time_elapsed         | 1417        |
|    total_timesteps      | 737280      |
| train/                  |             |
|    approx_kl            | 0.021184485 |
|    clip_fraction        | 0.222       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.92       |
|    explained_variance   | 0.933       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0774     |
|    n_updates            | 440         |
|    policy_gradient_loss | -0.0328     |
|    value_loss           | 0.000383    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -807       |
| time/                   |            |
|    fps                  | 514        |
|    iterations           | 46         |
|    time_elapsed         | 1463       |
|    total_timesteps      | 753664     |
| train/                  |            |
|    approx_kl            | 0.02133053 |
|    clip_fraction        | 0.226      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.85      |
|    explained_variance   | 0.927      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.103     |
|    n_updates            | 450        |
|    policy_gradient_loss | -0.0343    |
|    value_loss           | 0.00043    |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -810       |
| time/                   |            |
|    fps                  | 513        |
|    iterations           | 47         |
|    time_elapsed         | 1500       |
|    total_timesteps      | 770048     |
| train/                  |            |
|    approx_kl            | 0.02054927 |
|    clip_fraction        | 0.217      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.75      |
|    explained_variance   | 0.928      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0863    |
|    n_updates            | 460        |
|    policy_gradient_loss | -0.0303    |
|    value_loss           | 0.000716   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -768        |
| time/                   |             |
|    fps                  | 513         |
|    iterations           | 48          |
|    time_elapsed         | 1530        |
|    total_timesteps      | 786432      |
| train/                  |             |
|    approx_kl            | 0.021625338 |
|    clip_fraction        | 0.232       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.79       |
|    explained_variance   | 0.921       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0792     |
|    n_updates            | 470         |
|    policy_gradient_loss | -0.035      |
|    value_loss           | 0.000719    |
-----------------------------------------

Eval num_timesteps=800000, episode_reward=-1142.80 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -1.14e+03   |
| time/                   |             |
|    total_timesteps      | 800000      |
| train/                  |             |
|    approx_kl            | 0.020064536 |
|    clip_fraction        | 0.23        |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.61       |
|    explained_variance   | 0.921       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0813     |
|    n_updates            | 480         |
|    policy_gradient_loss | -0.0331     |
|    value_loss           | 0.000346    |
-----------------------------------------

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 480      |
|    ep_rew_mean     | -735     |
| time/              |          |
|    fps             | 513      |
|    iterations      | 49       |
|    time_elapsed    | 1563     |
|    total_timesteps | 802816   |
---------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -705        |
| time/                   |             |
|    fps                  | 514         |
|    iterations           | 50          |
|    time_elapsed         | 1593        |
|    total_timesteps      | 819200      |
| train/                  |             |
|    approx_kl            | 0.020987527 |
|    clip_fraction        | 0.219       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.61       |
|    explained_variance   | 0.95        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0934     |
|    n_updates            | 490         |
|    policy_gradient_loss | -0.0318     |
|    value_loss           | 0.000518    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -692        |
| time/                   |             |
|    fps                  | 514         |
|    iterations           | 51          |
|    time_elapsed         | 1622        |
|    total_timesteps      | 835584      |
| train/                  |             |
|    approx_kl            | 0.020577814 |
|    clip_fraction        | 0.217       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.53       |
|    explained_variance   | 0.932       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0569     |
|    n_updates            | 500         |
|    policy_gradient_loss | -0.033      |
|    value_loss           | 0.000555    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -638        |
| time/                   |             |
|    fps                  | 511         |
|    iterations           | 52          |
|    time_elapsed         | 1665        |
|    total_timesteps      | 851968      |
| train/                  |             |
|    approx_kl            | 0.019933335 |
|    clip_fraction        | 0.223       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.39       |
|    explained_variance   | 0.934       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0912     |
|    n_updates            | 510         |
|    policy_gradient_loss | -0.0312     |
|    value_loss           | 0.00034     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -589        |
| time/                   |             |
|    fps                  | 502         |
|    iterations           | 53          |
|    time_elapsed         | 1728        |
|    total_timesteps      | 868352      |
| train/                  |             |
|    approx_kl            | 0.020367464 |
|    clip_fraction        | 0.216       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.36       |
|    explained_variance   | 0.94        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0989     |
|    n_updates            | 520         |
|    policy_gradient_loss | -0.0316     |
|    value_loss           | 0.000271    |
-----------------------------------------

Eval num_timesteps=880000, episode_reward=-2975.63 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -2.98e+03   |
| time/                   |             |
|    total_timesteps      | 880000      |
| train/                  |             |
|    approx_kl            | 0.020046953 |
|    clip_fraction        | 0.214       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.3        |
|    explained_variance   | 0.944       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0802     |
|    n_updates            | 530         |
|    policy_gradient_loss | -0.0306     |
|    value_loss           | 0.000207    |
-----------------------------------------

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 480      |
|    ep_rew_mean     | -587     |
| time/              |          |
|    fps             | 495      |
|    iterations      | 54       |
|    time_elapsed    | 1786     |
|    total_timesteps | 884736   |
---------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -596        |
| time/                   |             |
|    fps                  | 491         |
|    iterations           | 55          |
|    time_elapsed         | 1832        |
|    total_timesteps      | 901120      |
| train/                  |             |
|    approx_kl            | 0.021099512 |
|    clip_fraction        | 0.217       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.22       |
|    explained_variance   | 0.93        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0528     |
|    n_updates            | 540         |
|    policy_gradient_loss | -0.0323     |
|    value_loss           | 0.000288    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -600        |
| time/                   |             |
|    fps                  | 489         |
|    iterations           | 56          |
|    time_elapsed         | 1874        |
|    total_timesteps      | 917504      |
| train/                  |             |
|    approx_kl            | 0.020711765 |
|    clip_fraction        | 0.204       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.23       |
|    explained_variance   | 0.934       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.075      |
|    n_updates            | 550         |
|    policy_gradient_loss | -0.0339     |
|    value_loss           | 0.000422    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -571        |
| time/                   |             |
|    fps                  | 488         |
|    iterations           | 57          |
|    time_elapsed         | 1910        |
|    total_timesteps      | 933888      |
| train/                  |             |
|    approx_kl            | 0.021503251 |
|    clip_fraction        | 0.225       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.12       |
|    explained_variance   | 0.951       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0845     |
|    n_updates            | 560         |
|    policy_gradient_loss | -0.0345     |
|    value_loss           | 0.000449    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -542       |
| time/                   |            |
|    fps                  | 487        |
|    iterations           | 58         |
|    time_elapsed         | 1949       |
|    total_timesteps      | 950272     |
| train/                  |            |
|    approx_kl            | 0.02011887 |
|    clip_fraction        | 0.207      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.01      |
|    explained_variance   | 0.911      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0779    |
|    n_updates            | 570        |
|    policy_gradient_loss | -0.0324    |
|    value_loss           | 0.000422   |
----------------------------------------

Eval num_timesteps=960000, episode_reward=-4096.63 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -4.1e+03    |
| time/                   |             |
|    total_timesteps      | 960000      |
| train/                  |             |
|    approx_kl            | 0.020462781 |
|    clip_fraction        | 0.214       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.02       |
|    explained_variance   | 0.932       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.046      |
|    n_updates            | 580         |
|    policy_gradient_loss | -0.0337     |
|    value_loss           | 0.000396    |
-----------------------------------------

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 480      |
|    ep_rew_mean     | -557     |
| time/              |          |
|    fps             | 486      |
|    iterations      | 59       |
|    time_elapsed    | 1986     |
|    total_timesteps | 966656   |
---------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -566       |
| time/                   |            |
|    fps                  | 487        |
|    iterations           | 60         |
|    time_elapsed         | 2017       |
|    total_timesteps      | 983040     |
| train/                  |            |
|    approx_kl            | 0.02096773 |
|    clip_fraction        | 0.215      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.1       |
|    explained_variance   | 0.941      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0785    |
|    n_updates            | 590        |
|    policy_gradient_loss | -0.0331    |
|    value_loss           | 0.00053    |
----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -552       |
| time/                   |            |
|    fps                  | 485        |
|    iterations           | 61         |
|    time_elapsed         | 2057       |
|    total_timesteps      | 999424     |
| train/                  |            |
|    approx_kl            | 0.02150579 |
|    clip_fraction        | 0.201      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.94      |
|    explained_variance   | 0.931      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0711    |
|    n_updates            | 600        |
|    policy_gradient_loss | -0.0331    |
|    value_loss           | 0.000511   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -528        |
| time/                   |             |
|    fps                  | 484         |
|    iterations           | 62          |
|    time_elapsed         | 2096        |
|    total_timesteps      | 1015808     |
| train/                  |             |
|    approx_kl            | 0.021646142 |
|    clip_fraction        | 0.198       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.9        |
|    explained_variance   | 0.901       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0964     |
|    n_updates            | 610         |
|    policy_gradient_loss | -0.0316     |
|    value_loss           | 0.000541    |
-----------------------------------------

Training completed in 0:35:09.957944
Model saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\rl_models\ppo_overload.zip
VecNormalize saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\rl_models\ppo_overload_vecnormalize.pkl

============================================================
Training PPO for scenario: COST
============================================================
Latest model: models\random_forest_cpu_total_usage_20251111_221930.pkl
✓ Model loaded: models\random_forest_cpu_total_usage_20251111_221930.pkl
  Model: random_forest
  Target: cpu_total_usage
  Saved at: 2025-11-11 22:19:30
Latest model: models\svr_memory_usage_pct_20251111_184735.pkl
✓ Model loaded: models\svr_memory_usage_pct_20251111_184735.pkl
  Model: svr
  Target: memory_usage_pct
  Saved at: 2025-11-11 18:47:35
Latest model: models\random_forest_system_load_20251111_221944.pkl
✓ Model loaded: models\random_forest_system_load_20251111_221944.pkl
  Model: random_forest
  Target: system_load
  Saved at: 2025-11-11 22:19:44
Creating new PPO model
Using cpu device

Starting training for 1,000,000 timesteps...
Logging to ./tensorboard_logs/PPO_10

Output()

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -2.01e+04 |
| time/              |           |
|    fps             | 703       |
|    iterations      | 1         |
|    time_elapsed    | 23        |
|    total_timesteps | 16384     |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -2e+04      |
| time/                   |             |
|    fps                  | 546         |
|    iterations           | 2           |
|    time_elapsed         | 59          |
|    total_timesteps      | 32768       |
| train/                  |             |
|    approx_kl            | 0.016878726 |
|    clip_fraction        | 0.191       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.58       |
|    explained_variance   | -0.0636     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0671     |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0283     |
|    value_loss           | 0.181       |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.97e+04   |
| time/                   |             |
|    fps                  | 504         |
|    iterations           | 3           |
|    time_elapsed         | 97          |
|    total_timesteps      | 49152       |
| train/                  |             |
|    approx_kl            | 0.018575802 |
|    clip_fraction        | 0.226       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.56       |
|    explained_variance   | 0.396       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.149      |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.0348     |
|    value_loss           | 0.0181      |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.9e+04    |
| time/                   |             |
|    fps                  | 486         |
|    iterations           | 4           |
|    time_elapsed         | 134         |
|    total_timesteps      | 65536       |
| train/                  |             |
|    approx_kl            | 0.020124508 |
|    clip_fraction        | 0.265       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.53       |
|    explained_variance   | 0.492       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.163      |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.0383     |
|    value_loss           | 0.0101      |
-----------------------------------------

Eval num_timesteps=80000, episode_reward=-13415.93 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -1.34e+04   |
| time/                   |             |
|    total_timesteps      | 80000       |
| train/                  |             |
|    approx_kl            | 0.021151269 |
|    clip_fraction        | 0.286       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.48       |
|    explained_variance   | 0.439       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.148      |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0415     |
|    value_loss           | 0.00789     |
-----------------------------------------

New best mean reward!

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 480      |
|    ep_rew_mean     | -1.8e+04 |
| time/              |          |
|    fps             | 467      |
|    iterations      | 5        |
|    time_elapsed    | 175      |
|    total_timesteps | 81920    |
---------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.71e+04   |
| time/                   |             |
|    fps                  | 466         |
|    iterations           | 6           |
|    time_elapsed         | 210         |
|    total_timesteps      | 98304       |
| train/                  |             |
|    approx_kl            | 0.021776939 |
|    clip_fraction        | 0.332       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.4        |
|    explained_variance   | 0.501       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.141      |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.0451     |
|    value_loss           | 0.00552     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -1.6e+04   |
| time/                   |            |
|    fps                  | 463        |
|    iterations           | 7          |
|    time_elapsed         | 247        |
|    total_timesteps      | 114688     |
| train/                  |            |
|    approx_kl            | 0.02519817 |
|    clip_fraction        | 0.327      |
|    clip_range           | 0.2        |
|    entropy_loss         | -9.33      |
|    explained_variance   | 0.438      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.124     |
|    n_updates            | 60         |
|    policy_gradient_loss | -0.0477    |
|    value_loss           | 0.00495    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.48e+04   |
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 8           |
|    time_elapsed         | 283         |
|    total_timesteps      | 131072      |
| train/                  |             |
|    approx_kl            | 0.025087092 |
|    clip_fraction        | 0.336       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.23       |
|    explained_variance   | 0.474       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.15       |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.0474     |
|    value_loss           | 0.00427     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.36e+04   |
| time/                   |             |
|    fps                  | 469         |
|    iterations           | 9           |
|    time_elapsed         | 313         |
|    total_timesteps      | 147456      |
| train/                  |             |
|    approx_kl            | 0.025181688 |
|    clip_fraction        | 0.33        |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.12       |
|    explained_variance   | 0.599       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.131      |
|    n_updates            | 80          |
|    policy_gradient_loss | -0.0485     |
|    value_loss           | 0.0034      |
-----------------------------------------

Eval num_timesteps=160000, episode_reward=-12585.34 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -1.26e+04   |
| time/                   |             |
|    total_timesteps      | 160000      |
| train/                  |             |
|    approx_kl            | 0.025861278 |
|    clip_fraction        | 0.332       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.98       |
|    explained_variance   | 0.723       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.128      |
|    n_updates            | 90          |
|    policy_gradient_loss | -0.0489     |
|    value_loss           | 0.00327     |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -1.27e+04 |
| time/              |           |
|    fps             | 472       |
|    iterations      | 10        |
|    time_elapsed    | 346       |
|    total_timesteps | 163840    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.17e+04   |
| time/                   |             |
|    fps                  | 477         |
|    iterations           | 11          |
|    time_elapsed         | 377         |
|    total_timesteps      | 180224      |
| train/                  |             |
|    approx_kl            | 0.023803754 |
|    clip_fraction        | 0.317       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.89       |
|    explained_variance   | 0.781       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.134      |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.0466     |
|    value_loss           | 0.00354     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.06e+04   |
| time/                   |             |
|    fps                  | 478         |
|    iterations           | 12          |
|    time_elapsed         | 410         |
|    total_timesteps      | 196608      |
| train/                  |             |
|    approx_kl            | 0.025394801 |
|    clip_fraction        | 0.32        |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.72       |
|    explained_variance   | 0.874       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.144      |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.0466     |
|    value_loss           | 0.00272     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -9.77e+03   |
| time/                   |             |
|    fps                  | 482         |
|    iterations           | 13          |
|    time_elapsed         | 441         |
|    total_timesteps      | 212992      |
| train/                  |             |
|    approx_kl            | 0.022567376 |
|    clip_fraction        | 0.304       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.6        |
|    explained_variance   | 0.867       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.149      |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.0454     |
|    value_loss           | 0.00266     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -8.97e+03   |
| time/                   |             |
|    fps                  | 480         |
|    iterations           | 14          |
|    time_elapsed         | 477         |
|    total_timesteps      | 229376      |
| train/                  |             |
|    approx_kl            | 0.023803946 |
|    clip_fraction        | 0.31        |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.46       |
|    explained_variance   | 0.855       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.136      |
|    n_updates            | 130         |
|    policy_gradient_loss | -0.0462     |
|    value_loss           | 0.00242     |
-----------------------------------------

Eval num_timesteps=240000, episode_reward=-9595.97 +/- 0.00

Episode length: 480.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 480        |
|    mean_reward          | -9.6e+03   |
| time/                   |            |
|    total_timesteps      | 240000     |
| train/                  |            |
|    approx_kl            | 0.02288036 |
|    clip_fraction        | 0.301      |
|    clip_range           | 0.2        |
|    entropy_loss         | -8.33      |
|    explained_variance   | 0.894      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.119     |
|    n_updates            | 140        |
|    policy_gradient_loss | -0.0447    |
|    value_loss           | 0.00216    |
----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -8.22e+03 |
| time/              |           |
|    fps             | 475       |
|    iterations      | 15        |
|    time_elapsed    | 516       |
|    total_timesteps | 245760    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -7.62e+03   |
| time/                   |             |
|    fps                  | 477         |
|    iterations           | 16          |
|    time_elapsed         | 549         |
|    total_timesteps      | 262144      |
| train/                  |             |
|    approx_kl            | 0.022804365 |
|    clip_fraction        | 0.3         |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.17       |
|    explained_variance   | 0.869       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.133      |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.0441     |
|    value_loss           | 0.0019      |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -7.12e+03   |
| time/                   |             |
|    fps                  | 474         |
|    iterations           | 17          |
|    time_elapsed         | 587         |
|    total_timesteps      | 278528      |
| train/                  |             |
|    approx_kl            | 0.022170935 |
|    clip_fraction        | 0.294       |
|    clip_range           | 0.2         |
|    entropy_loss         | -8.07       |
|    explained_variance   | 0.891       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.136      |
|    n_updates            | 160         |
|    policy_gradient_loss | -0.0428     |
|    value_loss           | 0.00205     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -6.57e+03  |
| time/                   |            |
|    fps                  | 471        |
|    iterations           | 18         |
|    time_elapsed         | 624        |
|    total_timesteps      | 294912     |
| train/                  |            |
|    approx_kl            | 0.02231095 |
|    clip_fraction        | 0.282      |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.91      |
|    explained_variance   | 0.895      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.116     |
|    n_updates            | 170        |
|    policy_gradient_loss | -0.0419    |
|    value_loss           | 0.00184    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -6.03e+03   |
| time/                   |             |
|    fps                  | 469         |
|    iterations           | 19          |
|    time_elapsed         | 663         |
|    total_timesteps      | 311296      |
| train/                  |             |
|    approx_kl            | 0.021804417 |
|    clip_fraction        | 0.275       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.78       |
|    explained_variance   | 0.887       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.132      |
|    n_updates            | 180         |
|    policy_gradient_loss | -0.0405     |
|    value_loss           | 0.00164     |
-----------------------------------------

Eval num_timesteps=320000, episode_reward=-12796.61 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -1.28e+04   |
| time/                   |             |
|    total_timesteps      | 320000      |
| train/                  |             |
|    approx_kl            | 0.021853264 |
|    clip_fraction        | 0.285       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.66       |
|    explained_variance   | 0.872       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.155      |
|    n_updates            | 190         |
|    policy_gradient_loss | -0.0395     |
|    value_loss           | 0.00152     |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -5.72e+03 |
| time/              |           |
|    fps             | 467       |
|    iterations      | 20        |
|    time_elapsed    | 701       |
|    total_timesteps | 327680    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -5.42e+03   |
| time/                   |             |
|    fps                  | 466         |
|    iterations           | 21          |
|    time_elapsed         | 737         |
|    total_timesteps      | 344064      |
| train/                  |             |
|    approx_kl            | 0.021368053 |
|    clip_fraction        | 0.267       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.57       |
|    explained_variance   | 0.9         |
|    learning_rate        | 0.0003      |
|    loss                 | -0.109      |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.0379     |
|    value_loss           | 0.00141     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -5.15e+03   |
| time/                   |             |
|    fps                  | 465         |
|    iterations           | 22          |
|    time_elapsed         | 774         |
|    total_timesteps      | 360448      |
| train/                  |             |
|    approx_kl            | 0.021334726 |
|    clip_fraction        | 0.288       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.4        |
|    explained_variance   | 0.903       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.151      |
|    n_updates            | 210         |
|    policy_gradient_loss | -0.0405     |
|    value_loss           | 0.00106     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -4.73e+03   |
| time/                   |             |
|    fps                  | 464         |
|    iterations           | 23          |
|    time_elapsed         | 810         |
|    total_timesteps      | 376832      |
| train/                  |             |
|    approx_kl            | 0.022261146 |
|    clip_fraction        | 0.277       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.35       |
|    explained_variance   | 0.881       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.112      |
|    n_updates            | 220         |
|    policy_gradient_loss | -0.0409     |
|    value_loss           | 0.00104     |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -4.41e+03  |
| time/                   |            |
|    fps                  | 464        |
|    iterations           | 24         |
|    time_elapsed         | 846        |
|    total_timesteps      | 393216     |
| train/                  |            |
|    approx_kl            | 0.02186541 |
|    clip_fraction        | 0.279      |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.16      |
|    explained_variance   | 0.875      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.127     |
|    n_updates            | 230        |
|    policy_gradient_loss | -0.0391    |
|    value_loss           | 0.00107    |
----------------------------------------

Eval num_timesteps=400000, episode_reward=-16786.68 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -1.68e+04   |
| time/                   |             |
|    total_timesteps      | 400000      |
| train/                  |             |
|    approx_kl            | 0.021920804 |
|    clip_fraction        | 0.277       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.96       |
|    explained_variance   | 0.863       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.135      |
|    n_updates            | 240         |
|    policy_gradient_loss | -0.0401     |
|    value_loss           | 0.000741    |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -4.03e+03 |
| time/              |           |
|    fps             | 464       |
|    iterations      | 25        |
|    time_elapsed    | 882       |
|    total_timesteps | 409600    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -3.85e+03   |
| time/                   |             |
|    fps                  | 464         |
|    iterations           | 26          |
|    time_elapsed         | 916         |
|    total_timesteps      | 425984      |
| train/                  |             |
|    approx_kl            | 0.021495061 |
|    clip_fraction        | 0.276       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.84       |
|    explained_variance   | 0.865       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.114      |
|    n_updates            | 250         |
|    policy_gradient_loss | -0.04       |
|    value_loss           | 0.000696    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -3.72e+03   |
| time/                   |             |
|    fps                  | 466         |
|    iterations           | 27          |
|    time_elapsed         | 948         |
|    total_timesteps      | 442368      |
| train/                  |             |
|    approx_kl            | 0.021137469 |
|    clip_fraction        | 0.266       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.79       |
|    explained_variance   | 0.889       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0988     |
|    n_updates            | 260         |
|    policy_gradient_loss | -0.038      |
|    value_loss           | 0.000871    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -3.77e+03   |
| time/                   |             |
|    fps                  | 468         |
|    iterations           | 28          |
|    time_elapsed         | 978         |
|    total_timesteps      | 458752      |
| train/                  |             |
|    approx_kl            | 0.022319201 |
|    clip_fraction        | 0.266       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.68       |
|    explained_variance   | 0.908       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.119      |
|    n_updates            | 270         |
|    policy_gradient_loss | -0.0363     |
|    value_loss           | 0.00106     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -3.67e+03   |
| time/                   |             |
|    fps                  | 470         |
|    iterations           | 29          |
|    time_elapsed         | 1008        |
|    total_timesteps      | 475136      |
| train/                  |             |
|    approx_kl            | 0.021132436 |
|    clip_fraction        | 0.25        |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.74       |
|    explained_variance   | 0.915       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0871     |
|    n_updates            | 280         |
|    policy_gradient_loss | -0.0343     |
|    value_loss           | 0.00201     |
-----------------------------------------

Eval num_timesteps=480000, episode_reward=-10501.85 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -1.05e+04   |
| time/                   |             |
|    total_timesteps      | 480000      |
| train/                  |             |
|    approx_kl            | 0.022438187 |
|    clip_fraction        | 0.268       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.52       |
|    explained_variance   | 0.939       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0915     |
|    n_updates            | 290         |
|    policy_gradient_loss | -0.0377     |
|    value_loss           | 0.00139     |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -3.35e+03 |
| time/              |           |
|    fps             | 468       |
|    iterations      | 30        |
|    time_elapsed    | 1049      |
|    total_timesteps | 491520    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -3.08e+03  |
| time/                   |            |
|    fps                  | 469        |
|    iterations           | 31         |
|    time_elapsed         | 1082       |
|    total_timesteps      | 507904     |
| train/                  |            |
|    approx_kl            | 0.01944906 |
|    clip_fraction        | 0.242      |
|    clip_range           | 0.2        |
|    entropy_loss         | -6.27      |
|    explained_variance   | 0.904      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.104     |
|    n_updates            | 300        |
|    policy_gradient_loss | -0.0364    |
|    value_loss           | 0.00065    |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -2.86e+03   |
| time/                   |             |
|    fps                  | 469         |
|    iterations           | 32          |
|    time_elapsed         | 1117        |
|    total_timesteps      | 524288      |
| train/                  |             |
|    approx_kl            | 0.023133676 |
|    clip_fraction        | 0.241       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.31       |
|    explained_variance   | 0.932       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.1        |
|    n_updates            | 310         |
|    policy_gradient_loss | -0.0337     |
|    value_loss           | 0.00171     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -2.99e+03   |
| time/                   |             |
|    fps                  | 470         |
|    iterations           | 33          |
|    time_elapsed         | 1149        |
|    total_timesteps      | 540672      |
| train/                  |             |
|    approx_kl            | 0.021312546 |
|    clip_fraction        | 0.248       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.17       |
|    explained_variance   | 0.969       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.12       |
|    n_updates            | 320         |
|    policy_gradient_loss | -0.0338     |
|    value_loss           | 0.00107     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -2.72e+03   |
| time/                   |             |
|    fps                  | 471         |
|    iterations           | 34          |
|    time_elapsed         | 1181        |
|    total_timesteps      | 557056      |
| train/                  |             |
|    approx_kl            | 0.019773744 |
|    clip_fraction        | 0.245       |
|    clip_range           | 0.2         |
|    entropy_loss         | -6.09       |
|    explained_variance   | 0.959       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.118      |
|    n_updates            | 330         |
|    policy_gradient_loss | -0.0317     |
|    value_loss           | 0.00182     |
-----------------------------------------

Eval num_timesteps=560000, episode_reward=-12205.50 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -1.22e+04   |
| time/                   |             |
|    total_timesteps      | 560000      |
| train/                  |             |
|    approx_kl            | 0.019803282 |
|    clip_fraction        | 0.235       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.98       |
|    explained_variance   | 0.944       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0581     |
|    n_updates            | 340         |
|    policy_gradient_loss | -0.0308     |
|    value_loss           | 0.0014      |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -2.76e+03 |
| time/              |           |
|    fps             | 470       |
|    iterations      | 35        |
|    time_elapsed    | 1217      |
|    total_timesteps | 573440    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -2.64e+03   |
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 36          |
|    time_elapsed         | 1248        |
|    total_timesteps      | 589824      |
| train/                  |             |
|    approx_kl            | 0.021914778 |
|    clip_fraction        | 0.237       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.97       |
|    explained_variance   | 0.963       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.11       |
|    n_updates            | 350         |
|    policy_gradient_loss | -0.0349     |
|    value_loss           | 0.00119     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -2.62e+03   |
| time/                   |             |
|    fps                  | 474         |
|    iterations           | 37          |
|    time_elapsed         | 1277        |
|    total_timesteps      | 606208      |
| train/                  |             |
|    approx_kl            | 0.020927874 |
|    clip_fraction        | 0.246       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.87       |
|    explained_variance   | 0.976       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.13       |
|    n_updates            | 360         |
|    policy_gradient_loss | -0.0355     |
|    value_loss           | 0.00135     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -2.66e+03   |
| time/                   |             |
|    fps                  | 476         |
|    iterations           | 38          |
|    time_elapsed         | 1306        |
|    total_timesteps      | 622592      |
| train/                  |             |
|    approx_kl            | 0.021079399 |
|    clip_fraction        | 0.238       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.76       |
|    explained_variance   | 0.976       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.108      |
|    n_updates            | 370         |
|    policy_gradient_loss | -0.0349     |
|    value_loss           | 0.00135     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -2.52e+03   |
| time/                   |             |
|    fps                  | 477         |
|    iterations           | 39          |
|    time_elapsed         | 1338        |
|    total_timesteps      | 638976      |
| train/                  |             |
|    approx_kl            | 0.022106811 |
|    clip_fraction        | 0.241       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.85       |
|    explained_variance   | 0.981       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.124      |
|    n_updates            | 380         |
|    policy_gradient_loss | -0.0354     |
|    value_loss           | 0.00219     |
-----------------------------------------

Eval num_timesteps=640000, episode_reward=-11883.16 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -1.19e+04   |
| time/                   |             |
|    total_timesteps      | 640000      |
| train/                  |             |
|    approx_kl            | 0.018828098 |
|    clip_fraction        | 0.225       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.55       |
|    explained_variance   | 0.978       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.114      |
|    n_updates            | 390         |
|    policy_gradient_loss | -0.0329     |
|    value_loss           | 0.00113     |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -2.42e+03 |
| time/              |           |
|    fps             | 476       |
|    iterations      | 40        |
|    time_elapsed    | 1376      |
|    total_timesteps | 655360    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -1.95e+03  |
| time/                   |            |
|    fps                  | 477        |
|    iterations           | 41         |
|    time_elapsed         | 1406       |
|    total_timesteps      | 671744     |
| train/                  |            |
|    approx_kl            | 0.01944584 |
|    clip_fraction        | 0.218      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.55      |
|    explained_variance   | 0.985      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0922    |
|    n_updates            | 400        |
|    policy_gradient_loss | -0.0321    |
|    value_loss           | 0.0012     |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.75e+03   |
| time/                   |             |
|    fps                  | 479         |
|    iterations           | 42          |
|    time_elapsed         | 1436        |
|    total_timesteps      | 688128      |
| train/                  |             |
|    approx_kl            | 0.018318241 |
|    clip_fraction        | 0.221       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.12       |
|    explained_variance   | 0.901       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.11       |
|    n_updates            | 410         |
|    policy_gradient_loss | -0.0322     |
|    value_loss           | 0.00026     |
-----------------------------------------

---------------------------------------
| rollout/                |           |
|    ep_len_mean          | 480       |
|    ep_rew_mean          | -1.65e+03 |
| time/                   |           |
|    fps                  | 480       |
|    iterations           | 43        |
|    time_elapsed         | 1465      |
|    total_timesteps      | 704512    |
| train/                  |           |
|    approx_kl            | 0.0186949 |
|    clip_fraction        | 0.207     |
|    clip_range           | 0.2       |
|    entropy_loss         | -5.17     |
|    explained_variance   | 0.974     |
|    learning_rate        | 0.0003    |
|    loss                 | -0.0962   |
|    n_updates            | 420       |
|    policy_gradient_loss | -0.032    |
|    value_loss           | 0.000493  |
---------------------------------------

Eval num_timesteps=720000, episode_reward=-15244.53 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -1.52e+04   |
| time/                   |             |
|    total_timesteps      | 720000      |
| train/                  |             |
|    approx_kl            | 0.019170778 |
|    clip_fraction        | 0.214       |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.23       |
|    explained_variance   | 0.98        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0797     |
|    n_updates            | 430         |
|    policy_gradient_loss | -0.0303     |
|    value_loss           | 0.000774    |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -1.73e+03 |
| time/              |           |
|    fps             | 481       |
|    iterations      | 44        |
|    time_elapsed    | 1497      |
|    total_timesteps | 720896    |
----------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -1.7e+03   |
| time/                   |            |
|    fps                  | 481        |
|    iterations           | 45         |
|    time_elapsed         | 1531       |
|    total_timesteps      | 737280     |
| train/                  |            |
|    approx_kl            | 0.01935833 |
|    clip_fraction        | 0.219      |
|    clip_range           | 0.2        |
|    entropy_loss         | -5.18      |
|    explained_variance   | 0.984      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0763    |
|    n_updates            | 440        |
|    policy_gradient_loss | -0.0323    |
|    value_loss           | 0.000644   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.62e+03   |
| time/                   |             |
|    fps                  | 481         |
|    iterations           | 46          |
|    time_elapsed         | 1566        |
|    total_timesteps      | 753664      |
| train/                  |             |
|    approx_kl            | 0.019887637 |
|    clip_fraction        | 0.237       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.99       |
|    explained_variance   | 0.976       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0758     |
|    n_updates            | 450         |
|    policy_gradient_loss | -0.0343     |
|    value_loss           | 0.000376    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.59e+03   |
| time/                   |             |
|    fps                  | 481         |
|    iterations           | 47          |
|    time_elapsed         | 1599        |
|    total_timesteps      | 770048      |
| train/                  |             |
|    approx_kl            | 0.020147283 |
|    clip_fraction        | 0.22        |
|    clip_range           | 0.2         |
|    entropy_loss         | -5.01       |
|    explained_variance   | 0.975       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.129      |
|    n_updates            | 460         |
|    policy_gradient_loss | -0.0324     |
|    value_loss           | 0.000457    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.58e+03   |
| time/                   |             |
|    fps                  | 480         |
|    iterations           | 48          |
|    time_elapsed         | 1636        |
|    total_timesteps      | 786432      |
| train/                  |             |
|    approx_kl            | 0.020159837 |
|    clip_fraction        | 0.205       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.99       |
|    explained_variance   | 0.98        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.101      |
|    n_updates            | 470         |
|    policy_gradient_loss | -0.0319     |
|    value_loss           | 0.000975    |
-----------------------------------------

Eval num_timesteps=800000, episode_reward=-8600.78 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -8.6e+03    |
| time/                   |             |
|    total_timesteps      | 800000      |
| train/                  |             |
|    approx_kl            | 0.019452289 |
|    clip_fraction        | 0.209       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.84       |
|    explained_variance   | 0.982       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0742     |
|    n_updates            | 480         |
|    policy_gradient_loss | -0.0317     |
|    value_loss           | 0.000567    |
-----------------------------------------

New best mean reward!

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -1.51e+03 |
| time/              |           |
|    fps             | 479       |
|    iterations      | 49        |
|    time_elapsed    | 1674      |
|    total_timesteps | 802816    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.39e+03   |
| time/                   |             |
|    fps                  | 479         |
|    iterations           | 50          |
|    time_elapsed         | 1707        |
|    total_timesteps      | 819200      |
| train/                  |             |
|    approx_kl            | 0.018814355 |
|    clip_fraction        | 0.2         |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.75       |
|    explained_variance   | 0.975       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0606     |
|    n_updates            | 490         |
|    policy_gradient_loss | -0.0316     |
|    value_loss           | 0.000513    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.32e+03   |
| time/                   |             |
|    fps                  | 479         |
|    iterations           | 51          |
|    time_elapsed         | 1741        |
|    total_timesteps      | 835584      |
| train/                  |             |
|    approx_kl            | 0.019982966 |
|    clip_fraction        | 0.215       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.72       |
|    explained_variance   | 0.963       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.093      |
|    n_updates            | 500         |
|    policy_gradient_loss | -0.0336     |
|    value_loss           | 0.000427    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.26e+03   |
| time/                   |             |
|    fps                  | 480         |
|    iterations           | 52          |
|    time_elapsed         | 1774        |
|    total_timesteps      | 851968      |
| train/                  |             |
|    approx_kl            | 0.020300254 |
|    clip_fraction        | 0.227       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.63       |
|    explained_variance   | 0.975       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.114      |
|    n_updates            | 510         |
|    policy_gradient_loss | -0.0339     |
|    value_loss           | 0.00044     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.21e+03   |
| time/                   |             |
|    fps                  | 480         |
|    iterations           | 53          |
|    time_elapsed         | 1805        |
|    total_timesteps      | 868352      |
| train/                  |             |
|    approx_kl            | 0.017863277 |
|    clip_fraction        | 0.214       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.42       |
|    explained_variance   | 0.946       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.116      |
|    n_updates            | 520         |
|    policy_gradient_loss | -0.0317     |
|    value_loss           | 0.000179    |
-----------------------------------------

Eval num_timesteps=880000, episode_reward=-10759.41 +/- 0.00

Episode length: 480.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 480         |
|    mean_reward          | -1.08e+04   |
| time/                   |             |
|    total_timesteps      | 880000      |
| train/                  |             |
|    approx_kl            | 0.019257395 |
|    clip_fraction        | 0.214       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.45       |
|    explained_variance   | 0.975       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.095      |
|    n_updates            | 530         |
|    policy_gradient_loss | -0.0319     |
|    value_loss           | 0.000288    |
-----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -1.11e+03 |
| time/              |           |
|    fps             | 479       |
|    iterations      | 54        |
|    time_elapsed    | 1843      |
|    total_timesteps | 884736    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.1e+03    |
| time/                   |             |
|    fps                  | 480         |
|    iterations           | 55          |
|    time_elapsed         | 1875        |
|    total_timesteps      | 901120      |
| train/                  |             |
|    approx_kl            | 0.019814286 |
|    clip_fraction        | 0.233       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.24       |
|    explained_variance   | 0.953       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0987     |
|    n_updates            | 540         |
|    policy_gradient_loss | -0.0349     |
|    value_loss           | 0.000156    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.04e+03   |
| time/                   |             |
|    fps                  | 480         |
|    iterations           | 56          |
|    time_elapsed         | 1908        |
|    total_timesteps      | 917504      |
| train/                  |             |
|    approx_kl            | 0.020741416 |
|    clip_fraction        | 0.216       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.34       |
|    explained_variance   | 0.969       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.109      |
|    n_updates            | 550         |
|    policy_gradient_loss | -0.0331     |
|    value_loss           | 0.000266    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -1.04e+03  |
| time/                   |            |
|    fps                  | 481        |
|    iterations           | 57         |
|    time_elapsed         | 1938       |
|    total_timesteps      | 933888     |
| train/                  |            |
|    approx_kl            | 0.01984268 |
|    clip_fraction        | 0.223      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.18      |
|    explained_variance   | 0.97       |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0971    |
|    n_updates            | 560        |
|    policy_gradient_loss | -0.0326    |
|    value_loss           | 0.000246   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -1.07e+03   |
| time/                   |             |
|    fps                  | 481         |
|    iterations           | 58          |
|    time_elapsed         | 1973        |
|    total_timesteps      | 950272      |
| train/                  |             |
|    approx_kl            | 0.019341245 |
|    clip_fraction        | 0.208       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.19       |
|    explained_variance   | 0.973       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.086      |
|    n_updates            | 570         |
|    policy_gradient_loss | -0.0317     |
|    value_loss           | 0.000247    |
-----------------------------------------

Eval num_timesteps=960000, episode_reward=-8802.46 +/- 0.00

Episode length: 480.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 480        |
|    mean_reward          | -8.8e+03   |
| time/                   |            |
|    total_timesteps      | 960000     |
| train/                  |            |
|    approx_kl            | 0.01940734 |
|    clip_fraction        | 0.207      |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.22      |
|    explained_variance   | 0.965      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.071     |
|    n_updates            | 580        |
|    policy_gradient_loss | -0.031     |
|    value_loss           | 0.000585   |
----------------------------------------

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 480       |
|    ep_rew_mean     | -1.02e+03 |
| time/              |           |
|    fps             | 480       |
|    iterations      | 59        |
|    time_elapsed    | 2010      |
|    total_timesteps | 966656    |
----------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -971        |
| time/                   |             |
|    fps                  | 480         |
|    iterations           | 60          |
|    time_elapsed         | 2044        |
|    total_timesteps      | 983040      |
| train/                  |             |
|    approx_kl            | 0.018607695 |
|    clip_fraction        | 0.207       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.01       |
|    explained_variance   | 0.972       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0711     |
|    n_updates            | 590         |
|    policy_gradient_loss | -0.0332     |
|    value_loss           | 0.000246    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 480        |
|    ep_rew_mean          | -886       |
| time/                   |            |
|    fps                  | 481        |
|    iterations           | 61         |
|    time_elapsed         | 2076       |
|    total_timesteps      | 999424     |
| train/                  |            |
|    approx_kl            | 0.01934631 |
|    clip_fraction        | 0.212      |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.95      |
|    explained_variance   | 0.97       |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0434    |
|    n_updates            | 600        |
|    policy_gradient_loss | -0.0317    |
|    value_loss           | 0.000192   |
----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 480         |
|    ep_rew_mean          | -864        |
| time/                   |             |
|    fps                  | 482         |
|    iterations           | 62          |
|    time_elapsed         | 2107        |
|    total_timesteps      | 1015808     |
| train/                  |             |
|    approx_kl            | 0.019504689 |
|    clip_fraction        | 0.221       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.88       |
|    explained_variance   | 0.945       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0533     |
|    n_updates            | 610         |
|    policy_gradient_loss | -0.0313     |
|    value_loss           | 0.000189    |
-----------------------------------------

Training completed in 0:35:18.439536
Model saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\rl_models\ppo_cost.zip
VecNormalize saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\rl_models\ppo_cost_vecnormalize.pkl

In [3]:
# Evaluation: run PPO on test set and compare with LP baseline

results = {}

for scenario in [SCENARIO_OVERLOAD, SCENARIO_COST]:
    comp = evaluate_scenario(scenario)
    results[scenario] = comp
    print_comparison(comp)

results

============================================================
Evaluating scenario: OVERLOAD
============================================================
Latest model: models\random_forest_cpu_total_usage_20251111_221930.pkl
✓ Model loaded: models\random_forest_cpu_total_usage_20251111_221930.pkl
  Model: random_forest
  Target: cpu_total_usage
  Saved at: 2025-11-11 22:19:30
Latest model: models\svr_memory_usage_pct_20251111_184735.pkl
✓ Model loaded: models\svr_memory_usage_pct_20251111_184735.pkl
  Model: svr
  Target: memory_usage_pct
  Saved at: 2025-11-11 18:47:35
Latest model: models\random_forest_system_load_20251111_221944.pkl
✓ Model loaded: models\random_forest_system_load_20251111_221944.pkl
  Model: random_forest
  Target: system_load
  Saved at: 2025-11-11 22:19:44
Loaded model from E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\rl_models\ppo_overload.zip

Running PPO rollout for scenario: overload
Latest model: models\random_forest_cpu_total_usage_20251111_221930.pkl
✓ Model loaded: models\random_forest_cpu_total_usage_20251111_221930.pkl
  Model: random_forest
  Target: cpu_total_usage
  Saved at: 2025-11-11 22:19:30
Latest model: models\svr_memory_usage_pct_20251111_184735.pkl
✓ Model loaded: models\svr_memory_usage_pct_20251111_184735.pkl
  Model: svr
  Target: memory_usage_pct
  Saved at: 2025-11-11 18:47:35
Latest model: models\random_forest_system_load_20251111_221944.pkl
✓ Model loaded: models\random_forest_system_load_20251111_221944.pkl
  Model: random_forest
  Target: system_load
  Saved at: 2025-11-11 22:19:44
PPO schedule saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\forecast_result\ppo_schedule_test_overload.csv
PPO 30min bucket saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\forecast_result\ppo_schedule_30min_overload.csv
Warning: LP schedule not found at E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\forecast_result\vm_schedule.csv
Run 'python vm_resource_planner.py' first to generate baseline.

============================================================
RESULTS: OVERLOAD
============================================================

PPO Performance:
  Total VM Cost: $29.1136
  Total Switching Cost: $4.9800
  Total Cost: $34.0936
  SLA Violations: 4 (0.8%)
  Mean CPU Utilization: 0.9%
  Mean Memory Utilization: 0.0%

============================================================
Evaluating scenario: COST
============================================================
Latest model: models\random_forest_cpu_total_usage_20251111_221930.pkl
✓ Model loaded: models\random_forest_cpu_total_usage_20251111_221930.pkl
  Model: random_forest
  Target: cpu_total_usage
  Saved at: 2025-11-11 22:19:30
Latest model: models\svr_memory_usage_pct_20251111_184735.pkl
✓ Model loaded: models\svr_memory_usage_pct_20251111_184735.pkl
  Model: svr
  Target: memory_usage_pct
  Saved at: 2025-11-11 18:47:35
Latest model: models\random_forest_system_load_20251111_221944.pkl
✓ Model loaded: models\random_forest_system_load_20251111_221944.pkl
  Model: random_forest
  Target: system_load
  Saved at: 2025-11-11 22:19:44
Loaded model from E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\rl_models\ppo_cost.zip

Running PPO rollout for scenario: cost
Latest model: models\random_forest_cpu_total_usage_20251111_221930.pkl
✓ Model loaded: models\random_forest_cpu_total_usage_20251111_221930.pkl
  Model: random_forest
  Target: cpu_total_usage
  Saved at: 2025-11-11 22:19:30
Latest model: models\svr_memory_usage_pct_20251111_184735.pkl
✓ Model loaded: models\svr_memory_usage_pct_20251111_184735.pkl
  Model: svr
  Target: memory_usage_pct
  Saved at: 2025-11-11 18:47:35
Latest model: models\random_forest_system_load_20251111_221944.pkl
✓ Model loaded: models\random_forest_system_load_20251111_221944.pkl
  Model: random_forest
  Target: system_load
  Saved at: 2025-11-11 22:19:44
PPO schedule saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\forecast_result\ppo_schedule_test_cost.csv
PPO 30min bucket saved to E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\forecast_result\ppo_schedule_30min_cost.csv
Warning: LP schedule not found at E:\PROJECTS\Demand-Forecasting-and-Resource-Optimization-on-Cloud-Infrastructure\forecast_result\vm_schedule.csv
Run 'python vm_resource_planner.py' first to generate baseline.

============================================================
RESULTS: COST
============================================================

PPO Performance:
  Total VM Cost: $36.8128
  Total Switching Cost: $5.3800
  Total Cost: $42.1928
  SLA Violations: 0 (0.0%)
  Mean CPU Utilization: 0.1%
  Mean Memory Utilization: 0.0%

{'overload': {'scenario': 'overload',
  'timestamp': '2025-12-11 00:17:55',
  'ppo': {'total_vm_cost': 29.113599999999998,
   'total_switching_cost': 4.98,
   'total_cost': 34.093599999999995,
   'sla_violations': 4,
   'sla_violation_rate': 0.008333333333333333,
   'mean_cpu_utilization': 0.9006508297720798,
   'mean_mem_utilization': 0.0,
   'n_steps': 480},
  'ppo_30min': {'total_vm_cost': 0.0,
   'total_switching_cost': 0.0,
   'total_cost': 0.0,
   'sla_violations': 4,
   'sla_violation_rate': 0.023905723905723906,
   'n_buckets': 9}},
 'cost': {'scenario': 'cost',
  'timestamp': '2025-12-11 00:19:34',
  'ppo': {'total_vm_cost': 36.812799999999996,
   'total_switching_cost': 5.38,
   'total_cost': 42.192800000000005,
   'sla_violations': 0,
   'sla_violation_rate': 0.0,
   'mean_cpu_utilization': 0.0510493736219017,
   'mean_mem_utilization': 0.0,
   'n_steps': 480},
  'ppo_30min': {'total_vm_cost': 0.0,
   'total_switching_cost': 0.0,
   'total_cost': 0.0,
   'sla_violations': 0,
   'sla_violation_rate': 0.0,
   'n_buckets': 9}}}

In [4]:
# Inspect generated PPO schedules and comparison JSON

import pandas as pd
from pathlib import Path

RESULTS_DIR = Path("forecast_result")

ppo_overload_path = RESULTS_DIR / "ppo_schedule_test_overload.csv"
ppo_cost_path = RESULTS_DIR / "ppo_schedule_test_cost.csv"
comparison_path = RESULTS_DIR / "ppo_vs_lp_comparison.json"

print("PPO overload schedule exists:", ppo_overload_path.exists())
print("PPO cost schedule exists:", ppo_cost_path.exists())
print("Comparison JSON exists:", comparison_path.exists())

if ppo_overload_path.exists():
    df_over = pd.read_csv(ppo_overload_path)
    display(df_over.head())

if ppo_cost_path.exists():
    df_cost = pd.read_csv(ppo_cost_path)
    display(df_cost.head())

# Show 30-minute bucketed outputs (align with LP)
ppo_overload_bucket = RESULTS_DIR / "ppo_schedule_30min_overload.csv"
ppo_cost_bucket = RESULTS_DIR / "ppo_schedule_30min_cost.csv"
print("PPO overload 30min bucket exists:", ppo_overload_bucket.exists())
print("PPO cost 30min bucket exists:", ppo_cost_bucket.exists())

if ppo_overload_bucket.exists():
    df_over_b = pd.read_csv(ppo_overload_bucket)
    display(df_over_b.head())

if ppo_cost_bucket.exists():
    df_cost_b = pd.read_csv(ppo_cost_bucket)
    display(df_cost_b.head())

if comparison_path.exists():
    import json
    with open(comparison_path, "r") as f:
        comp_data = json.load(f)
    comp_data

PPO overload schedule exists: True
PPO cost schedule exists: True
Comparison JSON exists: False

,timestamp,allocation,vm_cost_per_hour,switching_cost,total_cost_per_hour,cpu_allocated_cores,mem_allocated_gb,cpu_vm_only,mem_vm_only,cpu_required_cores,mem_required_gb,cpu_overflow_cores,mem_overflow_gb,cpu_utilization_pct,mem_utilization_pct,sla_violation_flag
0,1970-01-25 01:05:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.24,0.258175,0.0,0,0.0,0.0,0
1,1970-01-25 01:06:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.22,0.258186,0.0,0,0.0,0.0,0
2,1970-01-25 01:06:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.13,0.258044,0.0,0,0.0,0.0,0
3,1970-01-25 01:07:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.08,0.257840,0.0,0,0.0,0.0,0
4,1970-01-25 01:07:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.10,0.258327,0.0,0,0.0,0.0,0

,timestamp,allocation,vm_cost_per_hour,switching_cost,total_cost_per_hour,cpu_allocated_cores,mem_allocated_gb,cpu_vm_only,mem_vm_only,cpu_required_cores,mem_required_gb,cpu_overflow_cores,mem_overflow_gb,cpu_utilization_pct,mem_utilization_pct,sla_violation_flag
0,1970-01-25 01:05:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.24,0.258175,0.0,0,0.0,0.0,0
1,1970-01-25 01:06:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.22,0.258186,0.0,0,0.0,0.0,0
2,1970-01-25 01:06:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.13,0.258044,0.0,0,0.0,0.0,0
3,1970-01-25 01:07:00,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.08,0.257840,0.0,0,0.0,0.0,0
4,1970-01-25 01:07:30,Host only,0.0,0.0,0.0,0.7,3.0,0.0,0.0,0.10,0.258327,0.0,0,0.0,0.0,0

PPO overload 30min bucket exists: True
PPO cost 30min bucket exists: True

,timestamp,vm_cost_per_hour_sum,switching_cost_sum,total_cost_per_hour_sum,cpu_required_cores_max,mem_required_gb_max,cpu_overflow_cores_max,mem_overflow_gb_max,cpu_vm_only_max,mem_vm_only_max,sla_violation_flag_sum,sla_violation_flag_mean
0,1970-01-25 01:00:00,0.0000,0.00,0.0000,0.670,0.319772,0.00,0,0.0,0.0,0,0.000000
1,1970-01-25 01:30:00,2.8288,1.21,4.0388,2.090,0.291744,1.39,0,26.0,136.0,1,0.016667
2,1970-01-25 02:00:00,0.0000,0.00,0.0000,0.680,0.281257,0.00,0,0.0,0.0,0,0.000000
3,1970-01-25 02:30:00,0.0000,0.00,0.0000,0.467,0.277264,0.00,0,0.0,0.0,0,0.000000
4,1970-01-25 03:00:00,2.0480,0.59,2.6380,1.660,0.279743,0.96,0,36.0,156.0,0,0.000000

,timestamp,vm_cost_per_hour_sum,switching_cost_sum,total_cost_per_hour_sum,cpu_required_cores_max,mem_required_gb_max,cpu_overflow_cores_max,mem_overflow_gb_max,cpu_vm_only_max,mem_vm_only_max,sla_violation_flag_sum,sla_violation_flag_mean
0,1970-01-25 01:00:00,0.0000,0.00,0.0000,0.670,0.319772,0.00,0,0.0,0.0,0,0.0
1,1970-01-25 01:30:00,14.4544,2.02,16.4744,2.090,0.291744,1.39,0,134.0,828.0,0,0.0
2,1970-01-25 02:00:00,0.0000,0.00,0.0000,0.680,0.281257,0.00,0,0.0,0.0,0,0.0
3,1970-01-25 02:30:00,0.0000,0.00,0.0000,0.467,0.277264,0.00,0,0.0,0.0,0,0.0
4,1970-01-25 03:00:00,4.3712,1.42,5.7912,1.660,0.279743,0.96,0,80.0,312.0,0,0.0